### ISSUE TITLE
Use sdelete64.exe on x64 system

### ISSUE THREAD

**Issue by JonathanPitre** [EUCweb/BIS-F#101]
Since the last couple version of sdelete, there's an x64 binary.

We should the appropriate binary one according to the system architecture.

**Comment by matthias-schlimm** [comment]
good point, means new BIS-F relesae will support SDelete v2.02 or newer and pick up the right executable based on OS Architecture

https://docs.microsoft.com/en-us/sysinternals/downloads/sdelete

**Comment by matthias-schlimm** [comment]
included in BB_develop and as a minimum version v2.02 or newer
