### ISSUE TITLE
Matrix42 Empirum Preparation > Service MATRIXAUT not always exists

### ISSUE THREAD

**Issue by vMathias79** [EUCweb/BIS-F#104]
Not in all installations of the Matrix42 Empirum agent the MATRIXAUT service does exist. Therefore the script tries to stop/start a non-existing service in 10_PrepBISF_Empirum.ps1

Suggestion: Wrap it in a condition if the service exists.

**Comment by vMathias79** [comment]
Updates script already in testing on customer site. Will create pull request as soon as I get a positive reply

**Comment by matthias-schlimm** [comment]
update ReleaseNotes.txt
