### ISSUE TITLE
Keep Windows Administrative Tools in Startmenu

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#105]
keep Windows Admistrative Tools ins Startmenu.

Workaround `97_PrepBISF_PRE_BaseImage.ps1`, line

`replace line 194 `

**old:**
Command="Remove-Item '$Dir_AllUsersStartMenu' -Recurse -Force -ErrorAction SilentlyContinue"};
			
**new:**
Command="Get-ChildItem -path '$Dir_AllUsersStartMenu' -Exclude 'Administrative Tools' | remove-item -Force -Recurse"};

**Comment by EUCweb** [comment]
### Grab a copy of the scripts below based on your BIS-F Release

**BIS-F 6.1.0 build 01.xxx**
https://github.com/EUCweb/BIS-F/blob/master/Framework/SubCall/Preparation/97_PrepBISF_PRE_BaseImage.ps1

**Bugs Bunny Release:**
https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/97_PrepBISF_PRE_BaseImage.ps1
