### ISSUE TITLE
ADMX extension: Configure WEM Cache to persistent drive

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#11]
_From @matthias-schimm on March 12, 2018 20:31_

I have a feature request - can we make the move of the WEM cache optional?? At the moment i believe BIS-F moves it to the PVS Cache Drive, I don't always want that Happening

seeing more and more problems with the cache being moved to non standard location - seems to be far more reliable to run the refreshcache startup script and leave the cache in the default location. Its tiny, has basically zero impact on the environment, and you avoid weird stuff going on. Don't get me wrong, there is obviously come current guidance that says do it - but there really isnt a clear explanation as to why - and if you use MCS, there is no move of the Cache.. I think it would be nice to have it optional so you aren't forced to move it if you don't want to - its better to have the latest version of the cache baked into the Image for computer based settings - and then just let the user refresh happen on logon

_Copied from original issue: EUCweb/BIS-F#17_

**Comment by EUCweb** [comment]
Open topic: if the policy is disabled, the WEM Cache must configured back to the origin path if previous configured to persistent drive

**Comment by EUCweb** [comment]
Default Settings from the WEM Agent 

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Norskale\Agent Host]
"AgentServiceDebugModeLocalOverride"=dword:00000000
"AgentLocation"="C:\\Program Files (x86)\\Norskale\\Norskale Agent Host\\"
"AgentDebugModeLocalOverride"=dword:00000000
"AgentServiceUseCacheEvenIfOnline"=dword:00000000
"AgentCacheAlternateLocation"=""
"AgentServiceUseNonPersistentCompliantHistory"=dword:00000000
"EnableUserCentricIntelligentOptimization"=dword:00000001

**Comment by matthias-schlimm** [comment]
- Read $AgentLocation from HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Norskale\Agent Host

- Default $AgentLocation\Local Databases\LocalAgentCache.sdf

**Comment by matthias-schlimm** [comment]
![BISF-WEM-ADMX](https://user-images.githubusercontent.com/34108484/66115970-37964a80-e5d2-11e9-9666-3862a244ac00.JPG)

LIC_BISF_CLI_WEMCfg set to Yes if policy is configured
LIC_BISF_CLI_WEMCache set to 1 if redirection is enabled
LIC_BISF_CLI_WEMFolder = "WEMCache"
LIC_BISF_CLI_WEMb = 1 (Enable custom WEMCache folder name)

Must be modified for MCSIO as well

**Comment by matthias-schlimm** [comment]
ENH 11 ADMX extension: Configure WEM Cache to persistent drive (PVS and MCSIO)
