### ISSUE TITLE
CTX optimizer: Multiple Templates with AutoSelect for OS Template

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#112]
With the new Feature called [multiple Templates](https://github.com/EUCweb/BIS-F/issues/111) you will loose AutoSelect for the OS Template.

In 10_PrepBISF_CTX.ps1 remove Line 418 as follows

`"& ""$fileExists"" -Source ""$template""$groups-mode $mode -OutputXml ""$output_xml""" | Out-File $tmpPS1 -Encoding default`

and replace with this special code

```
IF ($template -eq "AutoSelect") {
"& ""$fileExists"" -mode $mode -OutputXml ""$output_xml""" | Out-File $tmpPS1 -Encoding default
} ELSE {
"& ""$fileExists"" -Source ""$template""$groups-mode $mode -OutputXml ""$output_xml""" |  Out-File $tmpPS1 -Encoding default
}

```

In the BIS-F ADMX for the CTX Templates you can enter **AutoSelect,PVS_Target.xml** to get this work

**Comment by matthias-schlimm** [comment]
- If no template is specified, BIS-F triggers Optimizer with AutoSelect

- Optimizer XML filename  has the template Name included

**Comment by matthias-schlimm** [comment]
complete description https://eucweb.com/kba/0107190500

**Comment by matthias-schlimm** [comment]
ToDo: merge code from 6.1.2 to BB_develop

**Comment by EUCweb** [comment]
merged now into BB_develop
