### ISSUE TITLE
WinSxs optimization reached the MaxExecutionTime

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#113]
As I heard from some customers, the WinSxs optimizations that is executed since Version 6.1.1, was reached the MaxExecutionTime per default of 60 minutes and the process is terminated, not possible for future update.

You can change it manually, until a patch is available as follows:

1. open up https://github.com/EUCweb/BIS-F/blob/release/6.1.1_build_01.105/Framework/SubCall/Global/BISF.psm1

2. go to function **Optimize-WinSxs** in Line **1532**

3. Change line 1555 from

**before:**
`Show-BISFProgressBar -CheckProcess "Dism" -ActivityText "run DISM to cleanup WinSxs Folder ..."`

**after:**
`Show-BISFProgressBar -CheckProcess "Dism" -ActivityText "run DISM to cleanup WinSxs Folder ..." -MaximumExecutionMinutes 120`

The Parameter **MaximumExecutionMinutes 120** set the Value in minutes before terminate the DISM process (2 hours)

**Comment by matthias-schlimm** [comment]
will fixed with https://github.com/EUCweb/BIS-F/issues/115
