### ISSUE TITLE
App Crash since sealing with 6.1.1

### ISSUE THREAD

**Issue by korbinianthiel** [EUCweb/BIS-F#114]
When image is sealed with BIS-F 6.1.1 our CAD software crashes with access violation in mfc140u.dll
With previous 6.1.0 this does not happen. What have changed, which might causes this crash?

Thanks
Korbinian

**Comment by matthias-schlimm** [comment]
Please check https://eucweb.com/docs/bis-f/whats-new

Please have a look to https://github.com/EUCweb/BIS-F/issues/113 can you comment out line 1554 the start-process line.

**Comment by korbinianthiel** [comment]
I will try version 6.1.1 with WinSxS optimizations disabled.

Thanks for the quick reply.

**Comment by matthias-schlimm** [comment]
Will fixed with https://github.com/EUCweb/BIS-F/issues/115

**Comment by matthias-schlimm** [comment]
With the upcoming 6.1.2 Version you can Control WinSxS with the GPO, check out https://eucweb.com/docs/bis-f/run-bis-f/winsxs-optimization. this will fix the issue
