### ISSUE TITLE
Add Tanium support

### ISSUE THREAD

**Issue by toussman** [EUCweb/BIS-F#118]
The Tanium Client requires generalization during the image seal. 

Solution consists in stopping the service and delete client specific data, as per vendor documentation: 
https://docs.tanium.com/client/client/os_imaging.html

See attached script: 

[10_PrepBISF_Tanium.txt](https://github.com/EUCweb/BIS-F/files/3405202/10_PrepBISF_Tanium.txt)

**Comment by matthias-schlimm** [comment]
Thank you very much, I will change the Code for more BIS-F complaint

**Comment by matthias-schlimm** [comment]
@toussman can you grab a copy https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Preparation/10_PrepBISF_Tanium.ps1 and check it please, I have re-written it to the standard BIS-F usage

**Comment by toussman** [comment]
I am on holiday. Will do upon my return on September. Many thanks for
looking into it.
