### ISSUE TITLE
Add nVidia driver support

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#12]
**#HINT (Citrix XenDesktop 7.6-7.11 customers)**
The NVIDIA GRID API provides direct access to the frame buffer of the GPU, providing the fastest possible frame rate for a smooth and interactive user experience. If you install NVIDIA drivers before you install a VDA with HDX 3D Pro, NVIDIA GRID is enabled by default.
To enable NVIDIA GRID on a VM, disable Microsoft Basic Display Adapter from the Device Manager. Run the following command and then restart the VDA: Montereyenable.exe -enable -noreset
If you install NVIDIA drivers after you install a VDA with HDX 3D Pro, NVIDIA GRID is disabled. Enable NVIDIA GRID by using the Montereyenable tool provided by NVIDIA.
To disable NVIDIA GRID, run the following command and then restart the VDA: Montereyenable.exe -disable -noreset
**#HINT (Citrix XenDesktop 7.12/7.13 customers)**
The NVIDIA GRID API provides direct access to the frame buffer of the GPU, providing the fastest possible frame rate for a smooth and interactive user experience. If you install NVIDIA drivers before you install a VDA with HDX 3D Pro, NVIDIA GRID is enabled by default.
To enable NVIDIA GRID on a VM, disable Microsoft Basic Display Adapter from the Device Manager. Run the following command and then restart the VDA: NVFBCEnable.exe -enable -noreset
If you install NVIDIA drivers after you install a VDA with HDX 3D Pro, NVIDIA GRID is disabled. Enable NVIDIA GRID by using the NVFBCEnable tool provided by NVIDIA.
To disable NVIDIA GRID, run the following command and then restart the VDA: NVFBCEnable.exe -disable -noreset

enable or disable possible with ADMX to set
Servicename: nvsvc
DisplayName: nVIDIA Diplay Driver Service

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#16
