### ISSUE TITLE
Logfile using *.log filenameextension

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#121]
currently the logfile is using the filenameextension *.bis, for better support change it to *.log

**Comment by EUCweb** [comment]
must be changed in the following scripts



- [x] PersBISF_Start.ps1 

- [x] PrepBISF_Start1.ps1

- [x] CMTrace Logfileviwer, remove bis extension

**Comment by EUCweb** [comment]
BB_develop branch
