### ISSUE TITLE
Citrix Optimizer Templateprefix support

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#122]
Custom Templates with AutoSelect does not work.

For AutoSelect to work with custom templates, BIS-F would need to add support for -TemplatePrefix argument. This however means that they will need to rename all templates to match this syntax.

Means, if I have a template called **EUCweb_Windows_10_1903.xml** I must use -TemplatePrefix **EUCweb_Windows** as an additional argument to get this work.

ADMX Change required

**Comment by matthias-schlimm** [comment]
- Codechange in 90_PrepBISF_CTX.ps1
- ADMX Change

Codechange done

branch https://github.com/EUCweb/BIS-F/tree/develop 

![CTXO_TemplatePrefix_default](https://user-images.githubusercontent.com/34108484/61978869-92b82980-aff2-11e9-8cb5-1f8b432f1cef.jpg)

**Comment by EUCweb** [comment]
[HOW TO] Using Citrix Optimizer with TemplatePrefix https://eucweb.com/kba/1208191514

**Comment by EUCweb** [comment]
Release with 6.1.3 and merged now into BB_develop
