### ISSUE TITLE
ADMX: Wrong description in Global -> Configure Personalization

### ISSUE THREAD

**Issue by xenadmin** [EUCweb/BIS-F#125]
**Describe the bug**
The dropdown values don't fit the Policy description. 
Never <-> None
All <-> All
PrivateMode <-> ReadWrite

**To Reproduce**
ADMX in Central Store -> open GPMC -> Computer -> BISF -> Global -> Configure Personalization

**Expected behavior**
The values should match.

**Screenshots**
![image](https://user-images.githubusercontent.com/12057348/62933468-88ec3f80-bdc2-11e9-9a47-f8d26f7dd7d6.png)

**Additional context**
I think I made my point clear ;-)

**Comment by matthias-schlimm** [comment]
Thanks Marco, you‘re right.

**Comment by matthias-schlimm** [comment]
@xenadmin fixed and will be published with Bugs Bunny Release first 7 1912


![2019-08-17_21-14-13](https://user-images.githubusercontent.com/34108484/63216352-271a3580-c134-11e9-932d-5dca7d7a7540.jpg)
