### ISSUE TITLE
Personalization is in Active State Override

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#127]
As per https://eucweb.com/kba/27190801 this occasionally happens and BIS-F requires changing the key for it to proceed. Can we add an option to automatically change this and re-run the optimization via user input rather than having to go into the registry and change the key manually?

Well aware that this happens due to an underlying issue of some sort, but more often than not it's random and hard to troubleshoot - allow a "Change and Continue" option would help consumers. worth putting a warning in, but make it user-friendly - most people just go and change the key anyway

**Comment by matthias-schlimm** [comment]
We can change the MaxExecutionTimeOut via ADMX for this and afterwards the preparation starts automatically. Can this be a option ?

And additional in ADMX to options:

- Change and Continue
- Do not change and wait

**Comment by JamesKindon** [comment]
Yep that would work well I think - easier option

**Comment by matthias-schlimm** [comment]
A first draft of the new GPO @JamesKindon 

![ActiveStateOverride](https://user-images.githubusercontent.com/34108484/65369665-4125c700-dc50-11e9-8b69-235e83de04d3.JPG)

![ActiveStateOverride](https://user-images.githubusercontent.com/34108484/65369680-77634680-dc50-11e9-91af-3ae0029c5ee7.JPG)

**Comment by matthias-schlimm** [comment]
_LIC_BISF_CLI_PersonalizationOverride_  (DWORD)
1 = Do not change and wait 
2 = Change and continue

_LIC_BISF_CLI_PersonalizationOverrideTimeOut_  (DWORD)

**Comment by matthias-schlimm** [comment]
ADMX finished, coding not yet

**Comment by matthias-schlimm** [comment]
Coding and ADMX done
https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/PrepBISF_Start.ps1
https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/PersBISF_Start.ps1
