### ISSUE TITLE
Office 365 detection

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#13]
check root path HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun
<img width="353" alt="o365" src="https://user-images.githubusercontent.com/34108484/37307621-764dc628-2633-11e8-93c9-1e5fc8e9e45c.png">

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#15
