### ISSUE TITLE
Computer not shutdown after VHDX Capture

### ISSUE THREAD

**Issue by gangsterrapper22** [EUCweb/BIS-F#131]
**Describe the bug**
I have run the BIS-F Script on a Windows Server 2016 and after the VHDX has finished capture, then the VM isn't Shutdown but it is configured in the GPO. See this also in the attached Screenshot.
![gpo](https://user-images.githubusercontent.com/26838368/63228805-f5b76d80-c1f8-11e9-9898-76de65038551.PNG) The last Line I see in the Log is "INFORMATION... | Processing function Show-BISFProgressBar". The Script was started as local Administrator.

When I start the Captured Image, then I get the Message why the Computer was shutdown unexpected. See the message also in the Screenshot.
![shutdown](https://user-images.githubusercontent.com/26838368/63228829-4af37f00-c1f9-11e9-8e0c-1898883e7f34.PNG)

The Windows Server was installed via a SCCM Task Sequence and the Version of the Script is Version 6.1.3 build 01.110.

Is there something which I did wrong or is there something wrong with the Script?

Thnaks for your help.

**Comment by matthias-schlimm** [comment]
Did you start BIS-F sealing from a SCCM or MDT tasksequence ? 

and check this one please: Delete that value "DirtyShutdown" from HKLM\Software\Microsoft\Windows\CurrentVersion\Reliability

Will fixed in next BIS-F release 

Please also upload here the BIS-F preparation log

**Comment by matthias-schlimm** [comment]
The shutdown is supressed if BIS-F sealing is triggered from SCCM or mdt tasksequence

**Comment by gangsterrapper22** [comment]
I started the Script manually with the local Administrator Account after the OSD was done. I don't have it in the SCCM Task Sequence itself that it should run. The SCCM Client is installed on this Machine. I will check the Reg Key tomorrow. 
I have uploaded also the Log for you.
[Prep_BIS_20190818-164657.txt](https://github.com/EUCweb/BIS-F/files/3513444/Prep_BIS_20190818-164657.txt)

**Comment by matthias-schlimm** [comment]
Please send the C:\ProgramData\Citrix\ImagingWizard\ImagingWizard.log

**Comment by matthias-schlimm** [comment]
The script runs not to the end, hopefully we see more in the ImagingWizard.log

**Comment by gangsterrapper22** [comment]
I have attached it. Thanks.
[ImagingWizard.log](https://github.com/EUCweb/BIS-F/files/3513459/ImagingWizard.log)

**Comment by matthias-schlimm** [comment]
Can you create a new vDIsk on the PVS, attach this to the Image and Boot it from Hard Disk, reconfigure BIS-F without UNC path an Start the sealing again 


 I‘m on the road now for the next 3 hours, will see your response Tomorrow,

**Comment by matthias-schlimm** [comment]
That’s to less inside the log

**Comment by gangsterrapper22** [comment]
I will try it tomorrow again and let you know then. Thanks for your help so far. 
Can you tell me what do you mean with without UNC Path?

**Comment by gangsterrapper22** [comment]
I created now a new vDisk and let the VM Boot from it via Hard Disk. From the GPO I removed now the UNC Path. After this the Script ran without issues and has shutdown the VM after it was finished. When I logon, I get also no warning anymore, that the Server was shutdown unexpectedly. I will close the issue then.
Thanks for your help.
