### ISSUE TITLE
Detect WVD Multi User

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#132]
During BIS-F Sealing, it's necassary to detect WVD Multi User for BIS-F System Management and not run sysprep.

Need Powershell command to see the difference characteristics

**Comment by matthias-schlimm** [comment]
AppServerClient --> Enabled is only on multiuser WVD

![image](https://user-images.githubusercontent.com/34108484/63381439-f981f600-c398-11e9-9a09-c394a3c0b9f7.png)

**Comment by matthias-schlimm** [comment]
```
$AppServerClientState= (Get-WindowsOptionalFeature -Online | Where-Object { $_.FeatureName -eq "AppServerClient"}).State

IF ($AppServerClientState -eq "Enabled")
{ $WVD = $true} ELSE {$WVD = $false}
```

**Comment by thomaskrampe** [comment]
There is also a RDAgentBootLoader and a RDAgent service running on a WVD machine.

**Comment by matthias-schlimm** [comment]
(Get-WMIObject Win32_OperatingSystem).Name = "Microsoft Windows 10 Enterprise for Virtual Desktops"

**Comment by matthias-schlimm** [comment]
included in BB_devlop branch now
