### ISSUE TITLE
Citrix WEM 1909 - Agent is not detected

### ISSUE THREAD

**Issue by citrixguyblog** [EUCweb/BIS-F#139]
With Citrix WEM 1909 the service name changed (new installation) and is not detected by BIS-F anymore.
- No WEM Cache will get redirected
- When working with MCS/PVS the Targets are not capable of refreshing the cache 

Script: 90_PrepBISF_CTX.ps1
Line: 249

#Citrix Workspace Environment Management Agent
	function Set-WEMAgent {
		$product = "Citrix Workspace Environment Management (WEM) Agent"
        $services = "Norskale Agent Host Service", "Citrix WEM Agent Host Service"
		$AgentCacheFolder = "WEMAgentCache"  # ->  $LIC_BISF_CtxPath\$AgentCacheFolder

        foreach ($service in $services)
        {
         $svc = Test-BISFService -ServiceName "$service" -ProductName "$product"
		 IF ($svc -eq $true) {
            $servicename = $service
			Invoke-BISFService -ServiceName "$servicename" -Action Stop
            
        }

**Comment by citrixguyblog** [comment]
Here is the modification for the Personalisation:

Script: 02_PersBISF_CTX.ps1
Line: 145

	#Citrix Workspace Environment Management Agent 
    $product ="Citrix Workspace Environment Management (WEM) Agent"
    $services = "Norskale Agent Host Service", "Citrix WEM Agent Host Service"

    foreach ($service in $services)
     {
       $svc = Test-BISFService -ServiceName "$service" -ProductName "$product"

       	IF ($svc -eq $true)
	    {
         $servicename = $service
		 Invoke-BISFService -ServiceName "$servicename" -Action Stop
		 Start-Sleep $Wait1
		 Invoke-BISFService -ServiceName "$servicename" -Action Start
		 Invoke-BISFService -ServiceName "Netlogon" -Action Start	
		
		 #read WEM AgentAlternateCacheLocation from registry
		 $REG_WEMAgent = "HKLM:\SYSTEM\CurrentControlSet\Control\Norskale\Agent Host"
		 $WEMAgentLocation = (Get-ItemProperty $REG_WEMAgent).AgentLocation
		 Write-BISFLog -Msg "WEM Agent Location: $WEMAgentLocation"

		 #read WEM Agent Host BrokerName from registry 
		 $REG_WEMAgentHost = "HKLM:\SOFTWARE\Policies\Norskale\Agent Host"
		 $WEMAgentHostBrokerName = (Get-ItemProperty $REG_WEMAgentHost).BrokerSvcName
		 IF (!$WEMAgentHostBrokerName) {Write-BISFLog -Msg "WEM Agent BrokerName not specified through WEM ADMX" } ELSE {Write-BISFLog -Msg "WEM Agent BrokerName: $WEMAgentHostBrokerName"}

		 $WEMAgentCacheUtil = "$WEMAgentLocation" + "AgentCacheUtility.exe"
			 
		
		 Write-BISFLog -Msg "Running Agent Cache Management Utility with $product BrokerName $WEMAgentHostBrokerName " -ShowConsole -Color DarkCyan -SubMsg
		 Start-BISFProcWithProgBar -ProcPath "$WEMAgentCacheUtil" -Args "-RefreshCache" -ActText "Running Agent Cache Management Utility" | Out-Null
		 
	}
     }

**Comment by matthias-schlimm** [comment]
thanks Julian, if you aware with Github pull request are welcome too and easier to handle :-)

**Comment by citrixguyblog** [comment]
Going to install a new master when I find some free time and verify if everything is working as expected.
After this I will try to do a pull request. See you tomorrow @VCBAWUE

**Comment by chezzer64** [comment]
I've also come across this issue and was going to suggest the relevant code update to support both old and new WEM Agent Service names.  Looking at the proposed code fix, I'd recommend using the service name rather than display name i.e. WemAgentSvc rather than "Citrix WEM Agent Host Service". 

Also, I've noticed that when using the the Citrix Cloud WEM Service, the WEM Agent uses reg key "HKLM:\SOFTWARE\Policies\Norskale\Agent Host\CloudConnectorList" instead of "HKLM:\SOFTWARE\Policies\Norskale\Agent Host\BrokerSvcName".  Would be nice to get this supported in the code update - though it is only cosmetic (reported in the BIS-F Log) and not actually used in any commands from what I can see.

Happy to help with the PR if required?

**Comment by matthias-schlimm** [comment]
If anyone has the coding finished, send a PR. We can working together on this 👍


Am 25.09.2019 um 16:55 schrieb chezzer64 <notifications@github.com>:

**Comment by citrixguyblog** [comment]
@chezzer64: Can you send me your e-mail address? Implemented your suggestion with the service name and the CloudConnectorList.

**Comment by chezzer64** [comment]
@citrixguyblog - you can reach me at chezzer64.github @ outlook.com

**Comment by citrixguyblog** [comment]
Here is the updated script code.
[02_PersBISF_CTX_wem1909.txt](https://github.com/EUCweb/BIS-F/files/3679591/02_PersBISF_CTX_wem1909.txt)
[90_PrepBISF_CTX_wem1909.txt](https://github.com/EUCweb/BIS-F/files/3679592/90_PrepBISF_CTX_wem1909.txt)

Thanks @chezzer64 for doing some changes and final testing.

**Comment by matthias-schlimm** [comment]
@citrixguyblog @chezzer64  included now in Bugs Bunny Release

**Comment by matthias-schlimm** [comment]
Please note this **ADMX extension: Configure WEM Cache to persistent drive** https://github.com/EUCweb/BIS-F/issues/11 must be done as well
