### ISSUE TITLE
ADMX: enable additional time for Delay Desktop Service

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#14]
ADMX Extension:   
add checkbock -> enable additional time 
add number field -> Delay in seconds (default: 0)
 
If BIS-F is finished with the personalization task, you can enter here an additional time value to start the Desktop Service after this time value. 
Please Note: if BIS-F is crashed during personalization, the Desktop Service is not started and the Machine(s) are not registered on the XenDesktop Broker

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#14
