### ISSUE TITLE
FSLogix App Masking URL Rule Files are missing from FSLogix Personalisation

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#141]
Currently we cover FRX and FXA files, however URL rulesets are XML based. Can we please add to the BIS-F FSLogix Module
https://docs.microsoft.com/en-us/fslogix/java-version-control-rules-ht

**Comment by matthias-schlimm** [comment]
MS: ENH 141 - Add FSLogix App Masking URL Rule Files for personalization 

`$FSXfiles2Copy = @("*.fxr", "*.fxa", "*.xml")`
