### ISSUE TITLE
Office 365 detection

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#15]
_From @matthias-schimm on March 12, 2018 20:25_

check root path HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun
<img width="353" alt="o365" src="https://user-images.githubusercontent.com/34108484/37307621-764dc628-2633-11e8-93c9-1e5fc8e9e45c.png">

_Copied from original issue: EUCweb/BIS-F#13_

**Comment by matthias-schlimm** [comment]
22.03.2018 MS: Feature 15 - support for Office 365 ClicktoRun
