### ISSUE TITLE
Master Image mode

### ISSUE THREAD

**Issue by micswe** [EUCweb/BIS-F#156]
We need to run script at Master (Private) disk boot up. To run any automated update.

What we do, i create a new folder Structor under SubCall and Create a Imagemode folder with Custom subfolder.

I start the scripts over PersBISF_Start.ps1 in directive, Private mode yes than exit.

> ReadWrite {
> 			IF (($DiskMode -match "Private") -or ($DiskMode -match "ReadWrite"))
> 			{
> 				Start-BISFCDS
> 				Write-BISFLog -Msg "Write PersState to registry location Path: $hklm_software_LIC_CTX_BISF_SCRIPTS -Name: LIC_BISF_PersState -Value: $PersState"
> 				Set-ItemProperty -Path $hklm_software_LIC_CTX_BISF_SCRIPTS -Name "LIC_BISF_PersState" -value "$PersState" -Force #-ErrorAction SilentlyContinue
>                 #Write-BISFLog -Msg "Image in Mode $DiskMode, skip device personalization (configured: Private Mode) " -Type E -SubMsg;Exit
>                 Write-BISFLog -Msg "Image in Mode $DiskMode"
>                 #Michael Schwenke
>                 #load custom scripts
>                 $psfolder = $SubCall_Folder + "Imagemode\Custom"
>                 Invoke-BISFFolderScripts -Path "$psfolder" -Verbose:$VerbosePreference
>                 Write-BISFLog -Msg "Exit Personalization" -Type E -SubMsg;Exit
> 			} ELSE 
> 			{Write-BISFLog -Msg "Image in Mode $DiskMode, device personalization would not being skipped (configured: Private Mode)" -ShowConsole -Color DarkCyan}
> 		}
> 		Default {Write-BISFLog -Msg "Default Action selected, device personalization would not being skipped (not configured in ADMX)" -ShowConsole -Color DarkCyan}
> 	}

Any ideas for a better place ?

**Comment by matthias-schlimm** [comment]
Automated update is not a part of BIS-F, please do it with your ESD but not with BIS-F.

**Comment by micswe** [comment]
Hallo Matthias,

das ist ein Missverständnis. Ich möchte nicht die Updates mit BIS-F machen sondern die Maschine vorbereiten.

z.B. Es müssen für ESD verschiedene Dienste gestartet werden usw.

Wir haben in dem Spezielle fall Windows Update, DSM7 und weitere Dienste deaktiviert. Um die Updates zu automatisieren, müssen diese beim Systemstart wieder anlaufen, der rest kommt durch die Softwareverteilung und die kümmert sich auch darum das die Maschinen wieder versigelt werden.


Gruß

Michael Schwenke



Von: Matthias Schlimm <notifications@github.com>
Antworten an: EUCweb/BIS-F <reply@reply.github.com>
Datum: Donnerstag, 12. Dezember 2019 um 08:05
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Michael Schwenke <michael.schwenke@team-netz.com>, Author <author@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Master Image mode (#156)

Automated update is not a part of BIS-F, please do it with your ESD but not with BIS-F.

**Comment by matthias-schlimm** [comment]
Hallo Michael, 

Ok, verstanden. Windows Update Service wird im private Mode schon gestartet, Rest kannst du ganz normal über custom scripts I’m personalization Ordner machen. 



Matthias Schlimm


Am 12.12.2019 um 08:28 schrieb micswe <notifications@github.com>:

**Comment by matthias-schlimm** [comment]
please have a look into https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Personalization/99_PersBISF_StartUp.ps1 line 128. you can adopt this to your custom script

**Comment by matthias-schlimm** [comment]
but this can be a usefull function as a feature request in the ADMX to enter the servicenames to be start from BIS-F in private mode.

**Comment by micswe** [comment]
Hallo,

ja das war der erste Wurf, aber vor dem Ausführen der Scripts kommt bereits der exit wegen Private mode.

Im PersBISF_Start.ps1 wird ab Zeile 99 geprüft ob wir im Private mode sind und ein Exit des scripts gemacht. In Zeile 128 werden aber die Personal Scripts erst abgearbeitet.

Deswegen war mein Vorschlag für den Private mode, personal Scripts anzubieten.

Gruß
Michael

Von: Matthias Schlimm <notifications@github.com>
Antworten an: EUCweb/BIS-F <reply@reply.github.com>
Datum: Donnerstag, 12. Dezember 2019 um 08:49
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Michael Schwenke <michael.schwenke@team-netz.com>, Author <author@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Master Image mode (#156)

Hallo Michael,

Ok, verstanden. Windows Update Service wird im private Mode schon gestartet, Rest kannst du ganz normal über custom scripts I’m personalization Ordner machen.



Matthias Schlimm


Am 12.12.2019 um 08:28 schrieb micswe <notifications@github.com>:

**Comment by matthias-schlimm** [comment]
Dann hast du aber auch die GPO konfiguriert, dass im  private Mode keine Personalisierung laufen soll.

**Comment by micswe** [comment]
Das kann sein, mach ich mal aus. Und stell für die Dienste über gpo einen Features request.

Schönen Tag noch

Am 12.12.2019 um 09:39 schrieb Matthias Schlimm <notifications@github.com>:

﻿Dann hast du aber auch die GPO konfiguriert, dass im private Mode keine Personalisierung laufen soll.

**Comment by matthias-schlimm** [comment]
using DSM as well, for Master Image with PVS / MCS seperated OU and with GPP the DSM Service is set to automatic start. 
For the PVS/MCS Targets the DSM Service is set to disable via GPP.

works without issues.
