### ISSUE TITLE
Layer finalize is NOT allowed, this issue is sending out from AppLayering and not BIS-F

### ISSUE THREAD

**Issue by qq9338745** [EUCweb/BIS-F#157]
ELM version : 19.2.0.17 

 when running bis-f , it failed with  at layer finalize step:

 Layer finalize is NOT allowed, this issue is sending out from AppLayering and not BIS-F

+++++++++++++++++++
[Prep_BIS_CITRXALba8000_20191218-172449.txt](https://github.com/EUCweb/BIS-F/files/3991473/Prep_BIS_CITRXALba8000_20191218-172449.txt)

+++++++++++++++++++++++++++++++++++

................................................................................

12/18/2019 5:25:41 PM | temp | EXTERNAL LOG.... | Support bypass of layer integrity enforcement is NOT enabled on this machine
12/18/2019 5:25:41 PM | temp | EXTERNAL LOG.... | Layer finalize is BLOCKED
12/18/2019 5:25:41 PM | temp | EXTERNAL LOG.... | The outstanding items are:
12/18/2019 5:25:41 PM | temp | EXTERNAL LOG.... |     a Microsoft NGen operation is in progress in the background 
12/18/2019 5:25:41 PM | temp | INFORMATION... | -----snap-----
12/18/2019 5:25:41 PM | temp | INFORMATION... | Processing function Test-BISFLog
12/18/2019 5:25:41 PM | temp | INFORMATION... | Check C:\Windows\logs\BISFtmpProcessLog.log
12/18/2019 5:25:41 PM | temp | INFORMATION... | Check C:\Windows\logs\BISFtmpProcessLog.log for allowed
12/18/2019 5:25:41 PM | temp | ERROR............... | Layer finalize is NOT allowed, this issue is sending out from AppLayering and not BIS-F, please check the BIS-F log for further informations
12/18/2019 5:26:11 PM | temp | WARNING......... | Check Logfile C:\Windows\Logs\BISFLogs\Prep_BIS_CITRXALba8000_20191218-172449.bis for further informations !!
12/18/2019 5:26:11 PM | temp | INFORMATION... | Script exiting !!
12/18/2019 5:26:16 PM | temp | INFORMATION... | - - - End Of Script - - -

**Comment by matthias-schlimm** [comment]
in the bis-F log you can see, why the Layer finalze is blocked 

-----snip-----
Support bypass of layer integrity enforcement is NOT enabled on this machine
Layer finalize is BLOCKED
The outstanding items are:
**a Microsoft NGen operation is in progress in the background** 
 -----snap-----

check out https://docs.citrix.com/en-us/citrix-app-layering/4/layer/update-layer.html and https://support.citrix.com/article/CTX222099 for further informations about ngen

**Comment by matthias-schlimm** [comment]
In addition I see you use an older BIS-F version 6.1.0 build 01.101, the latest BIS-F 6.1.3 can be grabbed from my page https://eucweb.com/download-bis-f

In Version Version 6.1.0 build 01.102 I have some AppLayering approvements

**Comment by matthias-schlimm** [comment]
create an Enhancements request for this https://github.com/EUCweb/BIS-F/issues/167
