### ISSUE TITLE
Add nVidia driver support

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#16]
_From @matthias-schimm on March 12, 2018 20:22_

**#HINT (Citrix XenDesktop 7.6-7.11 customers)**
The NVIDIA GRID API provides direct access to the frame buffer of the GPU, providing the fastest possible frame rate for a smooth and interactive user experience. If you install NVIDIA drivers before you install a VDA with HDX 3D Pro, NVIDIA GRID is enabled by default.
To enable NVIDIA GRID on a VM, disable Microsoft Basic Display Adapter from the Device Manager. Run the following command and then restart the VDA: Montereyenable.exe -enable -noreset
If you install NVIDIA drivers after you install a VDA with HDX 3D Pro, NVIDIA GRID is disabled. Enable NVIDIA GRID by using the Montereyenable tool provided by NVIDIA.
To disable NVIDIA GRID, run the following command and then restart the VDA: Montereyenable.exe -disable -noreset
**#HINT (Citrix XenDesktop 7.12/7.13 customers)**
The NVIDIA GRID API provides direct access to the frame buffer of the GPU, providing the fastest possible frame rate for a smooth and interactive user experience. If you install NVIDIA drivers before you install a VDA with HDX 3D Pro, NVIDIA GRID is enabled by default.
To enable NVIDIA GRID on a VM, disable Microsoft Basic Display Adapter from the Device Manager. Run the following command and then restart the VDA: NVFBCEnable.exe -enable -noreset
If you install NVIDIA drivers after you install a VDA with HDX 3D Pro, NVIDIA GRID is disabled. Enable NVIDIA GRID by using the NVFBCEnable tool provided by NVIDIA.
To disable NVIDIA GRID, run the following command and then restart the VDA: NVFBCEnable.exe -disable -noreset

enable or disable possible with ADMX to set
Servicename: nvsvc
DisplayName: nVIDIA Diplay Driver Service

_Copied from original issue: EUCweb/BIS-F#12_

**Comment by matthias-schlimm** [comment]
![BISF-NVIDIA](https://user-images.githubusercontent.com/34108484/66253624-e5892c80-e76b-11e9-8620-245b02605750.JPG)


LIC_BISF_CLI_VDA_NVDIAGRID | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist

**Comment by matthias-schlimm** [comment]
https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Preparation/97_PrepBISF_PRE_BaseImage.ps1
