### ISSUE TITLE
AMDX Extension: Configure sDelete

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#16]
if using Citrix MCS, VMware Horizon View, Microsoft only sDelete can be run on the Systemdrive during sealing only.
 
IF Citrix PVS is used, if sDelete is enabled in the ADMX, it runs on the PVS WriteCacheDisk if the Disk is in shared Mode only every boot. Mostly it is not necessary to run sDelete after every boot, with the ADMX extensnion you can configure sDelete for PVS in addition:

- run sDelete Once
- run sDelete after boot count: 0 - 99 [0 = every boot]
- 

Write a sDelete txt-file to the WriteCacheDisk with the boot timestamp and the counter
if sDelete is run, the sDelete txt-file will be cleared

sdelete can alos be run on:
MCS (c:drive)
AppLayering - outside ELM

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#12
