### ISSUE TITLE
ADMX extension: Configure WEM Cache to persistent drive

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#17]
I have a feature request - can we make the move of the WEM cache optional?? At the moment i believe BIS-F moves it to the PVS Cache Drive, I don't always want that Happening

seeing more and more problems with the cache being moved to non standard location - seems to be far more reliable to run the refreshcache startup script and leave the cache in the default location. Its tiny, has basically zero impact on the environment, and you avoid weird stuff going on. Don't get me wrong, there is obviously come current guidance that says do it - but there really isnt a clear explanation as to why - and if you use MCS, there is no move of the Cache.. I think it would be nice to have it optional so you aren't forced to move it if you don't want to - its better to have the latest version of the cache baked into the Image for computer based settings - and then just let the user refresh happen on logon

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#11
