### ISSUE TITLE
Exception when calling "SetAccessRule" with 1 argument (s): "Some or all identity references could not be translated

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#172]
BISF,psm1 -> Set-BISFACLrights

```Set NTFS rights on D:\Spool
Exception when calling "SetAccessRule" with 1 argument (s): "Some or all identity references could not be translated."
In C:\Program Files (x86)\Base Image Script Framework (BIS-F)\framework\SubCall\Global\BISF.psm1:3714 Zeichen:2
+     $acl.SetAccessRule($rule)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException
Exception when calling "SetAccessRule" with 1 argument (s): "Some or all identity references could not be translated."
In C:\Program Files (x86)\Base Image Script Framework (BIS-F)\framework\SubCall\Global\BISF.psm1:3714 Zeichen:2
+     $acl.SetAccessRule($rule)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException
```

**Comment by matthias-schlimm** [comment]
using SID instead of the name ?

**Comment by matthias-schlimm** [comment]
better errorhandling 

```
try {
		$acl.SetAccessRule($rule)
	}
	catch {
		Write-BISFlog -Msg "Error during set NTFS rights. The error is: $_" -Type W -SubMsg
	}
```

**Comment by matthias-schlimm** [comment]
issue happens for d:\Spool only, for D:\Eventlogs works without issue

**Comment by matthias-schlimm** [comment]
With above arrorhandling it's better now

**Comment by matthias-schlimm** [comment]
On a system the NTFS right are set correctly
![image](https://user-images.githubusercontent.com/34108484/71779982-d14c0a00-2fbc-11ea-80da-fcd311347aef.png)

**Comment by matthias-schlimm** [comment]
the Local Service is the issue, using SID now

**old:**
`$perm = "local service", "FullControl", "ContainerInherit, ObjectInherit", "None", "Allow"`

**new:**
`$perm = "S-1-5-19", "FullControl", "ContainerInherit, ObjectInherit", "None", "Allow"`

**Comment by andre-sicking** [comment]
Just replacing the SID does not work in my tests. But you could resolve the SID to the localized name on the running system.

`$localServiceSID = New-Object System.Security.Principal.SecurityIdentifier("S-1-5-19")
$localServiceName = ($localServiceSID.Translate( [System.Security.Principal.NTAccount])).Value`

This resolves to "NT-AUTORITÄT\Lokaler Dienst" on a german system and works when used with the rest of the code.

**Comment by EUCweb** [comment]
I‘m also play around with the SID, but it didn’t work. I must translate the SiD into the right language. 

Am 15.01.2020 um 16:00 schrieb Andre Sicking <notifications@github.com>:

**Comment by EUCweb** [comment]
Can you send me a pull request ? 


Am 15.01.2020 um 16:00 schrieb Andre Sicking <notifications@github.com>:

**Comment by andre-sicking** [comment]
done!
