### ISSUE TITLE
Remove DHCP Information if 3P Optimizer is configured

### ISSUE THREAD

**Issue by citrixguyblog** [EUCweb/BIS-F#173]
**Describe the bug
VDAs rolled out with Citrix Machine Creation Services are keeping the IP address of the golden image. “ipconfig /release“ is fixing the issue.
BISF is already including the needed Powershell functions for clearing DHCP client information. With the current release this is only being executed when Citrix Optimizer is not being used.
Suggestion: Remove the condition for Citrix Optimizer & vmOSOT

**Comment by matthias-schlimm** [comment]
handeld in 97_PrepBISF_PRE_BaseImage.ps1 line 483 - 619

**Comment by matthias-schlimm** [comment]
fixed in developer branch https://github.com/EUCweb/BIS-F/tree/develop

**Comment by citrixguyblog** [comment]
That was fast 👍🏽

**Comment by matthias-schlimm** [comment]
as I say ASAP

**Comment by matthias-schlimm** [comment]
please grab a complete copy of the dev branch and run a test again
