### ISSUE TITLE
$Global:ImageSW request is set one Time only

### ISSUE THREAD

**Issue by Siebrandf** [EUCweb/BIS-F#176]
**Describe the bug**
We use the personalization phase to configure MCSIO based on GPO settings to D:
Considering HF 170 being implemented when using Citrix App Layering, MCSIO is not configured correctly because of an incorrect state for the global variable MCSIO. This happens because: '$Global:returnTestAppLayeringSoftware = Test-BISFAppLayeringSoftware' is run before '	$Global:returnTestXDSoftware = Test-BISFXDSoftware' the global variable $ImageSW is already set to "$true" and therefore Global:MSCIO is never set to $true.

**Expected behavior**
the variable MSCIO should be set to $true when VDA version is -ge "7.21"

**Additional context**
Fix can be applied probably by adding '$ImageSW = $false' under the service check for the functions; Test-XDSoftware but I'm not fully aware of the exact behavior of the variable as it is used on other occasion as well like Nutanix and Parrallels

**Comment by matthias-schlimm** [comment]
update all functions for better handling 

- Test-BISFAppLayeringSoftware 
- Test-BISFXDSoftware 
- Test-BISFPVSSoftware 
- Test-BISFVMwareHorizonViewSoftware 
- Test-BISFNutanixFrameSoftware 
- Test-BISFParallelsRASSoftware 
- Test-BISFWVDSoftware

**Comment by matthias-schlimm** [comment]
fixed in developer branch
