### ISSUE TITLE
XA/ XD 7.x Cache folder will be created

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#18]
_From @matthias-schimm on March 12, 2018 20:20_

IF XA/XD 7.x is installed, the Cache folder will be created in PVSWriteCacheDisk\Citrix\Cache or C:\Windows\Logs\

_Copied from original issue: EUCweb/BIS-F#10_

**Comment by matthias-schlimm** [comment]
fixed in https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Personalization/02_PersBISF_CTX.ps1
