### ISSUE TITLE
ADMX Extension: Configure AdminAutoLogon

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#18]
During automated Installation customer uses often AutoAdminLogon, during sealing with BIS-F you can reset this registry value if configured in the ADMX
 
 
AutoAdminLogon 
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon 
Data type
 Range
 Default value
 
REG_SZ 
 0 | 1 
 0 
 

Determines whether the automatic logon feature is enabled. Automatic logon uses the domain, user name, and password stored in the registry to log users on to the computer when the system starts. The Log On to Windows dialog box is not displayed.
Value
 Meaning
 
0
 Disables automatic logon.
 
1
 Enables automatic logon.

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#10
