### ISSUE TITLE
Async WriteCacheType not detected for shared Images

### ISSUE THREAD

**Issue by korbinianthiel** [EUCweb/BIS-F#188]
If the vDisk is configured in Read Only Mode (PVS in RAM with overflow in harddisk), the WriteCacheDisk script causes a reboot loop.

The desired Logfile folder will not be created, caused by the if-statement:
`if ((Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\bnistack\PVSAgent).WriteCacheType -eq 4 -or (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\bnistack\PVSAgent).WriteCacheType -eq 9) {
`

The value of WriteCacheType is 12 in this PVS mode.

**Comment by korbinianthiel** [comment]
Adding the value did not solve the problem.
The folder BISFLogs is no created on the WriteCacheDisk, this is causing the reboot loop.

**Comment by matthias-schlimm** [comment]
Which BIS-F version ist that, 7.1912 ?

**Comment by matthias-schlimm** [comment]
You can configure a shared log directory on a unc path in the bis-f admx, this will help for better analysis

**Comment by matthias-schlimm** [comment]
WriteCacheTypes:

- 0 (Private)
- 1 (Cache on Server)
- 3 (Cache in Device RAM)
- 4 (Cache on Device Hard Disk)
- 7 (Cache on Server, Persistent)
- 9 (Cache in Device RAM with Overflow on Hard Disk)
- 10 (Private async)
- 11(Server persistent async)
- 12 (Cache in Device RAM with Overflow on Hard Disk async)

**Comment by matthias-schlimm** [comment]
fixed in 00_PersBISF_WriteCacheDisk.ps1.. grab a copy of the developer branch and run a test again

**Comment by matthias-schlimm** [comment]
```
$WriteCacheType = (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\bnistack\PVSAgent).WriteCacheType
			if (($WriteCacheType -eq 4) -or ($WriteCacheType -eq 9) -or ($WriteCacheType -eq 12)) {   # 4:Cache on Device Hard Disk // 9:Cache in Device RAM with Overflow on Hard Disk // 12:Cache in Device RAM with Overflow on Hard Disk async
				
```
