### ISSUE TITLE
Microsoft LAPS support

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#19]
See https://blog.thesysadmins.co.uk/deploying-microsoft-laps-non-persistent-vdi.html

Or make use of the PowerShell Module...
![laps](https://user-images.githubusercontent.com/34108484/37308176-1db34338-2635-11e8-8604-d5d6fba8ac55.png)

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#9
