### ISSUE TITLE
Cannot run in RDP Session

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#190]
1912 (with Beta code fix), VDA 1912, Windows Server 2016 and Windows 10 1607

When trying to run BIS-F in remote session, script fails saying that you need to enable RDP via policy. RDP session support is enabled in Policy

**Comment by EUCweb** [comment]
Also tested it with bis-f 7.1912.1 from developer branch ? 


Am 16.01.2020 um 23:23 schrieb JamesKindon <notifications@github.com>:

**Comment by JamesKindon** [comment]
Yes confirmed same issue with dev branch

**Comment by matthias-schlimm** [comment]
tested it with Win10 1809 and latest developer branch and not able to reproduce

**Comment by matthias-schlimm** [comment]
This described issue was forced from the bug https://github.com/EUCweb/BIS-F/issues/195 I think
