### ISSUE TITLE
FSLOGIX and Citrix UPM

### ISSUE THREAD

**Issue by hermann1514** [EUCweb/BIS-F#198]
Hey, is it possible to check - if FSLOGIX installed and used for Profile Container, that the Citrix UPM Service is set to disabled?

**Comment by EUCweb** [comment]
Service control is out of scope, please use Citrix optimizer or GPP.

Disable of UPM service is not a best practices, so the login time in Citrix director can‘t be get if UPM service is disabled or not installed. 


Am 31.01.2020 um 13:38 schrieb hermann1514 <notifications@github.com>:

**Comment by hermann1514** [comment]
When i use Citrix Optimizer then FSLOGIX and UPM works fine together?
In Fslogix Support there is a hint to disable the UPM Service.

**Comment by EUCweb** [comment]
You can try it if you have any impact, I‘m disable UPM in the UPM configuration only, this disables the config, but the service is still running. 

Von meinem iPhone gesendet

**Comment by hermann1514** [comment]
Okay, after disable the Profilemanagement it's working.
