### ISSUE TITLE
Set NTFS rights on D:\Spool - Error on German Win10 1809

### ISSUE THREAD

**Issue by tschuegy** [EUCweb/BIS-F#199]
**Describe the bug**
I think the bug is on the line 3702 in file BISF.psm1

**To Reproduce**
I have changed from:
	$acl = Get-Acl -Path $path
	$perm = 'local service', 'FullControl', 'ContainerInherit, ObjectInherit', 'None', 'Allow'

to:
	$SIDLocalService = [System.Security.Principal.WellKnownSidType]::LocalServiceSid
	$AccountLocalService = new-object system.security.principal.securityidentifier($SIDLocalService, $null)
	$LocalServiceName = $AccountLocalService.Translate([system.security.principal.ntaccount]).value

	$acl = Get-Acl -Path $path
	$perm = $LocalServiceName, 'FullControl', 'ContainerInherit, ObjectInherit', 'None', 'Allow'

**Expected behavior**
No errer message in BISF logfile

What do you think?

Best regards,
tschuegy

**Comment by EUCweb** [comment]
Wich BIS-F Version 7.1912.0 or .1 ?

**Comment by tschuegy** [comment]
7.1912.0

**Comment by tschuegy** [comment]
sorry, 7.1912.0

**Comment by EUCweb** [comment]
7.1912.1 is available since yesterday and fix this issue 

Am 01.02.2020 um 16:37 schrieb tschuegy <notifications@github.com>:
