### ISSUE TITLE
Enable or Disable RSS via Policy

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#20]
Script to enable or disable RSS via Policy.  If enabled via Policy then configuration should take place to try and set performance-based results.  2017 "best practices" are to configure RSS as follows:

- Use "N-1" CPU's and assign to RSS.
    EG, if a system has 4 CPU's, assign 3 to RSS for a single NIC
- Use NUMA for RSS and divide CPU time along NUMA configurations.  eg, in a 2 x 6 vCPU system (12 total) with a single NIC assign 5 CPU's on NUMA node 0 to the NIC.  If two NIC's are present, then assign 5 vCPU's on NUMA 0 to NIC1 and 5 vCPU's on NUMA1 to NIC2

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#8
