### ISSUE TITLE
Installer Script - Scripts not in custom folders being kept during Update

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#20]
_From @matthias-schimm on March 12, 2018 20:17_

After copy the custom scripts to the temp folder, clean the entire BIS-F folder. If a customer place own scripts to the other folders (not custom folder), this files are being kept from the installer.

_Copied from original issue: EUCweb/BIS-F#8_

**Comment by matthias-schlimm** [comment]
with latest Installer Build to create MMYY Version, it's fixed now.
