### ISSUE TITLE
After Update GPO Policiy CHK_CTXOE_Analyze Error

### ISSUE THREAD

**Issue by hermann1514** [EUCweb/BIS-F#205]
Hi,
i upgraded my GPO Templates with the latest Version (from 6.x). After that i cannot change hte BISF Settings. Error:

Das Richtlinienpräsentationselement "CHK_CTXOE_Analyze" auf das in Präsentation "POL_CTXOE" verwiesen wird, ist nicht vorhanden.

Datei........BaseImageScriptFramework.admx Zeile 55, Spalte 128

Can anybody help?
Regards
Hermann

**Comment by hermann1514** [comment]
Found the Problem. An old german Language file was in the Policyfolder. After i delete this file the GPO Settings works fine.

**Comment by matthias-schlimm** [comment]
yupp, thanks. check out here https://eucweb.com/docs/bisf-7-1912/depcrecated-features
