### ISSUE TITLE
Reboot loop caused by missing folder

### ISSUE THREAD

**Issue by korbinianthiel** [EUCweb/BIS-F#206]
If VM is provisioned by PVS, it reboots endless.

If I create the missing folder manually, the reboot loop stops. There was no problem before release 7.1912

[log.txt](https://github.com/EUCweb/BIS-F/files/4165530/log.txt)

**Comment by matthias-schlimm** [comment]
Which folder do you mean ? 


Am 06.02.2020 um 15:17 schrieb korbinianthiel <notifications@github.com>:

**Comment by matthias-schlimm** [comment]
```
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | =========================== 00_PersBISF_WriteCacheDisk.ps1 ===========================  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Read reference server hostname from registry HKLM:\SOFTWARE\Login Consultants\BISF  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Reference server hostname [VDI-CAD-365-03] / hostname from this machine [VDI-CAD-365-20] - set SkipReboot = FALSE  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Set optical drive letter to  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Processing function Get-BISFDiskMode  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | DiskMode is ReadOnly  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | CacheDisk would be configured now for DiskMode ReadOnly  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Read uniqueID from registry HKLM:\SOFTWARE\Login Consultants\BISF  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Read uniqueID 50565357  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | WARNING......... | LogFolder D:\BISFLogs does not exist  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | PVS WriteCacheType is set to 12 - Cache in Device RAM with Overflow on Hard Disk async  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | vDisk is set to Cache on Device Hard Drive Mode  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Number of Partitions from ADMX:  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Number of Partitions on current System: 3  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | WARNING......... | WriteCache disk is formatted, but no or the wrong drive letter is assigned  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Fixing drive letter assignemnt on WriteCache disk  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Processing function Get-LogContent  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | Get content from file C:\Windows\TEMP\VDI-CAD-365-20-DiskpartFile.txt...please wait  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | -----snip-----  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | EXTERNAL LOG.... | select disk 0  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | EXTERNAL LOG.... | online disk noerr  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | EXTERNAL LOG.... | rescan  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | EXTERNAL LOG.... | rescan  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | EXTERNAL LOG.... | uniqueid disk ID=50565357  
06.02.2020 14:11:43 | VDI-CAD-365-20$ | INFORMATION... | -----snap-----  
06.02.2020 14:11:44 | VDI-CAD-365-20$ | INFORMATION... | Disk ID 50565357 is set on D:  
06.02.2020 14:11:44 | VDI-CAD-365-20$ | WARNING......... | Wait 60 seconds before system restart  
06.02.2020 14:11:44 | VDI-CAD-365-20$ | INFORMATION... | Reboot needed for config changes  
```

**Comment by matthias-schlimm** [comment]
@korbinianthiel can you send me the complete log please, thx

**Comment by korbinianthiel** [comment]
Sure [PERS_BISF_VDI-CAD-365-20_20200206-141118.log](https://github.com/EUCweb/BIS-F/files/4169248/PERS_BISF_VDI-CAD-365-20_20200206-141118.log)

**Comment by matthias-schlimm** [comment]
Can you check the path C:\Windows\Logs\BISFLogs on the VM itself, I think the start of the log is there too before moved to the configured shared logdirectory

**Comment by korbinianthiel** [comment]
I don't see any log in this directory

**Comment by matthias-schlimm** [comment]
Can you export the bis-f policy in the registry and upload it here as an text file 

Am 07.02.2020 um 13:33 schrieb korbinianthiel <notifications@github.com>:

**Comment by korbinianthiel** [comment]
[Policies_x64.txt](https://github.com/EUCweb/BIS-F/files/4171472/Policies_x64.txt)
[Policies_x86.txt](https://github.com/EUCweb/BIS-F/files/4171474/Policies_x86.txt)

**Comment by korbinianthiel** [comment]
Are more information needed?

**Comment by matthias-schlimm** [comment]
No, sorry I‘m on a conference this week and will have a look later into this. 


Am 12.02.2020 um 11:24 schrieb korbinianthiel <notifications@github.com>:

**Comment by Munken1301** [comment]
korbinianthiel:

I can let you know that the exact same issue happend for me :)
So your not alone, not that it fixes the issue.
But as you also reported, a simple "Create the BISFLogs" folder on the Cache disk, solved the issue.
//Munk

Keep up the good work Matthias!!
AWSOME program!

**Comment by korbinianthiel** [comment]
> Keep up the good work Matthias!!

Huge thanks for the framework :thumbsup:

**Comment by matthias-schlimm** [comment]
with BIS-F 7.1912 the BISFLogs folder is not created anymore on the persisitent Disk if the shared logfolder is configured.

This test runs for PVS and MCSIO too and this is definitly a Bug

`if ((Test-Path -Path "$LIC_BISF_LogPath") -eq $false) {`

as a simple workaound you can create this folder wih GPP for example.
I will check how to resolve it

**Comment by matthias-schlimm** [comment]
update code in developer branch @korbinianthiel can you grab a copy of the dev branch and run a test again please ?

**Comment by Trentent** [comment]
Nice, just ran into this.  I will test the fix too.

**Comment by Trentent** [comment]
I can confirm that I no longer have the reboot issue with this update.
