### ISSUE TITLE
Pagefile not set

### ISSUE THREAD

**Issue by Munken1301** [EUCweb/BIS-F#207]
The pagefile is not set according to what you specify in the GPO (or template file)

The following is set in my script 
Define new global variable LIC_BISF_POL_PAGEFILE=1
Processing function New-BISFGlobalVariable
Define new global variable LIC_BISF_CLI_PAGEFILE_DRIVE=E:
Processing function New-BISFGlobalVariable
Define new global variable LIC_BISF_CLI_PAGEFILE_SIZE=4

Expected the pagefile to be configured with the above paramenters however the result is the following:
The pagefile is not configured at all and is left to be "System managed" 

Misc info
Windows 2019
Using latest version of BIS-F 7.1912.1

Check logfile for log for pagefile
[LogPagefile.log](https://github.com/EUCweb/BIS-F/files/4191419/LogPagefile.log)

And log file for Full sealing process
[FullSealLog.log](https://github.com/EUCweb/BIS-F/files/4191439/FullSealLog.log)

This is what i end up with
![image](https://user-images.githubusercontent.com/52923929/74328232-d9525300-4d8d-11ea-9487-07a94668109d.png)

**Comment by matthias-schlimm** [comment]
@Trentent any idea what’s going wrong ? 

I think the reboot is not performed, can be this the issue ?

**Comment by Munken1301** [comment]
@matthias-schlimm 
I tried myself and fiddly around with the commands that is present in 
10_PrepBISF_SetPageFile.ps1

And it didn't look like the commands was doing what they were suppose to
That is also fairly visible in the log file, as it never prints any value for the properties of the NEW pagefile:
(From the log file)
12-02-2020 08:47:49 |  | INFORMATION... | Number of pagefiles: 0
12-02-2020 08:47:49 |  | INFORMATION... | Pagefile location: 
12-02-2020 08:47:49 |  | INFORMATION... | Pagefile initial size: 
12-02-2020 08:47:49 |  | INFORMATION... | Pagefile maximum size: 

And if you look in the script this is what is suppose to happen
Write-BISFLog -Msg  "Number of pagefiles: $($($CurrentPageFile.SettingID).count)" -ShowConsole -Color DarkCyan -SubMsg
Write-BISFLog -Msg  "Pagefile location: $($CurrentPageFile.name)" -ShowConsole -Color DarkCyan -SubMsg
Write-BISFLog -Msg  "Pagefile initial size: $($CurrentPageFile.initialSize)" -ShowConsole -Color DarkCyan -SubMsg
Write-BISFLog -Msg  "Pagefile maximum size: $($CurrentPageFile.MaximumSize)" -ShowConsole -Color DarkCyan -SubMsg

Meaning that the following line in the ps1 file is not returning the expected results:
$CurrentPageFile = Get-CimInstance -Query "select * from Win32_PageFileSetting" - Line 86

And since that did not return the expected results i can say for sure that the lines 50 to 58 does not do what its suppose to :)
Aka is set the pagefile to that expected values - can be tested by simply running the command manually.
I tried setting the pagefile following this guys suggestion and it worked flawlessly - as far as i can see its just slightly different to what BIS-f does
https://stackoverflow.com/questions/37813441/powershell-script-to-set-the-size-of-pagefile-sys
Obviously you would also need to add the line
$pagefile.name = <Location of the pagefile> 
So people can move it to the cache drive :)

------

And just to give some feedback on the restart pending question - That does not matter - Its correct the new settings is not applied before a restart is done - but that will happen automatically after you take an image of the disk and provisioning it (or MCS it) - So any settings to the pagefile will be in effect as soon as you boot into the newly created vDisk :)

Hope that helps

I am by no means any expert :)

Thanks for the great work!


//Munk

**Comment by Trentent** [comment]
Hi Munk, what OS are you running?  I've tested on 2008R2, 2016, and 2019.

I have identified 2 bugs in the script:

`$CurrentPageFile = Get-CimInstance -Query "select * from Win32_PageFileSetting"
		$System = Get-CimInstance -ClassName Win32_ComputerSystem`

The second line had a legacy "-enableallprivileges" used by Get-WMIObject which needs to be removed with Get-CIMInstance.  I've posted the corrected line.

The second issue was with the if statement in the Begin method:

`if ($LIC_BISF_CLI_PAGEFILE_DRIVE -eq "PVSWriteCacheDrive") {`

PVSWriteCacheDrive was set as a variable with a dollar sign instead of a string. Again, you're looking at the corrected line.

If you are not getting anything from the $CurrentPageFile line you may have a corrupt WMI repository.

You should be able to run that command individually and have it put some result. Here is what I get (2008R2):

`C:\> Get-CimInstance -Query "select * from Win32_PageFileSetting"

MaximumSize Name            Caption           
----------- ----            -------           
       4096 D:\pagefile.sys D:\ 'pagefile.sys'
`

**Comment by Trentent** [comment]
Attaching updated script with the bugfixes @matthias-schlimm 

[10_PrepBISF_SetPageFile.zip](https://github.com/EUCweb/BIS-F/files/4207802/10_PrepBISF_SetPageFile.zip)

**Comment by Trentent** [comment]
Ok, I found further issues
It turns out the conversion to the CIM instances is not sufficient.  The CIM method does not allow changing how the pagefile is managed (automatic vs manual) -- only the Get-WMIObject with -EnableAllPrivileges allows it.  In addition, CIM does not implement some of the methods available with WMIObject (.Delete)  I'm uploading another file with these additional changes.  Hopefully that nips this in the bud permanently.

**Comment by Trentent** [comment]
[10_PrepBISF_SetPageFile.zip](https://github.com/EUCweb/BIS-F/files/4208390/10_PrepBISF_SetPageFile.zip)

**Comment by Munken1301** [comment]
You guys are awsome!! :)
less then a week after bug report and you have fixed it

btw i used windows server 2019 , sorry for the late respons
Looking forward to next release :)

**Comment by matthias-schlimm** [comment]
Yupp 7.1912.2 will fix it 


Am 17.02.2020 um 09:28 schrieb Munken1301 <notifications@github.com>:

**Comment by matthias-schlimm** [comment]
@Munken1301 I have updated the developer branch with the fix now. Can you grab a copy and run a test again please ?

**Comment by jmloubser** [comment]
> Hi Munk, what OS are you running? I've tested on 2008R2, 2016, and 2019.
> 
> I have identified 2 bugs in the script:
> 
> `$CurrentPageFile = Get-CimInstance -Query "select * from Win32_PageFileSetting" $System = Get-CimInstance -ClassName Win32_ComputerSystem`
> 
> The second line had a legacy "-enableallprivileges" used by Get-WMIObject which needs to be removed with Get-CIMInstance. I've posted the corrected line.
> 
> The second issue was with the if statement in the Begin method:
> 
> `if ($LIC_BISF_CLI_PAGEFILE_DRIVE -eq "PVSWriteCacheDrive") {`
> 
> PVSWriteCacheDrive was set as a variable with a dollar sign instead of a string. Again, you're looking at the corrected line.
> 
> If you are not getting anything from the $CurrentPageFile line you may have a corrupt WMI repository.
> 
> You should be able to run that command individually and have it put some result. Here is what I get (2008R2):
> 
> `C:> Get-CimInstance -Query "select * from Win32_PageFileSetting"
> 
> MaximumSize Name Caption
> 
> ```
>    4096 D:\pagefile.sys D:\ 'pagefile.sys'
> ```
> 
> `

I believe you still have a bug in the latest version: 7.1912.6
File: 10_PrepBISF_SetPageFile.ps1
Line: 29: `if ($LIC_BISF_CLI_PAGEFILE_DRIVE -eq "$PVSWriteCacheDrive") {`
As @Trentent said: `PVSWriteCacheDrive` was set as a variable with a dollar sign instead of a string.

**Comment by jmloubser** [comment]
But, the ADMX policy (BIS-F > Microsoft > Configure Page File > Enabled: Page file drive) only allows you to select a drive letter from the dropdown.

I searched all the scripts and there is no other reference to `$PVSWriteCacheDrive`. Thus, my conclusion is that the `$PVSWriteCacheDrive` variable in this case is a bug.

`$LIC_BISF_CLI_PAGEFILE_DRIVE `should use a valid drive letter.  Should the code be changed to the following instead?
```
if ($LIC_BISF_CLI_PAGEFILE_DRIVE -eq $LIC_BISF_CLI_WCD) {
	$pagefileLocation = "$LIC_BISF_CLI_WCD\pagefile.sys"
} else {
	$pageFileLocation = "$LIC_BISF_CLI_PAGEFILE_DRIVE\pagefile.sys"
}
```
