### ISSUE TITLE
PVS WriteCacheDisk - endless Reboot if System Reserved Parttion exists

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#21]
_From @matthias-schimm on March 12, 2018 20:16_

If the System Reserved Partition exists, the formating of the WriteCacheDisk run in a endless reboot, beacuse in the script 00_PersBISF_WriteCacheDisk.ps1, line 102 -> If ((Get-WmiObject -Class Win32_volume).count -lt 3)  it checks the count of the drives <3, means SystemDrive and WriteCache only. 
 
**Workaround:**
IF you have System Reserverd Partation increase the above value from 3 to 5 manualy, we are working on a fix for this

_Copied from original issue: EUCweb/BIS-F#7_

**Comment by matthias-schlimm** [comment]
I will add a option to BIS-F admx to select the count of partitions

**Comment by matthias-schlimm** [comment]
included in BB_develop

![BISF-PVSconfig](https://user-images.githubusercontent.com/34108484/63647634-84117f00-c724-11e9-810f-26c1bd31975e.png)
