### ISSUE TITLE
App-V PackageInstallationRoot not detected properly

### ISSUE THREAD

**Issue by infecticide** [EUCweb/BIS-F#210]
**Describe the bug**
In our Citrix PVS-based environment we set the PackageInstallationRoot for App-V via GPO to the WriteCache under a folder "F:\App-V".

As a result C:\Programdata\App-V does not exist for us.

BIS-F is still looking for C:\ProgramData\App-V for files instead of the output of Get-AppvClientConfiguration under the PackageInstallationRoot value

**To Reproduce**
- Run BIS-F with a GPO setup to redirect App-V PIR to another location
- Watch BIS-F output for the wrong file location

**Expected behavior**
- BIS-F should look under the PIR defined by GPO for files to delete

**Desktop (please complete the following information):**
 - OS: Windows Server 2016 Build 1607

**Comment by matthias-schlimm** [comment]
the path is getting from HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\AppV\Client\Streaming
PackageInstallationRoot.

```
$HKLM_Path = "HKLM:\Software\Microsoft\AppV\Client"
$Installpath = Get-ItemProperty -path "$HKLM_Path" | % { $_.InstallPath }
$ModuleFile = "AppvClient.psd1"
$ModulePath = "$Installpath\AppvClient\$ModuleFile"
$PckInstRoot = Get-ItemProperty -path "$HKLM_Path\Streaming" | % { $_.PackageInstallationRoot }
$PckInstRoot = [Environment]::ExpandEnvironmentVariables($PckInstRoot)


```

**Comment by matthias-schlimm** [comment]
@infecticide can you send me the registry path and item that is configured with the GPO you are using ?

a export from HKLM:\Software\Microsoft\AppV\Client should be possible as well

**Comment by infecticide** [comment]
The GPO item is here:    Computer Configuration --> Policies --> Admin Templates --> System --> App-V --> Streaming --> Package Installation Root

Ours is enabled with a value of "F:\App-V"

Registry path is here:  HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\AppV\Client\Streaming\PackageInstallationRoot

In Powershell if you run "Get-AppvClientConfiguration" you can see if the values are set via GPO and what they are.

**Comment by matthias-schlimm** [comment]
What is the value HKLM:\Software\Microsoft\AppV\Client\Streaming\PackageInstallationRoot ?

**Comment by infecticide** [comment]
%programdata%\App-V

**Comment by matthias-schlimm** [comment]
**old:**
`
$PckInstRoot = Get-ItemProperty -path "$HKLM_Path\Streaming" | % { $_.PackageInstallationRoot }
`
**new:**
`
$PckInstRoot = (get-appvclientconfiguration -name PackageInstallationRoot).value`

**Comment by matthias-schlimm** [comment]
@infecticide update developer branch, you can grab the single script only or the complete branch for testing

**Complete branch:**
https://github.com/EUCweb/BIS-F/tree/develop

**Single AppV Script**
https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_AppVClient.ps1

**Comment by infecticide** [comment]
Looks good.   This variable is being set with the correct path now.
