### ISSUE TITLE
McAfee MOVE Self Protection blocks the modification of the registry

### ISSUE THREAD

**Issue by Deyda** [EUCweb/BIS-F#214]
**Describe the bug**
McAfee MOVE Self Protection blocks the modification of the registry

Set-ItemProperty: Es wurde versucht, einen nicht autorisierten Vorgang auszuführen...

**To Reproduce**
Try Bis-F with actual McAfee MOVE

**Expected behavior**
Optimization of McAfee MOVE

**Screenshots**
![AV BIS-F Error](https://user-images.githubusercontent.com/59874195/74936802-18fee780-53eb-11ea-91a9-2a1f09712ec3.PNG)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - McAfee MOVE 5.5.1.342

**Additional context**
Solution is to set the IntegrityEnabled Variable to 0 and after the Registry Hacks, again to 7
See below...
....
powershell -command "mvadm config set IntegrityEnabled=0"

		Write-BISFLog -Msg "Remove Registry $HKLMAgent10path1 - Key $HKLMAgent10key1" -ShowConsole -Color DarkCyan -SubMsg
		Remove-ItemProperty -Path $HKLMAgent10path1 -Name $HKLMAgent10key1 -ErrorAction SilentlyContinue

		Write-BISFLog -Msg "Update Registry $HKLMAgent10path2 - Key $HKLMAgent10key2_1"
		Set-ItemProperty -Path $HKLMAgent10path2 -Name $HKLMAgent10key2_1 -value "" -Force

		Write-BISFLog -Msg "Update Registry $HKLMAgent10path2 - Key $HKLMAgent10key2_2"
		Set-ItemProperty -Path $HKLMAgent10path2 -Name $HKLMAgent10key2_2 -value "" -Force

		Write-BISFLog -Msg "Update Registry $HKLMAgent10path2 - Key $HKLMAgent10key2_3"
		Set-ItemProperty -Path $HKLMAgent10path2 -Name $HKLMAgent10key2_3 -value "" -Force
        powershell -command "mvadm config set IntegrityEnabled=7"
...

[10_PrepBISF_AV-McAfee.zip](https://github.com/EUCweb/BIS-F/files/4230859/10_PrepBISF_AV-McAfee.zip)

**Comment by matthias-schlimm** [comment]
included in developer branch now
