### ISSUE TITLE
Set-LAPSExpirationTime

### ISSUE THREAD

**Issue by tschuegy** [EUCweb/BIS-F#218]
Function in BISF.psm1: Set-LAPSExpirationTime
Function call in 01_PersBISF_MS.ps1 SET-BISFLAPSExpirationTime

This two function names does not match.

**Comment by matthias-schlimm** [comment]
BISF.psd1 set the prefix BISF and Import the Module bisf.psm1. For all functions this prefix is used after the verb-BISF.. 

Easy to identify, if a function has the prefix BISf, that will come from BISF.psm1 module


Am 27.02.2020 um 13:40 schrieb tschuegy <notifications@github.com>:

**Comment by EUCweb** [comment]
Simple example Write-BISfLog is used everytime, the function itself is Write-Log 



Am 27.02.2020 um 13:40 schrieb tschuegy <notifications@github.com>:

**Comment by tschuegy** [comment]
OK, i understand.

Thanks.
