### ISSUE TITLE
GPO: Set Power Saving Scheme to High Performance

### ISSUE THREAD

**Issue by tschuegy** [EUCweb/BIS-F#219]
this setting should be configurable via group policy. In addition, the scheme should be selectable when the status is activated.

**Comment by matthias-schlimm** [comment]
Will remove it, can be done with Citrix Optimizer or VMware OSOT in the future

Am 28.02.2020 um 08:16 schrieb tschuegy <notifications@github.com>:

**Comment by tschuegy** [comment]
OK
