### ISSUE TITLE
Increases the UDP packet size to 1500 bytes for FastSend --> Jumbo Frames

### ISSUE THREAD

**Issue by tschuegy** [EUCweb/BIS-F#221]
If Jumbo Frames is activated, this value should not be set to 1500

**Comment by matthias-schlimm** [comment]
This will be fixed with that issue https://github.com/EUCweb/BIS-F/issues/185

**Comment by matthias-schlimm** [comment]
![image](https://user-images.githubusercontent.com/34108484/82746289-672ada80-9d8e-11ea-85f6-8600557c059c.png)

**Comment by matthias-schlimm** [comment]
DWORD: FastSendDatagramThreshold
Key:  HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\AFD\Parameters
Set the value to 0x10000 (if you have 64k Jumbo frames available)

Set the value to 1500 (if you are using a traditional network)

Source:  http://support.microsoft.com/kb/235257

source: https://www.drastic.tv/support-59/supporttipstechnical/320-optimizing-windows-networking

**Microsoft KB article is not valid anymore**

**Comment by matthias-schlimm** [comment]
@Trentent whats your suggestion on this ?

**Comment by matthias-schlimm** [comment]
the VMware KB article from 2018 https://kb.vmware.com/s/article/2040065 shows 1500 for FastSendDatagramThreshold. The Microsoft Article that are references are not valid anymore.

At the moment I have no other statement to adjust this setting.
