### ISSUE TITLE
Fixing encoding

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#222]
sometimes the PS1 files have wrong encoding, during packaging it necessary to get the file encoding and set it with a POSH script to UTF8 with BOM encoding, this will prevent encoding failures in the future and errors on admin side 

![image](https://user-images.githubusercontent.com/34108484/75607279-b21db480-5af5-11ea-8f84-8bd9240acb59.png)

**Comment by EUCweb** [comment]
Build Script must check the Encoding !

**Comment by EUCweb** [comment]
please check

- [x] Framework\SubCall\Personalization\01_PersBISF_TimeAndGPO.ps1 und
- [x] Framework\SubCall\Personalization\10_PersBISF_SCCM.ps1

**Comment by EUCweb** [comment]
Build Script will now use this script to check encoding of all PS1 scripts for UTF8, if not stops and send output https://www.powershellgallery.com/packages/PSTemplatizer/1.0.20/Content/Functions%5CGet-FileEncoding.ps1

![image](https://user-images.githubusercontent.com/34108095/76091417-ccf09d00-5fbd-11ea-8c79-f2cb936181f5.png)
