### ISSUE TITLE
Advanced Installer: Empty Folder in ProgramMenu

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#223]
**contact Advanced Installer support:**
I don’t need the application Shortcut Folder in the Startmenu or any other location, but a blank entry are not accepted. 

![image](https://user-images.githubusercontent.com/34108484/75613258-bf559600-5b2b-11ea-8a45-d09dcf5c9225.png)

**Comment by EUCweb** [comment]
Please make sure that the application folder shortcut from the Files and Folders view does not have the create folder on target machine option selected:

![image](https://user-images.githubusercontent.com/34108095/76067811-4a051d80-5f90-11ea-90cd-facbae24dbf5.png)

 
In the Application Shortcut Folder field you can specify the default location for the Application Shortcut Folder (SHORTCUTDIR). This path is stored in the SHORTCUTDIR property, and it is applicable only to those files and folders which are located under the "Application Shortcut Folder" directory in the "Files and Folders" page. The default value of this field points to a sub-folder of the ProgramMenuFolder.

**Comment by EUCweb** [comment]
available first with installer 7.1912.3
