### ISSUE TITLE
MSI Package

### ISSUE THREAD

**Issue by tschuegy** [EUCweb/BIS-F#225]
Hallo Matthias

Ich biete als professioneller Software Paketierer meine Dienste an um ein perfektes MSI Paket zu erstellen.
Gerne würde ich ein MSI Paket für Dich und die Community erstellen, damit die Unannehmlichkeiten mit den "kurrligen" Installer Vergangenheit ist.

Bitte melde Dich doch bei mir, dann kann ich Dir mal ein MSI erstellen und Du kannst es dann prüfen. Wenn Du es dann OK findest, dann kann ich es gerne für jede Version erstellen.

Meiner Meinung nach ist das viel besser als mit einem Installer. Es kann ja auch als Goodie hinzugefügt werden, sofern Du auf die Installer Versionen bestehst...

Was Meinst Du dazu?

Gruss
tschuegy

**Comment by matthias-schlimm** [comment]
Danke für das Angebot, mit dem neuen „Advanced Installer“ bin ich nun auch in der Lage ein natives MSI Paket zu erstellen, hatte nur noch nicht die Zeit gefunden mich damit zu beschäftigen. 

Generell ist das alles automatisiert und soll auch zukünftig so bleiben.

Wenn du Interesse hast, dich mit dem Advanced installer mal zu beschäftigen, können wir uns das ja mal gemeinsam anschauen . 



Am 07.03.2020 um 07:58 schrieb tschuegy <notifications@github.com>:

**Comment by matthias-schlimm** [comment]
Magst mal testen :-) 
[setup-BIS-F-7.1912.3.31030.zip](https://github.com/EUCweb/BIS-F/files/4712847/setup-BIS-F-7.1912.3.31030.zip)

**Comment by tschuegy** [comment]
Ja klar doch, werde ich morgen gerne mal anschauen und Dir anschliessend Feedback geben.
________________________________
Von: Matthias Schlimm <notifications@github.com>
Gesendet: Montag, 1. Juni 2020 20:27
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: tschuegy <tschuegy@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] MSI Package (#225)


Magst mal testen :-)
setup-BIS-F-7.1912.3.31030.zip<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEUCweb%2FBIS-F%2Ffiles%2F4712847%2Fsetup-BIS-F-7.1912.3.31030.zip&data=02%7C01%7C%7C90a35fde43ce46a633fb08d806597db2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637266328711390644&sdata=zjOz%2BBrbbi%2FTvQoxT2XMhjxXSNnO%2BgmGba8Nb40Yb80%3D&reserved=0>

**Comment by matthias-schlimm** [comment]
implemented now for dev branch and will be available with 7.1912.3 and above
