### ISSUE TITLE
Bluescreen after execution and reboot - 1912.2, PVS, Citrix Hypervisor, WinServer2019

### ISSUE THREAD

**Issue by Andre1Becker** [EUCweb/BIS-F#227]
Hi all,
i got a weird problem which i never get before. I've used the BIS-F many times for many installations (best thing ever by the way guys!)
Some system infos:

BIS-F Version: BIS-F-7.1912.2.11029 (Advanced installer)
Server 2019 DC (Patched as of 2020-03)
PVS 1912 - ISO Boot - NON UEFI
VDA 1912
Citrix Hypervisor 8.1

So after install BIS-F, rebooting the Master and then Executing the script, anything seems fine so far.

But when i reboot the Master after running the script, i get the following bluescreen:

![image](https://user-images.githubusercontent.com/25841903/76967905-55f5c580-6928-11ea-9712-adae685b8ee1.png)

I also noticed that the NIC will **vanish** after running bis-f

Before :
![image](https://user-images.githubusercontent.com/25841903/76968493-4d51bf00-6929-11ea-92ce-3df48d7cc60b.png)

After: 
![image](https://user-images.githubusercontent.com/25841903/76971460-82601080-692d-11ea-8fd1-18023eac0b95.png)

My GPO / Bis-f config:

![image](https://user-images.githubusercontent.com/25841903/76968761-b76a6400-6929-11ea-8ee4-a41d5682367c.png)
![image](https://user-images.githubusercontent.com/25841903/76968834-d832b980-6929-11ea-8f3c-ba73629cb5a4.png)

Also, the configured shutdown is not working. 

Log: [PREP_BISF_SRV-SHM1_20200318-151207.log](https://github.com/EUCweb/BIS-F/files/4349488/PREP_BISF_SRV-SHM1_20200318-151207.log)

Something interesting note:
![image](https://user-images.githubusercontent.com/25841903/76969730-12508b00-692b-11ea-9ff0-3d7164996922.png)

If you need any additional infos, just ask ;-)

Thanks!

**Comment by EUCweb** [comment]
Configure the GPO "Ghost Devices: Friendly named devices to exclude from removal" with value *XenServer PV;*

Make sure you don't forget the *

Regards 
Matthias 


Am 18.03.2020 um 15:31 schrieb Andre Becker <notifications@github.com>:

**Comment by Andre1Becker** [comment]
Hey Matthias - thanks for the quick reply! That did the Trick - now that i know it, its way to obvious ;-)

i leave this here for future reference:

![image](https://user-images.githubusercontent.com/25841903/77140089-b5fb8180-6a78-11ea-9fb0-97504fd49e16.png)

Thanks mate and have a good one!
