### ISSUE TITLE
With very latest release and with Citrix PVS image, Shut Down after generalization is not completing

### ISSUE THREAD

**Issue by ozzy01** [EUCweb/BIS-F#229]
**Describe the bug**
Policy setting is enabled to shut down after completion and generalization ends and closes window but doesn't shut down image. 

**To Reproduce**
Enable policy setting to shutdown when complete and then it completes and doesn't shut down. All other steps seemingly run and complete and then the script closes the window and doesn't do the shutdown. 

**Expected behavior**
At the script ending, shut down

**Screenshots**
This the very last thing that happens (it says "Removing module BIS-F" after this and closes the window)
![image](https://user-images.githubusercontent.com/24480911/77201791-20351600-6abb-11ea-8806-4fbc9e59e970.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Citrix PVS
 - 7.15 LTSR

**Additional context**
I have no idea if related to the Ivanti piece, but I don't think so. The script gets through everything normally it appears, skips my PVS stuff like I told it and then closes the window when finished. this is the first time I have tried the new version with PVS (as I had to wait until Bugs bunny release for it to not try and convert the image)  I can't see any other way to change a setting in that PVS section to avoid this, but maybe somebody can let me know if something else is needed here.

**Comment by ozzy01** [comment]
Screenshot of PVS Target Device setting 

![image](https://user-images.githubusercontent.com/24480911/77202283-03e5a900-6abc-11ea-9e92-b56ed2e1dbd8.png)

And I have disabled everything else to rule any of these items out:
![image](https://user-images.githubusercontent.com/24480911/77202344-237cd180-6abc-11ea-8edb-da0c947a835b.png)

**Comment by matthias-schlimm** [comment]
included into developer branch now
