### ISSUE TITLE
Personalization hangs at the WriteCache Disk script.

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#230]
I just updated my Admin image to 1912.2 and I am seeing the personalization script hang at the WriteCache Disk script.  Anyone seen this behavior and know what changed between 1912.1 and 1912.2 that might be the cause?

**Comment by EUCweb** [comment]
Ok, I think I have the line narrowed down.  Line 99 of the 00_PersBISF_WriteCacheDisk.ps1 script.  It is the new-item commandlet. There appears to be a required parameter missing.  When I run interactively I get a “Type:” prompt

![image](https://user-images.githubusercontent.com/34108095/78068348-89106e00-7398-11ea-9d8c-55b3d69f0ff3.png)

**Comment by EUCweb** [comment]
Line 99 of the 00_PersBISF_WriteCacheDisk.ps1

**old:**
IF (!(Test-path $CacheCheckFile)) {new-item $CacheCheckFile}

**new:**
IF (!(Test-path $CacheCheckFile)) {new-item -path $CacheCheckFile -ItemType File}

Update to Powershell Version 5 as well fixes the issue

**Comment by joeldonaldson** [comment]
IF (!(Test-path $CacheCheckFile)) {new-item -path $CacheCheckFile -ItemType "File"}

Needs to have the quotes

**Comment by matthias-schlimm** [comment]
see https://github.com/EUCweb/BIS-F/issues/232 for a general fix
