### ISSUE TITLE
TrendMicro Apex One process not killed

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#233]
We are using latest 1912 BIS-F on a Windows Server 2016 environment.
As security software TrendMicro Apex One is installed.
While using the script, it says "Process 'PccNTMon.exe' is running, killing process now" without any error.
But the process is still running

**Comment by matthias-schlimm** [comment]
I have now received additional errors when BISF tries to change the startup type of the TrendMicro services to manual. But this is because TrendMicro protects all processes and services. After deactivating the protection in the admin console the errors were gone. But it does not solve the actual killing PccNTMon.exe problem.

Besides that, is it possible to change the startup type oft the services even with protection on?

**Comment by matthias-schlimm** [comment]
maybe this is helpful for you:

 **Location of TrendMicro files is different with ApexOne:**

- TrendMicro: C:\ProgramFiles(x86)\TrendMicro\OfficeScan Client
- TM ApexOne: C:\ProgramFiles(x86)\TrendMicro\Security Agent

![image](https://user-images.githubusercontent.com/34108484/79013648-80265600-7b69-11ea-846d-d5e8ea9e006d.png)

 
**DeleteRunValue is different:**

- TrendMicro: OfficeScanNT Monitor
- TM ApexOne: Apex One NT Monitor

 ![image](https://user-images.githubusercontent.com/34108484/79013688-916f6280-7b69-11ea-9b88-2d055bd73a55.png)


But it looks like process and service names are identical.

**Comment by matthias-schlimm** [comment]
included in developer branch

**Comment by matthias-schlimm** [comment]
I tested the script today.
Unfortunately the processes are still not stopped. But I don't know if it's important that they are stopped either.
The other changes work.
After I distributed the new image, TrendMicro unfortunately doesn't start completely anymore (no icon in the taskbar).
The other TrendMicro processes start.

![TM-Prozesse](https://user-images.githubusercontent.com/34108484/83029990-9ada5e80-a033-11ea-8404-2ce72284b670.png)

**Comment by ghost** [comment]
TrendMicro Apex One uses self-preservation to restart all processes after unexpected termination.
This prevents the GUID from being deleted and edited.

TrendMicro offers the "ImgSetup" tool for machine cloning, which generates an individual GUID. This tool is the better choice in this case when using the ApexOne.

**Comment by matthias-schlimm** [comment]
Thx Maik, I will go back to the origin Script without ApexOne but will use the new Stop-Processes function. In addition I can check the apexOne service if it exists and skip bis-F preparation and personalization.

**Comment by matthias-schlimm** [comment]
@Maik268 Skipping ApexOne is implemented now in dev-branch
