### ISSUE TITLE
Encoding/CRLF inconsistency in source code files 01_PersBISF_TimeAndGPO.ps1 and 110_PersBISF_SCCM.ps1

### ISSUE THREAD

**Issue by trondr** [EUCweb/BIS-F#235]
**Describe the bug**
The following files is not displayed correctly in a text editor on Windows probably due line ending inconsistency with the rest of the code base.
01_PersBISF_TimeAndGPO.ps1
10_PersBISF_SCCM.ps1

This is what is shown in Visual Studio Code when doing a review of 01_PersBISF_TimeAndGPO.ps1:
਍    ⸀匀夀一伀倀匀䤀匀ഀഀ
        Update Time and Reapply GPO
਍ऀ⸀䐀攀猀挀爀椀瀀琀椀漀渀ഀഀ
    .EXAMPLE
਍    ⸀䤀渀瀀甀琀猀ഀഀ
    .Outputs
਍    ⸀一伀吀䔀匀ഀഀ
		Author: Benjamin Ruoff
਍      ऀ䌀漀洀瀀愀渀礀㨀 䰀漀最椀渀 䌀漀渀猀甀氀琀愀渀琀猀 䜀攀爀洀愀渀礀 䜀洀戀䠀ഀഀ
[...]

**To Reproduce**
1, Install BISF 7.1912.2.11029 on a Windows 10 machine
2. Find and open the files in folder "C:\Program Files (x86)\Base Image Script Framework (BIS-F)\Framework\SubCall\Personalization":
   01_PersBISF_TimeAndGPO.ps1
   10_PersBISF_SCCM.ps1

**Expected behavior**
Should be possible to review the source files on a Windows machine.

Workaround: Get the raw copy of the files from github using copy/paste from the web browser.

**Comment by matthias-schlimm** [comment]
It’s already fixed, check out https://github.com/EUCweb/BIS-F/issues/222

Send from my mobile device

**Comment by trondr** [comment]
You are right, thanks! Closing this issue.
