### ISSUE TITLE
Error: Get-NetAdapterRSS : No MSFT_NetAdapterRssSettingData objects found

### ISSUE THREAD

**Issue by trondr** [EUCweb/BIS-F#236]
In BISF 7.1912.2.11029, when running PrepareBaseImage.cmd:

[...]
	+ Starting VMWare TCPIP Optimizations
	Get-NetAdapterRSS : No MSFT_NetAdapterRssSettingData objects found with property 'Name' equal to 'Ethernet'.  Verify the value of the property and retry.
	At C:\Program Files (x86)\tietoEVRY\VDI-Prep-Tools\BIS-F\framework\SubCall\Preparation\52_PrepBISF_VMWareTCPIPOptimizations.ps1:322 char:23
	+             if (($netAdapter | Get-NetAdapterRSS).Enabled -eq $false) ...
	+                                ~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : ObjectNotFound: (Ethernet:String) [Get-NetAdapterRss], CimJobException
	    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_Name,Get-NetAdapterRss
	
	Set-NetAdapterRSS : No MSFT_NetAdapterRssSettingData objects found with property 'Name' equal to 'Ethernet'.  Verify the value of the property and retry.
	At C:\Program Files (x86)\tietoEVRY\VDI-Prep-Tools\BIS-F\framework\SubCall\Preparation\52_PrepBISF_VMWareTCPIPOptimizations.ps1:405 char:20
	+ ... etAdapter | Set-NetAdapterRSS -Enabled $true -BaseProcessorNumber $ba ...
	+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : ObjectNotFound: (Ethernet:String) [Set-NetAdapterRss], CimJobException
	    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_Name,Set-NetAdapterRss
[...]
	
When looking at the adapter list the script seems to be tripping on the Cisco AnyConnect Mobility adapter:

	PS C:\Users\Administrator> Get-NetAdapter
	Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
	----                      --------------------                    ------- ------       ----------             ---------
	Ethernet                  Cisco AnyConnect Secure Mobility Cli...       5 Not Present  00-05-9A-3C-7A-00          0 bps
	Ethernet0                 vmxnet3 Ethernet Adapter                      4 Up           00-50-56-AA-8C-C0        10 Gbps
	
	
Suggested solution: 
-------------------
Change line 295 in 52_PrepBISF_VMWareTCPIPOptimizations.ps1 from:
	$NetAdapters = Get-NetAdapter | sort -Property InterfaceDescription
To
    $NetAdapters = Get-NetAdapter |Where-Object {$_.Status -eq "Up"} | sort -Property InterfaceDescription

**Comment by matthias-schlimm** [comment]
included into developer branch
