### ISSUE TITLE
10_PrepBISF_AV-CylanceProtect.ps1 and VDI Fingerprinting

### ISSUE THREAD

**Issue by scriptkiddy666** [EUCweb/BIS-F#238]
Hi,
please add an additional check if Cylance was installed with VDI or AD parameter.
Because in a VMware environments it's not always necessary to cleanup Cylance.
(And it's also not working if the self protection of Cylance isn't set to 'Local Administrator'.)

https://support.cylance.com/s/article/VDI-Fingerprinting-for-Non-Persistent-Virtual-Machines

This feature isn't working in Azure at the moment and I think there are no plans supporting it in the near future.
A support ticket was closed with the statement 'Open a new idea.' 
And guess what, that's what I did: https://support.cylance.com/s/idea/0872S000000HH6dQAG/detail

Just as an additional info, the compatibility mode of Cylance can also be set before the installation, but that has nothing to do with BIS-F itself of course.
I'm using the PSAppDeployToolkit and within the 'Pre-Installation tasks area' I have the following commands:
$null = New-Item -Path 'HKLM:\Software\' -Name 'Cylance'
$null = New-Item -Path 'HKLM:\Software\Cylance\' -Name 'Desktop'
$null = New-ItemProperty -Path 'HKLM:\Software\Cylance\Desktop' -Name 'CompatibilityMode' -PropertyType 'BINARY' -Value '01'

Thanks
Markus

**Comment by matthias-schlimm** [comment]
thanks, this need further investigation

**Comment by matthias-schlimm** [comment]
@scriptkiddy666 both links you posted are not valid, can't open without registration. can you put the content of this 2 links in github here ?

**Comment by scriptkiddy666** [comment]
@matthias-schlimm I just downloaded the content of the two links and a few additional pages.

[VDI Fingerprinting for Non-Persistent Virtual Machines.pdf](https://github.com/EUCweb/BIS-F/files/4678339/VDI.Fingerprinting.for.Non-Persistent.Virtual.Machines.pdf)
[Idea_ Best Practices for Cylance in Citrix on Azure.pdf](https://github.com/EUCweb/BIS-F/files/4678340/Idea_.Best.Practices.for.Cylance.in.Citrix.on.Azure.pdf)
[CylancePROTECT Installation Parameters.pdf](https://github.com/EUCweb/BIS-F/files/4678341/CylancePROTECT.Installation.Parameters.pdf)
[CylancePROTECT Admin Guide 2.1 rev30.pdf](https://github.com/EUCweb/BIS-F/files/4678342/CylancePROTECT.Admin.Guide.2.1.rev30.pdf)

And additionally (but not tested by me) here is a way to change the self-protection level on local administrator without using the Cylance Console.

[Modifying the Self Protection on CylancePROTECT.pdf](https://github.com/EUCweb/BIS-F/files/4678352/Modifying.the.Self.Protection.on.CylancePROTECT.pdf)

**Comment by matthias-schlimm** [comment]
@scriptkiddy666 the VDI or AD parameter can be set only during installation. Any other ideas to do this with BIS-F ?

**Comment by scriptkiddy666** [comment]
@matthias-schlimm unfortunately no. Maybe it works if the registry keys are changed afterwards, but this is something that needs to be tested first...
I think the most important thing is to detect if Cylance was installed using one of the two parameters, and then not to make it anonymous.

**Comment by matthias-schlimm** [comment]
I don't find anything in the PDF documents above, where I can find informations about the 2 parameters on the system, like registry or file system. any idea ?

**Comment by scriptkiddy666** [comment]
Oh sorry, my bad :-(
There are two DWORDS or so with AD and VDI in the registry.
I'll ask a colleague of mine to send me a screenshot of it, because I'm currently in parental leave.

**Comment by scriptkiddy666** [comment]
Please have a look at the following screenshot (HKEY_LOCAL_MACHINE):
![grafik](https://user-images.githubusercontent.com/11939952/83171782-e7e33100-a116-11ea-86a7-e37a2c560d22.png)

We installed Cylance with the VDI=1 parameter. I think that the VDIType DWORD will change it's value to 2 if the AD parameter is used. (And should be 0 if neither of the parameters are used.)
The VDI DWORD should hold the value of the VDI=X parameter.
I can have a look into that in July, if it's necessary or interesting for BIS-F.
But I think it should be enough checking the value of VDIType, if it's non zero...

**Comment by matthias-schlimm** [comment]
added to developer branch
```
If ($svc -eq $true) {
		Write-BISFLog -Msg "Product $ProductName installed" -ShowConsole -Color Cyan
		$VDIType = (Get-ItemProperty HKLM:\SOFTWARE\Cylance\Desktop).VDIType
		IF (!($VDIType -eq 0)) {
			Stop-Service
			Set-CompatibilityMode
			Remove-Data
		} Else {
			Write-BISFLog -Msg "Skipping ProductName sealing operations !" -ShowConsole -Type W -SubMsg
		}
	}

```
