### ISSUE TITLE
Invoke-FolderScripts is relying on the default order from Get-ChildItem

### ISSUE THREAD

**Issue by gregbeck** [EUCweb/BIS-F#239]
**Describe the bug**
Invoke-FolderScripts is relying on the default order from Get-ChildItem when running scripts.  Items from Get-ChildItem are not guaranteed to be in sorted order.  It would be better sort them to make sure they are in the correct order. 

Something like 
`$scripts = @(Get-ChildItem -Path $Path -Filter "*.ps1") | Sort-Object -Property Name`

Note. I just stumbled upon this while looking at the code.  I have not noticed the scripts running out of order.

**Comment by matthias-schlimm** [comment]
included into developer branch
