### ISSUE TITLE
hybrid join

### ISSUE THREAD

**Issue by TRiebesel** [EUCweb/BIS-F#246]
Hello,

is it possible to check the Azure AD hybrid join status? (dsregcmd /status) and when the Image is hybrid join to leave the hybrid join with dsregcmd /leave

thank
best regards
Tobias

**Comment by EUCweb** [comment]
This is done as described here https://github.com/EUCweb/BIS-F/issues/84 and available in BIS-F 7.1912 

Send from my mobile device
