### ISSUE TITLE
WEMCache folder will be reconfigured to c:\... on Windows 10 with UPL

### ISSUE THREAD

**Issue by thewitscher** [EUCweb/BIS-F#249]
If the WEMCache is already configured on the WriteCache disk (e.g. via registry setting), the following message appears during BIS-F run: "Redirection is disabled"
This happens on a Windows 10 VM with installed UPL feature in the VDA Installation.

**Comment by thewitscher** [comment]
[PREP_BISF_WPT_MASTER-W10EX64_20200615-144644.log](https://github.com/EUCweb/BIS-F/files/4784952/PREP_BISF_WPT_MASTER-W10EX64_20200615-144644.log)
[PERS_BISF_MASTER-W10EX64_20200615-145952.log](https://github.com/EUCweb/BIS-F/files/4784953/PERS_BISF_MASTER-W10EX64_20200615-145952.log)
[PERS_BISF_WPT_MASTER-W10EX64_20200615-145952.log.log](https://github.com/EUCweb/BIS-F/files/4784954/PERS_BISF_WPT_MASTER-W10EX64_20200615-145952.log.log)
[PREP_BISF_MASTER-W10EX64_20200615-144644.log](https://github.com/EUCweb/BIS-F/files/4784955/PREP_BISF_MASTER-W10EX64_20200615-144644.log)

**Comment by matthias-schlimm** [comment]
the Redirection for PVS/MCS must be checked if $UPL -eq $true/$False in addition

**Comment by matthias-schlimm** [comment]
Windows 10 on Azure with UPL
![image](https://user-images.githubusercontent.com/34108484/85072765-e4911180-b1b9-11ea-8d1e-32d9ae72eda9.png)

Windows 10 on Azure without AppLayering
![image](https://user-images.githubusercontent.com/34108484/85073330-e0b1bf00-b1ba-11ea-90c6-6a83be549ba1.png)


Windows 10 with AppLayering
![image](https://user-images.githubusercontent.com/34108484/85073084-76991a00-b1ba-11ea-8eae-ffed358b36a9.png)

**Comment by matthias-schlimm** [comment]
integrated into developer branch
