### ISSUE TITLE
VDA SSL Wildcard Support

### ISSUE THREAD

**Issue by paul-e-martin** [EUCweb/BIS-F#250]
Is it possible to amend the EnableSSLVDA script to also search for wildcard certs that match the domain name of the VDA?

We have a number of BYOD's that we don't want to distribute the root cert to, but wish to keep the VDA connection SSL.

I have made amendments to the script attached (understand you may want to make amendments to it). line 172 onwards.

The script will first look for a certificate with the thumbprint specified. If no certificate thumbprint is specified, it searches for a certificate that matches the hostname, if 1 isn't found, it then looks for a wildcard certificate that matches the domain.

[05_PersBISF_EnableSSLVDA.txt](https://github.com/EUCweb/BIS-F/files/4785076/05_PersBISF_EnableSSLVDA.txt)

**Comment by matthias-schlimm** [comment]
**--- Communication ---**

**Matthias:**
Thanks Paul. One quick question: you have integrated your changes in the latest script version that I provide ? 

**Reimius99** 
Yes it looks like it. The only change should be between line 173 and 180 of your version.
 
Found that it doesn’t need a foreach loop on the certs, but what I have sent over will first look for a cert that matches the hostname, if 1 isn’t found, looks for a wildcard that matches the domainname.
 
So will prioritise a hostname certificate over the wildcard.
 
Only issue I can now think of is if multiple certs are found, may need to put in a sort by expiry date, select first or something.

Just added those sort/select to ensure if only selects a single cert if there are multiple installed.
 
Again, the only changes are between line 173 and 180.

**Comment by paul-e-martin** [comment]
Attached version with the sort/select as mentioned above.

[05_PersBISF_EnableSSLVDA.txt](https://github.com/EUCweb/BIS-F/files/4785302/05_PersBISF_EnableSSLVDA.txt)

**Comment by paul-e-martin** [comment]
Realised my method of determining the domain name wouldn’t work. As $env:USERDNSDOMAIN doesn’t return the domain name when run as a local account, which your script will be executed with.
 
Have amended it to "*." + "$([System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain().Name)" as per the attached

[05_PersBISF_EnableSSLVDA.txt](https://github.com/EUCweb/BIS-F/files/4787231/05_PersBISF_EnableSSLVDA.txt)

**Comment by matthias-schlimm** [comment]
**integrated into developer branch**

check out https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Personalization/05_PersBISF_EnableSSLVDA.ps1

**Comment by paul-e-martin** [comment]
Realised an issue with case sensitivity of the subject name of the cert.
Attached is a revised copy that accounts for that.

Only lines 176 and 178 amended to  be the DnsNameList.Unicode rather than Subject

[05_PersBISF_EnableSSLVDA.txt](https://github.com/EUCweb/BIS-F/files/4819616/05_PersBISF_EnableSSLVDA.txt)
