### ISSUE TITLE
VDA SSL Wildcard Cert Case Sensitive

### ISSUE THREAD

**Issue by paul-e-martin** [EUCweb/BIS-F#253]
Issue with case sensitivity on the matching of the subject name of the certificate to the computername and domain name (wildcard)

Edited line 176 and 178 to change the property from Subject to DnsNameList.Unicode

[05_PersBISF_EnableSSLVDA.txt](https://github.com/EUCweb/BIS-F/files/4824169/05_PersBISF_EnableSSLVDA.txt)

**Comment by matthias-schlimm** [comment]
Thank you. If you familiar with GitHub, you can send me a pull request in the future. easier to handle and to compare the changes 

Send from my mobile device

**Comment by paul-e-martin** [comment]
Sorry i'm not, still new to github

**Comment by matthias-schlimm** [comment]
updated in developer branch
