### ISSUE TITLE
No full AVScan with Defender : Windows Defender is installed, but not activated

### ISSUE THREAD

**Issue by remkolansaat** [EUCweb/BIS-F#256]
After updating to bisf 1912.3 the full av scan will not run anymore , in 1912.2 and previous there was no problem. The only thing I can see in the log is this:

Nice thingabout the error is that the script is finished in 10 minutes instead of 90 minutes ;-)

=========================== 10_PrepBISF_AV-WinDefend.ps1 ===========================
20-6-2020 16:13:55 | sCitrixXenDesktop | INFORMATION... | Processing function Test-BISFService
20-6-2020 16:13:55 | sCitrixXenDesktop | INFORMATION... | Service WinDefend exists
20-6-2020 16:13:55 | sCitrixXenDesktop | INFORMATION... | Windows Defender is installed, but not activated
20-6-2020 16:13:55 | sCitrixXenDesktop | INFORMATION... | =========================== FINISH SCRIPT ===========================

**Comment by matthias-schlimm** [comment]
please check if the Service WinDefend is running

**Comment by remkolansaat** [comment]
Hi Matthias,

Thanks for the great work!

I will add a custom script “get-service windefend” and write out the output to a log. Then I can see the status of the service at running time of BISF prep

Now at the moment the service is running but that’s after the sealing process

Keep you updated!

Regards

Remko

Van: Matthias Schlimm <notifications@github.com>
Verzonden: donderdag 25 juni 2020 14:44
Aan: EUCweb/BIS-F <BIS-F@noreply.github.com>
CC: Lansaat, Remko <RLansaat@rijnstate.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [EUCweb/BIS-F] No full AVScan with Defender : Windows Defender is installed, but not activated (#256)


please check if the Service WinDefend is running

**Comment by remkolansaat** [comment]
The problem was that Windows Defender was not ready, it was nothing with Bisf. I fixed the Defender issue and full av scan is running again. My Appolagies
