### ISSUE TITLE
Azure WVD not detected

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#257]
IF running BIS-F on WVD, the platform is not detected and BIS-F shows the following error

```
6/26/2020 4:14:03 PM | admin | WARNING......... | No Image Management Software detected [Citrix PVS Target Device Driver, XenDesktop VDA or VMware View Agent]
6/26/2020 4:14:03 PM | admin | WARNING......... | The system will not be shutdown by this script. Please run Sysprep or your prefered method manualy or install one of the software above and run the script again
```

**Comment by matthias-schlimm** [comment]
### Action plan
Script: BISF.psm1
Function: Test-WVDSoftware
Line: 3850 - 3862 delete and replace with the Lines below

```

Write-BISFFunctionName2Log -FunctionName ($MyInvocation.MyCommand | ForEach-Object { $_.Name })  #must be added at the begin to each function
$OSName = (Get-WMIObject Win32_OperatingSystem).Name
$product = "Microsoft Windows 10 Enterprise for Virtual Desktops"
IF ($OSName -eq $product) { $WVD = $true } ELSE { $WVD = $false }
    IF ($WVD -eq $true) {
        Write-BISFlog -Msg "Product $product installed" -ShowConsole -Color Cyan
        $Global:ImageSW = $true
     } ELSE {
         Write-BISFlog -Msg "Product $product NOT installed"
     }
   
    return $WVD

```

**Comment by alphasteff** [comment]
6/26/2020 7:20:45 PM | admin | INFORMATION... | Processing function Test-BISFWVDSoftware
6/26/2020 7:20:45 PM | admin | INFORMATION... | Product Microsoft Windows 10 Enterprise for Virtual Desktops NOT installed

**Comment by alphasteff** [comment]
I will test the follow lines:

    Write-BISFFunctionName2Log -FunctionName ($MyInvocation.MyCommand | ForEach-Object { $_.Name })  #must be added at the begin to each function
    $OSName = (Get-WMIObject Win32_OperatingSystem).Name
    $product = "Microsoft Windows 10 Enterprise for Virtual Desktops"
    IF ($OSName -match $product) { $WVD = $true } ELSE { $WVD = $false }
    IF ($WVD -eq $true) {
        Write-BISFlog -Msg "Product $product installed" -ShowConsole -Color Cyan
        $Global:ImageSW = $true
     } ELSE {
         Write-BISFlog -Msg "Product $product NOT installed"
     }
   
$OSName has value "Microsoft Windows 10 Enterprise for Virtual Desktops|C:\windows|\Device\Harddisk0\Partition2"

**Comment by alphasteff** [comment]
OK, with this modification (-match) it works.

**Comment by matthias-schlimm** [comment]
But I think if you have windows 10 Enterprise that will not work with -match

**Comment by matthias-schlimm** [comment]
Please send me a output of  (Get-WMIObject Win32_OperatingSystem)

**Comment by alphasteff** [comment]
I have "Microsoft Windows 10 Enterprise for Virtual Desktops" and you check also the same string. The problem is "|C:\windows|\Device\Harddisk0\Partition2" at the end of the string.

**Comment by alphasteff** [comment]
(Get-WMIObject Win32_OperatingSystem):

```
SystemDirectory : C:\windows\system32
Organization    : 
BuildNumber     : 19041
RegisteredUser  : 
SerialNumber    : 00432-70000-00001-AA326
Version         : 10.0.19041
```

(Get-WMIObject Win32_OperatingSystem).Name:
`Microsoft Windows 10 Enterprise for Virtual Desktops|C:\windows|\Device\Harddisk0\Partition2`

**Comment by matthias-schlimm** [comment]
we can use $OSName, this is a global variable from BIS-F and can be get in the log as well, check line `Operating System: Microsoft Windows 10 Enterprise for Virtual Desktops` of your sending log, means we must change the code as follows:

```
Write-BISFFunctionName2Log -FunctionName ($MyInvocation.MyCommand | ForEach-Object { $_.Name })  #must be added at the begin to each function
$product = "Microsoft Windows 10 Enterprise for Virtual Desktops"
IF ($OSName -eq $product) { $WVD = $true } ELSE { $WVD = $false }
IF ($WVD -eq $true) {
    Write-BISFlog -Msg "Product $product installed" -ShowConsole -Color Cyan
    $Global:ImageSW = $true
 } ELSE {
     Write-BISFlog -Msg "Product $product NOT installed"
 }


```

**Comment by matthias-schlimm** [comment]
develop branch updated

**Comment by matthias-schlimm** [comment]
@alphasteff can we close this issue ?

**Comment by alphasteff** [comment]
I've tested the newest post above, it works like a charm.
