### ISSUE TITLE
Typo in 97_PrepBISF_PRE_BaseImage.ps1

### ISSUE THREAD

**Issue by ES-PSH** [EUCweb/BIS-F#266]
There is a typo:

Script: 97_PrepBISF_PRE_BaseImage.ps1
Line: 856

```Powershell
Write-BISFLog -Msg " Skipping Commannd $($prepCommand.Description)" -ShowConsole -Color DarkCyan -SubMsg
```

Commannd should be Command. 

There is also an extra space?

**Comment by matthias-schlimm** [comment]
fixed in developer branch
