### ISSUE TITLE
TIMEBOMB RegKey will not be deleted

### ISSUE THREAD

**Issue by thewitscher** [EUCweb/BIS-F#268]
TIMEBOMB RegKey will not be deleted.

In the attached logs, deleting is finished successfully, but the reg-key is still available.

[PREP_BISF_MASTER-W2K16_20200730-103345.log](https://github.com/EUCweb/BIS-F/files/5000226/PREP_BISF_MASTER-W2K16_20200730-103345.log)
[PERS_BISF_WPT_MASTER-W2K16_20200730-102258.log.log](https://github.com/EUCweb/BIS-F/files/5000227/PERS_BISF_WPT_MASTER-W2K16_20200730-102258.log.log)

Could it be that it is a permission issue, because the default owner is the network service account.

**Comment by matthias-schlimm** [comment]
please upload the transcript from the preparation, RDS Timebomb well deleted on the Masterimage

**Comment by thewitscher** [comment]
Here you are 👍 

[PREP_BISF_WPT_MASTER-W2K16_20200730-103345.log](https://github.com/EUCweb/BIS-F/files/5007171/PREP_BISF_WPT_MASTER-W2K16_20200730-103345.log)

**Comment by thewitscher** [comment]
![grafik](https://user-images.githubusercontent.com/66991062/89074416-a53f0e80-d37c-11ea-9c7f-5885dfcb6288.png)

**Comment by matthias-schlimm** [comment]
translating SID for Builtin\Admnistrators for MUI Systems
$localSID = New-Object System.Security.Principal.SecurityIdentifier("S-1-5-32-544")
$localame = ($localServiceSID.Translate( [System.Security.Principal.NTAccount])).Value

[51_PrepBISF_DeleteRDSGracePeriod.txt](https://github.com/EUCweb/BIS-F/files/5008953/51_PrepBISF_DeleteRDSGracePeriod.txt)

**Comment by matthias-schlimm** [comment]
$SID = "S-1-5-32-544" #Builtin\Admnistrators
$objSID = New-Object System.Security.Principal.SecurityIdentifier($SID)
$objUser = $objSID.Translate([System.Security.Principal.NTAccount])
$localame = $objUser.Value

[51_PrepBISF_DeleteRDSGracePeriod.txt](https://github.com/EUCweb/BIS-F/files/5009001/51_PrepBISF_DeleteRDSGracePeriod.txt)

**Comment by matthias-schlimm** [comment]
fixed in developer branch
