### ISSUE TITLE
Office detection needs to long

### ISSUE THREAD

**Issue by thewitscher** [EUCweb/BIS-F#269]
Office Rearm Script takes too long:

29.07.2020 11:30:32 | admuser | INFORMATION... | -----snap-----
29.07.2020 11:30:32 | admuser | INFORMATION... | =========================== FINISH SCRIPT ===========================
29.07.2020 **11:30:32** | admuser | INFORMATION... | =========================== 96_PrepBISF_Rearm.ps1 ===========================
29.07.2020 **11:40:58** | admuser | INFORMATION... | Microsoft Office Standard 2013 - 15.0.4569.1506 installed
29.07.2020 11:40:58 | admuser | INFORMATION... | Installpath C:\Program Files (x86)\Microsoft Office\Office15\

BIS-F Code:
`Get-WmiObject win32_product | where {$_.Name -like "Microsoft Office Professional Plus*" -or $_.Name -Like "Microsoft Office Standard*" -or $_.Name -like "*Click-to-Run Licensing Component*"}`

**Comment by matthias-schlimm** [comment]
it looks like this https://docs.microsoft.com/de-de/powershell/scripting/samples/working-with-software-installations?view=powershell-7

_

> The Win32_Product class is not query optimized. Queries that use wildcard filters cause WMI to use the MSI provider to enumerate all installed products then parse the full list sequentially to handle the filter. This also initiates a consistency check of packages installed, verifying and repairing the install. The validation is a slow process and may result in errors in the event logs.

_

**Comment by matthias-schlimm** [comment]
### Action Plan
replace both scripts for Office detection. Using registry instead of WMI 

[10_PersBISF_OfficeKMS.txt](https://github.com/EUCweb/BIS-F/files/5006868/10_PersBISF_OfficeKMS.txt)
[96_PrepBISF_Rearm.txt](https://github.com/EUCweb/BIS-F/files/5006869/96_PrepBISF_Rearm.txt)

**Comment by matthias-schlimm** [comment]
integrated into developer branch
