### ISSUE TITLE
BIS-F PERS 00_PersBISF_WriteCacheDisk.ps1 fails, due to timing issue with registry values

### ISSUE THREAD

**Issue by xenadmin** [EUCweb/BIS-F#271]
**Describe the bug**
The PERS step fails, during `00_PersBISF_WriteCacheDisk.ps1`, as the script starts before the GPO refresh and therefore uses wrong registry variables. When the `00_PersBISF_WriteCacheDisk.ps1` is started with wrong values, a reboot loops occurs. 
If you break the reboot loop with a `shutdown -a` and start the PERS manually a minute later, no issues happen. 

**To Reproduce**
In my case it happend with an already working catalog, that hit the reboot loop after a maintenance reboot. Many but not all machines were affected. 
There is no way I could reliably reproduce the issue. 

**Expected behavior**
The registry values should be updated and in-place before BIS-F PERS starts, so it gets the correct values and executes without issues. 

**Screenshots**
Had a live demonstration with the Dev. 

**Environment (please complete the following information):**
 - OS: ServerOS 2016
 - BIS-F Version: 7.1912.4
 - Citrix VDA: 1912.1000

**Additional context**
We fixed the function `Get-CLIcmd` https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Global/BISF.psm1#L1535
And added after Line 1558:
```
Write-BISFLog "Apply Computer GPO"
& "$env:SystemRoot\system32\gpupdate.exe" /Target:Computer /Force /Wait:0 | Out-Null
```
I created several MCS clones after the change and couldn't reproduce the issue anymore.

Please make it possible, that the `gpupdate` gets executed, before the `00_PersBISF_WriteCacheDisk.ps1` gets executed.

**Comment by matthias-schlimm** [comment]
integrated into developer branch:
**Function:** Initialize-BISFConfiguration
**Line:** 72-73

![image](https://user-images.githubusercontent.com/34108484/89332439-b1381280-d693-11ea-8b76-6abd524ffab4.png)


grab the gpupdate output into the BIS-F log as follows

![image](https://user-images.githubusercontent.com/34108484/89332320-7fbf4700-d693-11ea-8e3b-dc59634f540d.png)

**Comment by xenadmin** [comment]
Today the issue happened again. The settings aren't recognized and a reboot Loop occurs. I can once again break the loop with a `shutdown -a` and afterwards manual start of `PERSBISF_Start.ps1`. So this wasn't the solution?

EDIT:
#274 would solve many issues, as I now have users connecting and getting disconnect through the loop. If the Broker Agent wouldn't be running until the very end of PERS, no user would be able to connect and get kicked afterwards.

**Comment by xenadmin** [comment]
Today I had to Force Restart a MCS VDA at a different customer. The MCS clones there run from this catalog since about 4 weeks. With this Force Reboot, a Reboot Loop was started. 7.1912.4. This seems to be spreading. 

Please re-open this issue. 

![grafik](https://user-images.githubusercontent.com/12057348/91023991-8e947c00-e5f7-11ea-9f44-9756570d4c62.png)

**Comment by matthias-schlimm** [comment]
can we have a GTM about this ?

**Comment by matthias-schlimm** [comment]
IF NONE is set in the Policy, Diskpart and Reboot must be skipped
![image](https://user-images.githubusercontent.com/34108484/92439941-fd530700-f1ab-11ea-8b4c-151ec43ddb65.png)

**Comment by xenadmin** [comment]
Had different very long talks to @matthias-schlimm **thanks for that!** We came to the conclusion, that I might be the only one affected, and that it's not a BIS-F issue. 
So I build a workaround, to bake the missing reg key into the Master at the end of Preparation. 
I added the following line to my master image setup script:
```
Copy-Item -Path .\99_MCSIO.ps1 -Destination "C:\Program Files (x86)\Base Image Script Framework (BIS-F)\Framework\SubCall\Preparation" -Force
```
With the following content in the file:
```
New-ItemProperty -Name LIC_BISF_CLI_MCSIONumberOfPartitions -Path 'HKLM:\SOFTWARE\Policies\Login Consultants\BISF' -PropertyType DWORD -Value 5 -Force
New-ItemProperty -Name LIC_BISF_CLI_MCSIODriveLetter -Path 'HKLM:\SOFTWARE\Policies\Login Consultants\BISF' -PropertyType String -Value "D:" -Force
```
So far all tests have been positive. I think this can be closed.
