### ISSUE TITLE
"Delay Citrix Desktop Service" doesn't work

### ISSUE THREAD

**Issue by xenadmin** [EUCweb/BIS-F#274]
**Describe the bug**
Activate "Delay Citrix Desktop Service" via ADMX.
Boot up a MCS clone.
See it's already registered in Studio, while BIS-F PERS is still active.

**To Reproduce**
1. ServerOS 2016 with CVAD 1912.1000 and BIS-F 7.1912.4
1. Create a Machine Catalog
1. Boot a Clone up
1. Watch Studio and Log
1. See the Logs states:
```
05.08.2020 22:54:07 | WS2016-002-01$ | INFORMATION... | Processing function Start-BISFCDS
05.08.2020 22:54:07 | WS2016-002-01$ | INFORMATION... | The BrokerAgent is configured through ADMX.. delay operation configured
05.08.2020 22:54:07 | WS2016-002-01$ | INFORMATION... | Additional Citrix Desktop Service delay is set to 300 seconds
```
6. While Studio already says the VDA is registered. 

**Expected behavior**
Maybe I misunderstand the feature, but I thought the VDA should state "Unregistered" in Studio, until PERS VDA delay is finished. 

**Log & Screenshot**
BIS-F Log:
```
05.08.2020 22:54:07 | WS2016-002-01$ | INFORMATION... | Processing function Start-BISFCDS
05.08.2020 22:54:07 | WS2016-002-01$ | INFORMATION... | The BrokerAgent is configured through ADMX.. delay operation configured
05.08.2020 22:54:07 | WS2016-002-01$ | INFORMATION... | Additional Citrix Desktop Service delay is set to 300 seconds
```
![grafik](https://user-images.githubusercontent.com/12057348/89463716-9c30b180-d76f-11ea-8e6b-4963045526b8.png)

**Comment by EUCweb** [comment]
The Desktop Service Must be configured for the master itself, this will stop and configure the service back to manual start during preparation.

**Comment by xenadmin** [comment]
I'm sorry I don't know what you mean. I configured the following policy via GPO for both the Master and den Clones:
![grafik](https://user-images.githubusercontent.com/12057348/89507218-81405a80-d7cc-11ea-8a42-e7777ff1c5c7.png)

**Comment by matthias-schlimm** [comment]
If you seal the master, please cancel the shutdown at the end or configure it in the BIS-F ADMX to not shutting down the VM and check if the Desktop Service is stopped and disabled, please upload the complete PREP BIS-F log here

**Comment by xenadmin** [comment]
Didn't check the master, yet, but I can confirm, that every MCS clone I boot up, has the BrokerAgent Automatic and started. 
Will check the master when I have time.

**Comment by xenadmin** [comment]
Mea culpa, I think it's my fault. As you know, I split the GPO for Master and MCS clones. In the GPO for the Master, the `Delay Citrix Desktop Service` feature was disabled, and therefore the Service wasn't stopped & disabled during PREP. 
Thanks for the heads-up to the check the PREP phase again. I thought this was a pure PERS feature.
