### ISSUE TITLE
[PERS] W32TM and gpupdate /force running twice

### ISSUE THREAD

**Issue by zimbo86** [EUCweb/BIS-F#286]
I noticed that 01_PersBISF_MS.ps1 and 01_PersBISF_TimeAndGPO.ps1 are nearly identical and both scripts run 
# Resync Time with Domain and
# Sleep
# Reapply Computer GPO
Is this done intentionally or can one timesync, sleep and gpupdate be skipped?

**Comment by matthias-schlimm** [comment]
already fixed in 7.1912.5. see https://github.com/EUCweb/BIS-F/issues/267
