### ISSUE TITLE
Problems with ngen and force parameter

### ISSUE THREAD

**Issue by scriptkiddy666** [EUCweb/BIS-F#287]
Hi,
I just noticed, that I'm unable to create even small layers if BIS-F runs the ngen update with the force parameter.
The ngen runs takes a very long time to finish and for example it's impossible to create a simple application layer for Adobe Reader DC with only 10 GB of layer size.
The layer just gets full and can't be finalised, then BIS-F crashes because there is no more free space left.
I just reinstalled our whole ELM and verified it by doing these steps again for several times.
Another clean start and after removing the force parameter also mentioned here
https://github.com/EUCweb/BIS-F/issues/278
the ngen tasks are finished quite fast and it's possible to create a simple Adobe Reader DC layer with only the default size of 10 GB.

I also found the following discussion:
https://discussions.citrix.com/topic/394153-ngen-update

The Adobe Reader DC layer with ngen update force parameter had a total size of 22 GB and the layer without the force parameter has just 2,2 GB.

Maybe it's a good idea to remove the force parameter for default runs and for special cases add an additional logic letting ngen run with the force parameter.

(I'm using ELM 20.9.0.1003 with a Server 2016 OS layer and VDA 2006 in the platform layer.)

Markus

**Comment by kyriansaxum** [comment]
it looks like NGEN requires internet access for some reason to compile the .NET assemblies.
do you have internet access when running BIS-F?

**Comment by scriptkiddy666** [comment]
In general no, but in this case I had internet access via a proxy during the initial BIS-F run in the OS layer.
Maybe it's not an issue for everyone, but for me it's quite fine since I removed the force parameter, all other application layers could be created without problems now and the BIS-F run of the ngen stuff is a lot faster.
Therefore I think it is a good idea to let the user configure this with a GPO.

**Comment by matthias-schlimm** [comment]
checkout https://github.com/EUCweb/BIS-F/issues/288

**Comment by scriptkiddy666** [comment]
Yes, thats totally ok 👍

**Comment by matthias-schlimm** [comment]
Close this issue, tracking on https://github.com/EUCweb/BIS-F/issues/288 as written above
