### ISSUE TITLE
AppLayering does not detect the right Layer

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#29]
detect errors, test Test-AppLayering function must re-developed based on the following matrix
[BIS-F AppLayering RegValues.xlsx](https://github.com/EUCweb/BISF/files/1808467/BIS-F.AppLayering.RegValues.xlsx)

**Comment by matthias-schlimm** [comment]
Awaiting feedback from testers

**Comment by EUCweb** [comment]
First feedback from customer, all tests passed.
---snip---
I tested all my scenarios, updating the OS Layer, new App Layer, updated Platform Layer, sealing a PvS Layered Image (Private Image Mode boot).
 
Everything appears to work as expected.  Attached are the logs.

---snap---
