### ISSUE TITLE
Citrix AppLayering - Layer Finalize will be run in OS Layer

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#292]
@MathiasK-SVA: sag mal, kann es sein dass bisf nicht rafft, wenn du einen os layer erstellst (bevor du den in den ELM importierst) dass der kein shutdown to finalize braucht...
hintergrund: kunde erstellt neuen os layer (= brandneue vm) , installiert updates, die unidesk tools und anschließend bis-f
wenn er jetzt bis-f laufen lässt sagt bis-f am schluss

![image](https://user-images.githubusercontent.com/34108484/100867702-d6e6f400-349a-11eb-9f1a-ba43f9205338.png)

für mein dafürbefinden kann da aber nix finalized werden, weil das ist ja der OS layer (noch) outside des ELM's der wird ja erst importiert

hier mal das ganze logfile

[PREP_BISF_WIN-7NS1CJBLHLE_20201030-144639.log](https://github.com/EUCweb/BIS-F/files/5628962/PREP_BISF_WIN-7NS1CJBLHLE_20201030-144639.log)

**Comment by matthias-schlimm** [comment]
Kannst bitte mal im Script **99_PrepBISF_POST_BaseImage.ps1**  wie folgt ändern:

**Zeile 229:**
**vorher:**
`IF (!($CTXAppLayerName -eq "No-ELM")) {`

**nachher:**
`IF (!($CTXAppLayerName -eq "No-ELM") -or !($CTXAppLayerName -eq "OS-Layer")) {`

**Zeile 272:**
**vorher:**
`IF ($CTXAppLayeringSW) {`

**nachher:**
`IF (($CTXAppLayeringSW) -and !($CTXAppLayerName -eq "OS-Layer")) {`

**Comment by thewitscher** [comment]
Habs gerade mal mit einer neuen Windows 10 VM getestet. Meldung kommt immer noch.
Siehe nachfolgende Logs:

[PREP_BISF_WPT_MASTER-W10OS_20210105-142217.log](https://github.com/EUCweb/BIS-F/files/5770385/PREP_BISF_WPT_MASTER-W10OS_20210105-142217.log)
[PREP_BISF_MASTER-W10OS_20210105-142217.log](https://github.com/EUCweb/BIS-F/files/5770386/PREP_BISF_MASTER-W10OS_20210105-142217.log)

**Comment by EUCweb** [comment]
Anpassung in Script manuell nachgezogen wie oben beschrieben ? Das ist noch nicht in der dev branch drin
Am 5. Jan. 2021, 14:34 +0100 schrieb thewitscher <notifications@github.com>:

**Comment by thewitscher** [comment]
Ja hab ich, genauso wie oben beschrieben.

**Comment by matthias-schlimm** [comment]
irgendwas passt da nicht:

bitte mal manuelle Anpassung wie folgt 99_PrepBISF_POST_BaseImage.ps1 und dann nochmal laufen lassen und logs senden

**vorher Zeile 228/299**

```
function Start-AppLayeringLayerFinalze {
		IF (!($CTXAppLayerName -eq "No-ELM")) {
```

**nachher:**

```
function Start-AppLayeringLayerFinalze {
	Write-BISFLog -Msg "Layer: $CTXAppLayerName" -ShowConsole -Color DarkCyan -SubMsg
          IF (!($CTXAppLayerName -eq "No-ELM")) {
```

**Comment by thewitscher** [comment]
Hier die neuen Logs mit Deinen Codeanpassungen:

[PREP_BISF_WPT_MASTER-W10OS_20210106-083122.log](https://github.com/EUCweb/BIS-F/files/5774451/PREP_BISF_WPT_MASTER-W10OS_20210106-083122.log)
[PREP_BISF_MASTER-W10OS_20210106-083122.log](https://github.com/EUCweb/BIS-F/files/5774452/PREP_BISF_MASTER-W10OS_20210106-083122.log)

**Comment by EUCweb** [comment]
läuft im Layer: OS-Layer wie erwartet, warum greift dann die folgende Zeile nicht ?

IF (!($CTXAppLayerName -eq "No-ELM") -or !($CTXAppLayerName -eq "OS-Layer")) {

**Comment by EUCweb** [comment]
kannst Die Zeile 229 bzw. 230 mal bitte so anpassen 

IF ((!($CTXAppLayerName -eq "No-ELM")) -or (!($CTXAppLayerName -eq "OS-Layer"))) {

**Comment by thewitscher** [comment]
Hier die neuen Logs:

[PREP_BISF_WPT_MASTER-W10OS_20210106-091253.log](https://github.com/EUCweb/BIS-F/files/5774627/PREP_BISF_WPT_MASTER-W10OS_20210106-091253.log)
[PREP_BISF_MASTER-W10OS_20210106-091253.log](https://github.com/EUCweb/BIS-F/files/5774628/PREP_BISF_MASTER-W10OS_20210106-091253.log)

**Comment by thewitscher** [comment]
Diese Änderung ist bei mir noch drin (von Dir oben):

Zeile 272:
vorher:
IF ($CTXAppLayeringSW) {

nachher:
IF (($CTXAppLayeringSW) -and !($CTXAppLayerName -eq "OS-Layer")) {

**Comment by EUCweb** [comment]
in meinem letztem Kommentar habe ich aber mehrere Klammern verwendet

**Comment by thewitscher** [comment]
Ja, das war abr Zeile 229 / 230 :-).
...
kannst Die Zeile 229 bzw. 230 mal bitte so anpassen

IF ((!($CTXAppLayerName -eq "No-ELM")) -or (!($CTXAppLayerName -eq "OS-Layer"))) {

**Comment by EUCweb** [comment]
pass die Zeile mal bitte so an und schick die Logs nochmal.. danke 

IF ((!($CTXAppLayerName -eq "No-ELM")) -or (!($CTXAppLayerName -eq "OS-Layer"))) {

**Comment by thewitscher** [comment]
Die Zeile 230 hab eich so angepasst, die letzten Logs sind mit den zusätzlichen Klammern.
IF ((!($CTXAppLayerName -eq "No-ELM")) -or (!($CTXAppLayerName -eq "OS-Layer"))) {

Die Zeile 273 sieht bei mir so aus:
IF (($CTXAppLayeringSW) -and !($CTXAppLayerName -eq "OS-Layer")) {

**Comment by EUCweb** [comment]
ich glaub ich habs, pass die Zeile 230 mal son an bitte. Dieser Wert wird gesetzt wenn der Application oder Platform Layer erkannt wird: 

IF ($CTXAppLayeringPFLayer -eq $true) {

**Comment by EUCweb** [comment]
currently the following values are detected 

Processing function Test-BISFAppLayeringSoftware
06.01.2021 09:13:21 | Administrator | INFORMATION... | Processing function Test-BISFService
06.01.2021 09:13:21 | Administrator | INFORMATION... | Service UniService exists
06.01.2021 09:13:22 | Administrator | INFORMATION... | Product Citrix AppLayering (Version 20.11.0.12-2df17d2) installed
06.01.2021 09:13:22 | Administrator | INFORMATION... | OverrideRunMode: False
06.01.2021 09:13:22 | Administrator | INFORMATION... | Citrix AppLayering RunMode: 3
06.01.2021 09:13:22 | Administrator | INFORMATION... | Processing function Get-BISFDiskMode
06.01.2021 09:13:22 | Administrator | INFORMATION... | DiskMode is UnmanagedAppLayering
06.01.2021 09:13:22 | Administrator | INFORMATION... | Processing function Test-BISFServiceState
06.01.2021 09:13:22 | Administrator | INFORMATION... | The Service Citrix App Layering Guest Service is successfully in Running state
06.01.2021 09:13:22 | Administrator | INFORMATION... | ServiceStatus Citrix AppLayering: Running
06.01.2021 09:13:22 | Administrator | INFORMATION... | DomainMember: False
06.01.2021 09:13:22 | Administrator | INFORMATION... | UPL: 
06.01.2021 09:13:22 | Administrator | INFORMATION... | Citrix AppLayering - OS-Layer detected
06.01.2021 09:13:22 | Administrator | INFORMATION... | Processing function Test-BISFPVSSoftware
06.01.2021 09:13:22 | Administrator | INFORMATION... | Processing function Test-BISFService

https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Global/BISF.psm1#L2624

**Comment by EUCweb** [comment]
@MathiasK-SVA 
@thewitscher 

es gibt nur einen Workaround, vorher den Uniservice stoppen und dann BIS-F ausführen dann geht es.
Es gibt leider in diesem Zustand keine Möglichkeit den Unterschied seitens BIS-F zuerkennen, da alle Einstellungen 
seitens AppLayering gleich sind.
