### ISSUE TITLE
Change in FSLogix central rules share not applied in personlization phase if set during preparation

### ISSUE THREAD

**Issue by matthiaseckerle** [EUCweb/BIS-F#294]
Path for FSLogix central rules share not applied in personlization if already set during preparation.

GPO1: GPO setting for preparation contains \\\path\share1
GPO2: GPO setting for personlization contains \\\path\share2

Personlization phase will use \\\path\\share1 even if \\\path\\share2 is correctly applied during policy update.
Personlization phase seems to honor \\\path\\share1 from registry path "HKEY_LOCAL_MACHINE\SOFTWARE\Login Consultants\BISF" instead of "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Login Consulta

**Comment by matthias-schlimm** [comment]
I think that comes from the time before the admx, and the value must be stored on a different path in the registry. 

I will change the code and than you can run a Test

**Comment by matthias-schlimm** [comment]
change done:

- 10_PersBISF_FSlogix.ps1 / using registry policy vlaue from $LIC_BISF_CLI_RS to get the central rules share
- 10_PrepBISF_FSlogix.ps1 / function Set-RulesShare no longer required, RulesShare is set in registry policy path

copy this two files or the complete developer branch.

The reg value HKEY_LOCAL_MACHINE\SOFTWARE\Login Consultants\BISF FRXRulesShare can be deleted manually, on a fresh new image the value is not created anymore
