### ISSUE TITLE
Include extra steps for ConfigMgr Client

### ISSUE THREAD

**Issue by RobSheppard1976** [EUCweb/BIS-F#296]
**Is your feature request related to a problem? Please describe.**
As per this Slack thread, there are a few additional steps to make ConfigMgr not duplicate GUIDs:

https://worldofeuc.slack.com/archives/CK6TCV3JN/p1607018604438000

The additional steps are:

From Admin CMD prompt
1-net stop ccmexec
2- Del %WINDIR%\smscfg.ini
3-powershell -command "Remove-Item -Path HKLM:\Software\Microsoft\SystemCertificates\SMS\Certificates\* -Force"
4-wmic /namespace:\\root\ccm\invagt path inventoryActionStatus where InventoryActionID="{00000000-0000-0000-0000-000000000001}" DELETE /NOINTERACTIVE
From Admin PowerShell
1-dsregcmd /leave
2-Rename-Item -Path "C:\ProgramData\Microsoft\Crypto\Keys" -NewName "KeysOLD"
3-New-Item -Path "C:\ProgramData\Microsoft\Crypto\Keys" -ItemType Directory
4-Get-Acl -Path "C:\ProgramData\Microsoft\Crypto\KeysOLD" | Set-Acl -Path "C:\ProgramData\Microsoft\Crypto\Keys"
 
**Describe the solution you'd like**
Please add these additional steps the BIS-F process, preferably converted to PowerShell.

**Describe alternatives you've considered**
We've been running them manually as part of our own script.

**Additional context**

https://worldofeuc.slack.com/archives/CK6TCV3JN/p1607018604438000

**Comment by JonathanPitre** [comment]
The first 4 steps are already being taken care of with the preparation script
https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_SCCM.ps1

**Comment by RobSheppard1976** [comment]
Great, good to know! The Slack thread highlights that without the other steps, the unique identifier issue still occurs. These steps came from Citrix, in response to a support case we raised for this issue.

**Comment by matthias-schlimm** [comment]
you can grab a a copy of the 10_PrepBISF_SCCM.ps1 from the developer branch, the other 4 steps are included now

**Comment by RobSheppard1976** [comment]
Just getting around to testing this. I did notice that there's an 's' missing from the $CryptoKey = "Key" and $OldCrpytoKey = "KeyOLD" variables. The latter doesn't matter as much. Looking on a non-VDA, 'Keys' is the correct folder.

**Comment by RobSheppard1976** [comment]
Also, my VM is still AzureAD joined. It doesn't look like the dsregcmd /leave command ran, according to the logs.

**Comment by EUCweb** [comment]
Can you upload the updated script here as an txt file please, I‘m working on the upcoming BIS-F version an will put this Hotfix into it.  Thank you
Am 5. Jan. 2021, 20:43 +0100 schrieb KennyLogin <notifications@github.com>:

**Comment by matthias-schlimm** [comment]
And Upload the logs here if possible

**Comment by RobSheppard1976** [comment]
[10_PrepBISF_SCCM.txt](https://github.com/EUCweb/BIS-F/files/5776177/10_PrepBISF_SCCM.txt)

Here you go, here's the script with the extra 's' added. I think the reason why the dsregcmd /leave part isn't working is it seems to rely on the Get-BISFDSRegState function, which looks to be coming in 7.1912.6?

**Comment by EUCweb** [comment]
yes, you can copy the dev branch over your installation, please also update the ADMX is well. If everything is working fine, 7.129.6 will be released in January as well.

**Comment by EUCweb** [comment]
@KennyLogin I'm added your script now to the current dev branch.
