### ISSUE TITLE
MCS CacheDisk is not right formatted

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#297]
With Citrix MCS if a Driveletter E is assigned, the persistent disk is not formatted during BIS-F personalization:

Script https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Personalization/00_PersBISF_WriteCacheDisk.ps1#L234 

Line 234-236 is not required, this will be done from the afterwards diskpart script

-

**Comment by matthias-schlimm** [comment]
using $CachDiskID instead of hardcoding DiskID

**Comment by matthias-schlimm** [comment]
updated in developer branch, https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Personalization/00_PersBISF_WriteCacheDisk.ps1

**Comment by owoell** [comment]
Where should the variable $CachDiskID be defined?

**Comment by EUCweb** [comment]
Function Get-DiskID in BISF.psm1, called as Get-BISFDiskID
