### ISSUE TITLE
Not so fast reconnect in Windows Server 2019

### ISSUE THREAD

**Issue by Deyda** [EUCweb/BIS-F#299]
**Is your feature request related to a problem? Please describe.**
https://www.mycugc.org/blogs/brandon-mitchell1/2019/09/22/not-so-fast-reconnect
Nice Feature from Windows Server 2019 that doesn't work ;-)

**Describe the solution you'd like**
Create the following RegKey and the feature is turned off
HKLM:\SOFTWARE\Citrix\Reconnect
FastReconnect
REG_DWORD
0x0

**Additional context**
I edit the script 90_PrepBISF_CTX.ps1

![image](https://user-images.githubusercontent.com/59874195/102346856-d45ac300-3f9f-11eb-938a-b9d756f886b4.png)

[90_PrepBISF_CTX.txt](https://github.com/EUCweb/BIS-F/files/5702852/90_PrepBISF_CTX.txt)

**Comment by matthias-schlimm** [comment]
Hotfix submitted in Pullrequest https://github.com/EUCweb/BIS-F/pull/300

**Comment by matthias-schlimm** [comment]
integrated into developer branch
