### ISSUE TITLE
Remove all Message boxes, Input boxes

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#3]
_From @matthias-schimm on March 12, 2018 20:53_

ADMX or shared configuration required only, otherwise BIS-F will not be run.

_Copied from original issue: EUCweb/BIS-F#28_

**Comment by matthias-schlimm** [comment]
remove MSG Boxes from this scripts and set defaultvalue
10_PrepBISF_FSLogix.ps1
BISF.psm1 - Function Request-Sysprep
BISF.psm1 - Function Invoke-LogShare
10_PrepBISF_AppVClient.ps1
10_PrepBISF_AV-F-Secure.ps1
10_PrepBISF_AV-McAfee.ps1
10_PrepBISF_AV-SEP.ps1
10_PrepBISF_AV-Sophos.ps1
10_PrepBISF_AV-TM.ps1
10_PrepBISF_AV-WinDefend.ps1
10_PrepBISF_RES.ps1
10_PrepBISF_Turbo.ps1
10_PrepBISF_vmOSOT.ps1
90_PrepBISF_CTX.ps1
96_PrepBISF_Rearm.ps1
97_PrepBISF_PRE_BaseImage.ps1
98_PrepBISF_BUILD:BaseImage.ps1
99_PrepBISF_POST_BaseImage.ps1

**Comment by matthias-schlimm** [comment]
- [x] Verysilent Option must be removed from ADMX too

- [x] Review AMDX for Msg Boxes and describe Defaultvalue if the GPO is not configured
