### ISSUE TITLE
ADMX: WEM Agent 2012 Cache startup options

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#304]
With WEM Agent 2012 and above new agent cache startup options available. Possible to put this into admx 

https://docs.citrix.com/en-us/workspace-environment-management/service/whats-new.html

This release adds the following agent cache utility options:
-RefreshSettings or -S: Refreshes agent host settings.
-Reinitialize or -I: Reinitializes the agent cache when used together with the -RefreshCache option

**Comment by thewitscher** [comment]
Hi Matthias,
good idea. Maybe you can also integrate the issue described here:
https://support.citrix.com/article/CTX247927
Regards Torsten

**Comment by matthias-schlimm** [comment]
@thewitscher we will check first the new settings if it helps. delete the WEM DB on the endpoint every time is not a possible solution for BIS-F, more a workaround

**Comment by matthias-schlimm** [comment]
integrated into developer branch now, further testing required

![image](https://user-images.githubusercontent.com/34108484/102998841-4430f680-4528-11eb-9c92-0475987fd68a.png)

**Comment by thewitscher** [comment]
I just checked the new developer version, please check logs:
 
[PERS_BISF_WPT_MASTER-W10E_20201223-124354.log](https://github.com/EUCweb/BIS-F/files/5735026/PERS_BISF_WPT_MASTER-W10E_20201223-124354.log)
[PERS_BISF_MASTER-W10E_20201223-125954.log](https://github.com/EUCweb/BIS-F/files/5735027/PERS_BISF_MASTER-W10E_20201223-125954.log)
[PERS_BISF_WPT_MASTER-W10E_20201223-125954.log](https://github.com/EUCweb/BIS-F/files/5735028/PERS_BISF_WPT_MASTER-W10E_20201223-125954.log)
[PREP_BISF_MASTER-W10E_20201223-124456.log](https://github.com/EUCweb/BIS-F/files/5735029/PREP_BISF_MASTER-W10E_20201223-124456.log)

**Comment by matthias-schlimm** [comment]
**### GPO settings take affect with WEM Agent 2012 or higher:**

**WEM 2005** 
![image](https://user-images.githubusercontent.com/34108484/102996034-996a0980-4522-11eb-9d79-2163d84cfc8b.png)

**WEM 2012**
![image](https://user-images.githubusercontent.com/34108484/102996617-b3f0b280-4523-11eb-8e17-b44135f7eedf.png)

**Comment by matthias-schlimm** [comment]
@thewitscher: No WEM Agent installed in your Image ?

Processing function Test-BISFService
23.12.2020 13:00:52 | MASTER-W10E$ | INFORMATION... | Service Norskale Agent Host Service does not exist
23.12.2020 13:00:52 | MASTER-W10E$ | INFORMATION... | Product Citrix Workspace Environment Management (WEM) Legacy Agent is NOT installed
23.12.2020 13:00:52 | MASTER-W10E$ | INFORMATION... | Processing function Test-BISFService
23.12.2020 13:00:52 | MASTER-W10E$ | INFORMATION... | Service WemAgentSvc does not exist
23.12.2020 13:00:52 | MASTER-W10E$ | INFORMATION... | Product Citrix Workspace Environment Management (WEM) Agent is NOT installed

**Comment by thewitscher** [comment]
Now with WEM Agent installed :-):

[PERS_BISF_WPT_MASTER-W10E_20201223-153407.log](https://github.com/EUCweb/BIS-F/files/5735832/PERS_BISF_WPT_MASTER-W10E_20201223-153407.log)
[PREP_BISF_MASTER-W10E_20201223-154756.log](https://github.com/EUCweb/BIS-F/files/5735833/PREP_BISF_MASTER-W10E_20201223-154756.log)
[PREP_BISF_WPT_MASTER-W10E_20201223-154756.log](https://github.com/EUCweb/BIS-F/files/5735834/PREP_BISF_WPT_MASTER-W10E_20201223-154756.log)
[PERS_BISF_MASTER-W10E_20201223-153407.log](https://github.com/EUCweb/BIS-F/files/5735835/PERS_BISF_MASTER-W10E_20201223-153407.log)

**Comment by matthias-schlimm** [comment]
@thewitscher please grab a new copy of the dev branch und run it again, the Agent Arguments are not set here correctly 

**WEM Agent Version 2012.1.0.1 detected, StartupOption:  used**

**Comment by thewitscher** [comment]
Here you are:

[PREP_BISF_WPT_MASTER-W10E_20201224-081233.log](https://github.com/EUCweb/BIS-F/files/5738628/PREP_BISF_WPT_MASTER-W10E_20201224-081233.log)
[PERS_BISF_MASTER-W10E_20201224-083047.log](https://github.com/EUCweb/BIS-F/files/5738629/PERS_BISF_MASTER-W10E_20201224-083047.log)
[PERS_BISF_WPT_MASTER-W10E_20201224-083047.log](https://github.com/EUCweb/BIS-F/files/5738630/PERS_BISF_WPT_MASTER-W10E_20201224-083047.log)
[PREP_BISF_MASTER-W10E_20201224-081233.log](https://github.com/EUCweb/BIS-F/files/5738631/PREP_BISF_MASTER-W10E_20201224-081233.log)

**Comment by matthias-schlimm** [comment]
from the log above:

```
WEM Agent Startup Options set to default value: -RefreshCache
WEM Agent Version 2012.1.0.1 detected, StartupOption: -RefreshCache used
```

you don't have configure the GPO for the WEM Agent with the new cache options.

**Comment by thewitscher** [comment]
Now with RefreshSettings and RefreshCache:

[PREP_BISF_WPT_MASTER-W10E_20201224-102647.log](https://github.com/EUCweb/BIS-F/files/5739075/PREP_BISF_WPT_MASTER-W10E_20201224-102647.log)
[PERS_BISF_MASTER-W10E_20201224-103700.log](https://github.com/EUCweb/BIS-F/files/5739076/PERS_BISF_MASTER-W10E_20201224-103700.log)
[PERS_BISF_WPT_MASTER-W10E_20201224-103700.log](https://github.com/EUCweb/BIS-F/files/5739077/PERS_BISF_WPT_MASTER-W10E_20201224-103700.log)
[PREP_BISF_MASTER-W10E_20201224-102647.log](https://github.com/EUCweb/BIS-F/files/5739078/PREP_BISF_MASTER-W10E_20201224-102647.log)

**Comment by matthias-schlimm** [comment]
@thewitscher you are to quick, the personalization log is not finished and the WEM is not processed completely. please upload the complete personlization log again

**Comment by thewitscher** [comment]
now the logs should be completed:

[PERS_BISF_MASTER-W10E_20201224-120950.log](https://github.com/EUCweb/BIS-F/files/5739402/PERS_BISF_MASTER-W10E_20201224-120950.log)
[PERS_BISF_WPT_MASTER-W10E_20201224-120950.log](https://github.com/EUCweb/BIS-F/files/5739403/PERS_BISF_WPT_MASTER-W10E_20201224-120950.log)

**Comment by thewitscher** [comment]
Hi Matthias,
here are my logs from a W10 MCS Target Machine:

[PERS_BISF_WPT_VDW10MCSPZ02_20210104-133437.log](https://github.com/EUCweb/BIS-F/files/5764698/PERS_BISF_WPT_VDW10MCSPZ02_20210104-133437.log)
[PERS_BISF_VDW10MCSPZ02_20210104-133437.log](https://github.com/EUCweb/BIS-F/files/5764699/PERS_BISF_VDW10MCSPZ02_20210104-133437.log)

**Comment by matthias-schlimm** [comment]
looks not good, I must check it again. The WPT Log shows the following error on line 56 and later. the normal BIS-F log seems to be ok, strange

```
Current Path: D:\EventLogs\
PS>TerminatingError(Out-File): "Das Argument kann nicht an den Parameter "FilePath" gebunden werden, da es NULL ist."
Out-File : Das Argument kann nicht an den Parameter "FilePath" gebunden werden, da es NULL ist.
In C:\Program Files (x86)\Base Image Script Framework (BIS-F)\framework\SubCall\Global\BISF.psm1:292 Zeichen:29
+     Out-File -Append -Filepath $logfile -inputobject "$date | $env:us ...
+                                ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : 
```

**Comment by matthias-schlimm** [comment]
Now it looks better. I had an old WEM configuration :-(.

[PERS_BISF_VDW10MCSPZ02_20210104-164949.log](https://github.com/EUCweb/BIS-F/files/5765617/PERS_BISF_VDW10MCSPZ02_20210104-164949.log)

**Comment by matthias-schlimm** [comment]
@thewitscher great I will close this issue
