### ISSUE TITLE
Citrix Optimizer Faild

### ISSUE THREAD

**Issue by TRiebesel** [EUCweb/BIS-F#306]
**Describe the bug**
In Citrix VDA 2012 the Citrix Optimizer Failed to run. The Template Directory can not access. The error message is:

1/7/2021 1:40:46 PM | Administrator | INFORMATION... | Running Citrix Optimizer (CTXO)... please Wait
1/7/2021 1:40:46 PM | Administrator | INFORMATION... | Template(s) for Citrix Optimizer (CTXO) is configured by GPO: 
          
1/7/2021 1:40:46 PM | Administrator | INFORMATION... | Using Templateprefix: Citrix_Windows_Server_2019_1809
1/7/2021 1:40:46 PM | Administrator | INFORMATION... | Groups for Citrix Optimizer (CTXO) configured by GPO: 
          
1/7/2021 1:40:46 PM | Administrator | INFORMATION... | Processing Template 
          
1/7/2021 1:40:46 PM | Administrator | INFORMATION... | Create temporary CMD-File (C:\Windows\temp\runCTXOE.ps1) to run Citrix Optimizer (CTXO) from them
1/7/2021 1:40:46 PM | Administrator | ERROR............... | ERROR: Citrix Optimizer Template C:\Program Files (x86)\Citrix\Citrix Optimizer\Templates\

The folder and the template existed.

thx
Tobias

**Comment by EUCweb** [comment]
After the download of the optimizer zip file, do you unblock it before unzipped it ?
Am 8. Jan. 2021, 05:15 +0100 schrieb TRiebesel <notifications@github.com>:

**Comment by EUCweb** [comment]
.. otherwise check the files in optimizer folder, properties of each file and check if the unblock checkbox is there

**Comment by TRiebesel** [comment]
Hello

this is the Version That is installed from the vda setup.

I will check the files and unlock them.
Thanks
Tobias

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: EUCweb.com <notifications@github.com>
Gesendet: Friday, January 8, 2021 8:11:35 AM
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Tobias Riebesel <tobias@riebesel.net>; Author <author@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Citrix Optimizer Faild (#306)


After the download of the optimizer zip file, do you unblock it before unzipped it ?
Am 8. Jan. 2021, 05:15 +0100 schrieb TRiebesel <notifications@github.com>:

**Comment by EUCweb** [comment]
in the BIS-F _GPO > Global > Logs_ enable the Powershell Transcript, run BIS-F again and upload the BIS-F transaction log here that you can find in C:\Windows\Logs

**Comment by TRiebesel** [comment]
Hello,

her are the log files. I have unblock the files in the citrix optimizer folder.

Tobias
________________________________
Von: EUCweb.com <notifications@github.com>
Gesendet: Freitag, 8. Januar 2021 08:19
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Tobias Riebesel <tobias@riebesel.net>; Author <author@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Citrix Optimizer Faild (#306)


in the BIS-F GPO > Global > Logs enable the Powershell Transcript, run BIS-F again and upload the BIS-F transaction log here that you can find in C:\Windows\Logs

**Comment by EUCweb** [comment]
No log attached

**Comment by TRiebesel** [comment]
[PREP_BISF_VM-CVA-D02_20210108-083624.log](https://github.com/EUCweb/BIS-F/files/5786248/PREP_BISF_VM-CVA-D02_20210108-083624.log)
[PREP_BISF_WPT_VM-CVA-D02_20210108-083624.log](https://github.com/EUCweb/BIS-F/files/5786250/PREP_BISF_WPT_VM-CVA-D02_20210108-083624.log)
sorry i send the logs per Outlook client.

**Comment by EUCweb** [comment]
based on your log the value LIC_BISF_CLI_CTXOE_SF_CUS is not set, this defined the Optimizer path, this can be set with the BIS-F ADMX, check out https://eucweb.com/docs/bisf-7-1912/gpo-configuration/citrix/citrix-optimizer

**Comment by TRiebesel** [comment]
Hello,

I checked the GPO and the Citrix Optimizer Policy is enabled, and a custom search directory is set.

thanks
Tobias
________________________________
Von: EUCweb.com <notifications@github.com>
Gesendet: Freitag, 8. Januar 2021 12:52
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Tobias Riebesel <tobias@riebesel.net>; Author <author@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Citrix Optimizer Faild (#306)


based on your log the value LIC_BISF_CLI_CTXOE_SF_CUS is not set, this defined the Optimizer path, this can be set with the BIS-F ADMX, check out https://eucweb.com/docs/bisf-7-1912/gpo-configuration/citrix/citrix-optimizer

**Comment by EUCweb** [comment]
The TemplatePreFix you entered in the BIS-F GPO is wrong **Citrix_Windows_Server_2019_1809**

Please use **Citrix_Windows** only, check out https://eucweb.com/kba/1208191514-2

**Comment by EUCweb** [comment]
and check the other textboxes in the BIS-F Citrix Optimizer GPO if there is any empty space and remove it

**Comment by musklor** [comment]
> and check the other textboxes in the BIS-F Citrix Optimizer GPO if there is any empty space and remove it

Yes, it's right. Solved after removing empty spaces.

**Comment by TRiebesel** [comment]
Hello,

Yes there are spaces in the GPO. Now it works.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: musklor <notifications@github.com>
Gesendet: Friday, January 15, 2021 10:12:24 PM
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Tobias Riebesel <tobias@riebesel.net>; Author <author@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Citrix Optimizer Faild (#306)


and check the other textboxes in the BIS-F Citrix Optimizer GPO if there is any empty space and remove it

Yes, it's right. Solved after removing empty spaces.
