### ISSUE TITLE
Add ADMX Options for RSS/DEP

### ISSUE THREAD

**Issue by micswe** [EUCweb/BIS-F#307]
Hi EcuWeb Teams,

we have the need to Disable this setting in the Script, can you add this in GPO ?

regards

Michael

>>
	$PrepCommands += [pscustomobject]@{
		Order       = "$ordercnt";
		Enabled     = "$true";
		showmessage = "N";
		CLI         = "";
		TestPath    = "";
		Description = "Disable Receive Side Scaling (RSS)";
		Command     = "Start-Process -FilePath 'netsh.exe' -Argumentlist 'int tcp set global rss=disable' -Wait -WindowStyle Hidden"
	};

	$PrepCommands += [pscustomobject]@{
		Order       = "$ordercnt";
		Enabled     = "$true";
		showmessage = "N";
		CLI         = "";
		TestPath    = "";
		Description = "Disable Data Execution Prevention";
		Command     = "Start-Process 'bcdedit.exe' -Verb runAs -ArgumentList '/set nx AlwaysOff' | Out-Null"
	};
	$ordercnt += 1

<<

**Comment by matthias-schlimm** [comment]
Described here https://github.com/EUCweb/BIS-F/issues/185
