### ISSUE TITLE
Changing MCS WriteCache Disk letter to something different from default d: doesn´t work

### ISSUE THREAD

**Issue by thewitscher** [EUCweb/BIS-F#318]
Hi Matthias,
Changing MCS WriteCache Disk letter to something different from default d: doesn´t work on MCS Worker.
It ends in a reboot loop.
See attached log-file:
Regards,
Torsten
[PERS_BISF_VAW2K16MCSPZ01_20210518-114625.log](https://github.com/EUCweb/BIS-F/files/6500612/PERS_BISF_VAW2K16MCSPZ01_20210518-114625.log)

The W2K16 Master configuration is:
WriteCache Disk = W:
Page file is configured on W:
#Partitions = 3
Cache Disk ID = 1

**Comment by matthias-schlimm** [comment]
i need a diskpart output of the image where the reboot loop occurs

```
diskpart
list partition
```


Number of partitions from the log, this is a misconfiguration !
```
Number of Partitions from ADMX: 3
Number of Partitions on current System: 6
```


**CacheDisk is identified as Disk 2** 
18.05.2021 11:46:40 | VAW2K16MCSPZ01$ | EXTERNAL LOG.... | select disk 2
18.05.2021 11:46:40 | VAW2K16MCSPZ01$ | EXTERNAL LOG.... | online disk noerr
18.05.2021 11:46:40 | VAW2K16MCSPZ01$ | EXTERNAL LOG.... | rescan
18.05.2021 11:46:40 | VAW2K16MCSPZ01$ | EXTERNAL LOG.... | rescan
18.05.2021 11:46:40 | VAW2K16MCSPZ01$ | EXTERNAL LOG.... | create partition primary
18.05.2021 11:46:40 | VAW2K16MCSPZ01$ | EXTERNAL LOG.... | assign letter W:
18.05.2021 11:46:40 | VAW2K16MCSPZ01$ | EXTERNAL LOG.... | Format FS=NTFS LABEL=CacheDisk QUICK 

and check the real Disk-ID on the MCS Target of the MCSCacheDisk as well

**Comment by thewitscher** [comment]
This is on my Master:
![grafik](https://user-images.githubusercontent.com/66991062/118708639-40c24280-b81c-11eb-88ca-5cd880e9db38.png)
with this configured BIS-F Policy:
![grafik](https://user-images.githubusercontent.com/66991062/118708831-8121c080-b81c-11eb-8d0e-246117e00114.png)
![grafik](https://user-images.githubusercontent.com/66991062/118708923-a0205280-b81c-11eb-997d-c956d88d86a5.png)

The MCS Worker gets one disk more during MCS creation of the Citrix identity disk. Everything else is the same as on the Master from disk perspective.

**Comment by EUCweb** [comment]
Please send me the Informations from the MCS Target as well
Am 18. Mai 2021, 21:07 +0200 schrieb thewitscher ***@***.***>:

**Comment by thewitscher** [comment]
This is on the MCS Worker:
![grafik](https://user-images.githubusercontent.com/66991062/118711566-065aa480-b820-11eb-91e5-b9568f7b8f66.png)
![grafik](https://user-images.githubusercontent.com/66991062/118711691-2a1dea80-b820-11eb-94bc-b087228f7717.png)
[PERS_BISF_VAW2K16MCSPZ01_20210518-212825.log](https://github.com/EUCweb/BIS-F/files/6503828/PERS_BISF_VAW2K16MCSPZ01_20210518-212825.log)

**Comment by matthias-schlimm** [comment]
Can you change the ADMX to 6 partitions, to see if it works.

**Comment by thewitscher** [comment]
the max. number of partitions I can choose in the policy is 5:
![grafik](https://user-images.githubusercontent.com/66991062/119013179-0af59900-b997-11eb-9d4f-bb59b4e52ebd.png)

**Comment by matthias-schlimm** [comment]
please add in the BISF adml file https://github.com/EUCweb/BIS-F/blob/develop/ADMX/en-US/BaseImageScriptFramework.adml#L802 as follows

Line 802:

**before:**
```
<string id="ITM_MCSIO_Part5">5</string>
<string id="POL_MCSCfg_Help">MCSIO Disk Drive Letter:
```

**after:**
```
<string id="ITM_MCSIO_Part5">5</string>
<string id="ITM_MCSIO_Part6">6</string>
<string id="POL_MCSCfg_Help">MCSIO Disk Drive Letter:
```

**Comment by thewitscher** [comment]
with the settings partitions = 6 and diskID = 1 in the GPO it loooks as follow:
![grafik](https://user-images.githubusercontent.com/66991062/119036206-c7a82400-b9b0-11eb-94f7-8ffa9589710f.png)
[PERS_BISF_VAW2K16MCSPZ01_20210520-211919.log](https://github.com/EUCweb/BIS-F/files/6518343/PERS_BISF_VAW2K16MCSPZ01_20210520-211919.log)

**Comment by matthias-schlimm** [comment]
Why using DiskID = 1, it looks you must use DiskID 2 instead

**Comment by thewitscher** [comment]
And why I should used 6 as partition, I only have 5 partitions on the worker and 3 on the master. I already tested with partitions = 5 and disk id = 2. It also doesn´t work.

**Comment by matthias-schlimm** [comment]
Please use 6 partitions and DiskID 2 for testing, if this will work, we have a look to the summary of the partitions. First, I will check if the coding is correct.

**Comment by matthias-schlimm** [comment]
the code That BIS-F using, list CD-ROM Drive too and this will result 6 volumes

`(Get-CimInstance -ClassName Win32_volume).count`

**Comment by thewitscher** [comment]
[PERS_BISF_VAW2K16MCSPZ01_20210525-210603.log](https://github.com/EUCweb/BIS-F/files/6541796/PERS_BISF_VAW2K16MCSPZ01_20210525-210603.log)
[PERS_BISF_VAW2K16MCSPZ01_20210525-210139.log](https://github.com/EUCweb/BIS-F/files/6541797/PERS_BISF_VAW2K16MCSPZ01_20210525-210139.log)

**Comment by thewitscher** [comment]
[BISFtmp.log](https://github.com/EUCweb/BIS-F/files/6542054/BISFtmp.log)

**Comment by matthias-schlimm** [comment]
it's hardcoded in Citrix MCS deployment to use driveletter D: Sending a Feature Request to Citrix to put this in the next LTSR Release, to change to driveletter in Citrix Studio Wizard
