### ISSUE TITLE
BISF.psm1 wrong call for function Set-ACLrights 

### ISSUE THREAD

**Issue by itsnicetobeking** [EUCweb/BIS-F#320]
In line 3741 the function set-ACLrights is declared. Yet the script calls for the set-BISFACLrights Function
at line 2748, 2843 and 2928.

In the description of the function set-ACLrights is even the description of set-BISFACLrights.
So my guess is that someone just removed the "BISF" in the name of the function and forgot
to change that in the rest of the script.

To fix it either rename the function back to "set-BISFACLrights" again or change the former mentioned lines.

Cheers,

Sascha

**Comment by matthias-schlimm** [comment]
The prefix will be added with the bisf.psd1 and this is a Standard Powershell Action, check out https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-7.1
Am 27. Juni 2021, 18:10 +0200 schrieb itsnicetobeking ***@***.***>:
