### ISSUE TITLE
PREP: Azure AD leave doesn't work

### ISSUE THREAD

**Issue by xenadmin** [EUCweb/BIS-F#330]
**Describe the bug**
Although configured via GPO, the Azure AD **leave** during the PREP phase never works. 

**To Reproduce**
1. Set in GPO: Preparation Phase: Leave Azure Active Directory: Enabled
2. Create a new Master Image
3. Read the PREP log which says:
11.11.2021 10:07:09 | SetupAccount | INFORMATION... | Processing function New-BISFGlobalVariable
11.11.2021 10:07:09 | SetupAccount | INFORMATION... | Define new global variable LIC_BISF_CLI_MS_AAD_**HybribLeave**b=YES
11.11.2021 10:07:09 | SetupAccount | INFORMATION... | Processing function New-BISFGlobalVariable
11.11.2021 10:07:09 | SetupAccount | INFORMATION... | Define new global variable LIC_BISF_CLI_MS_AAD_HybridJoinb=NO
...
11.11.2021 10:10:26 | SetupAccount | INFORMATION... | Processing Order-Nbr 26: leave Azure AD Domain
11.11.2021 10:10:26 | SetupAccount | INFORMATION... | Configure leave Azure AD Domain
11.11.2021 10:10:26 | SetupAccount | INFORMATION... | Check GPO Configuration
11.11.2021 10:10:26 | SetupAccount | INFORMATION... | **GPO Valuedata: NO**
11.11.2021 10:10:26 | SetupAccount | INFORMATION... | **Skipping Command** leave Azure AD Domain
4. All MCS clones aren't AAD joined and cause trouble. 

**Expected behavior**
I expect BIS-F to AAD leave the master during PREP phase

**Screenshots**
This is what happens, if the master doesn't leave:
![grafik](https://user-images.githubusercontent.com/12057348/141749938-55dc0b14-5f40-4481-acb7-0accbb3f0263.png)
This is our GPO on the Master's OU:
![grafik](https://user-images.githubusercontent.com/12057348/141750035-fda508d1-0cbe-4693-95eb-b219e2fb5f45.png)
This are the reg values where I think is a bug:
![grafik](https://user-images.githubusercontent.com/12057348/141750124-c7877b7c-a1d1-49d7-ac6d-6efdc559efd2.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 Datacenter de-DE
 - BIS-F: 1912.6
 - Citrix VDA: 1912 CU3

**Additional context**
I think we already found part of the problem (or I misread your PS code).
1. There is a typo in the ADMX file which says Hybri**b** instead of Hybri**d**: https://github.com/EUCweb/BIS-F/blob/bd1b29b8c3a57a53676725b6cc2751ff26e99b3f/ADMX/BaseImageScriptFramework.admx#L1663
2. I read your code for the AAD leave and join, and maybe I found a logical error: The PREP_97 **never checks for a leave variable** as far as I can tell: https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/97_PrepBISF_PRE_BaseImage.ps1
3. The part where it should check for a leave, checks for a join instead: https://github.com/EUCweb/BIS-F/blob/bd1b29b8c3a57a53676725b6cc2751ff26e99b3f/Framework/SubCall/Preparation/97_PrepBISF_PRE_BaseImage.ps1#L477 && https://github.com/EUCweb/BIS-F/blob/bd1b29b8c3a57a53676725b6cc2751ff26e99b3f/Framework/SubCall/Preparation/97_PrepBISF_PRE_BaseImage.ps1#L488

**Comment by jeremyts** [comment]
Nice work Marco. I can confirm this works.

**Comment by matthias-schlimm** [comment]
Pullrequest is merged in to dev branch nox, for 7.1912.7 bugfix release

**Comment by madrianr** [comment]
Hello, I have the same issue - where to download the 7.1912.7 bugfix release MSI?

**Comment by xenadmin** [comment]
In the releases: https://github.com/EUCweb/BIS-F/releases/tag/7.1912.7
