### ISSUE TITLE
Search for vietool recursive

### ISSUE THREAD

**Issue by zimbo86** [EUCweb/BIS-F#335]
**Is your feature request related to a problem? Please describe.**
When vietool is placed in a subfolder inside ${env:ProgramFiles(x86)} it is not found via function "RunVIE"
**Describe the solution you'd like**
When vietool is placed in a subfolder inside ${env:ProgramFiles(x86)} it is not found via function "RunVIE"

**Describe alternatives you've considered**
Add -recurse  parameter in line 152, 10_PrepBIS_AV-SEP.ps1
change
`$VIEExists = Get-ChildItem -Path "$VIESearchFolder" -filter "$VIEApp" -ErrorAction SilentlyContinue | % { $_.FullName }`
to
`$VIEExists = Get-ChildItem -Path "$VIESearchFolder" -filter "$VIEApp" -recurse -ErrorAction SilentlyContinue | % { $_.FullName }`

**Additional context**
![image](https://user-images.githubusercontent.com/69269000/149155818-6b134909-f253-4518-82f9-63a6f03c5a3b.png)

**Comment by bladeoner** [comment]
@zimbo86 can you replace the 10_PrepBIS_AV-SEP.ps1 script with the attached one and see if it works?
[10_PrepBISF_AV-SEP.zip](https://github.com/EUCweb/BIS-F/files/9332876/10_PrepBISF_AV-SEP.zip)

I added the following online 84:
Old: ```$VIESearchFolders = @("C:\Windows", "C:\Windows\system32", "$env:ProgramFiles", "$(${env:Programfiles(x86)})", "$SEP_path")```
New: ```$VIESearchFolders = @("C:\Windows", "C:\Windows\system32", "$env:ProgramFiles", "$(${env:Programfiles(x86)})", "${env:Programfiles(x86)}\Symantec" , "$SEP_path")```

Thanks in advance.
