### ISSUE TITLE
Multiple FQDN Machine Certificates breaks EnableSSLVDA.ps1

### ISSUE THREAD

**Issue by badnatho** [EUCweb/BIS-F#340]
**Describe the bug**
- When: Citrix VDA SSL being armed.
- When: machine has multiple FQDN certificates issued.
- When: not all certificates have the Client/Server Authentication purpose.
- Outcome: EnableSSLVDA.ps1 picks first certificate in list. (Regardless of purpose)
- Outcome: First certificate in list may not have Server Authentication purpose.
- Outcome: Incorrect certificate thumbprint put into registry.

I am aware this is a weird edge-case. The environment I'm currently working in has this setup and is unable to change.

**To Reproduce**
1. Generate multiple machine certificates, one with Server Authentication and one without.
2. Seal template with BIS-F
3. Deploy template with MCS
4. Check deployed machines SSL configuration.

**Expected behavior**
Ideally the EnableSSLVDA.ps1 script should check for the Server Authentication purpose before selecting the certificate thumbprint.

**Screenshots**
I am unable to provide screenshots due to the target environment's security requirements.
I assume the issue should contain enough detail to avoid this, otherwise I'll make mock ups.

**Desktop (please complete the following information):**
 - OS: Windows 10 (2004 & 20H2) & Windows Server 2019 (1809)
 - CVAD: 1912 CU5
 - BIS-F: 7.1912.6 (Latest)

**Additional context**
I've already written a script to workaround this issue and correct the registry keys after MCS creates the machine and BIS-F runs.
I'm planning to write an actual patch in BIS-F and raise a PR for it.

**Comment by matthias-schlimm** [comment]
Thanks for your PR; I'm put it in the 7.1912.7 bugfix release
