### ISSUE TITLE
ADMX extension: Copy all logfiles to BIS-F Logshare

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#35]
Enter the path to the logfiles like C:\Windows\Temp in the BIS-F AMX, and BIS-F will copy all files *.log,*.txt,*.bis recurse to the BIS-F Shared logfile. This will take affect if the BIS-F Logshare is configured and enabled and during preparation only.

---snip---
I'm using PowerShell wrappers to install all my software using MDT. Is there an easy way to also copy C:\Windows\Temp to the BISF log share? This can be very helpful when you have 100% automated deployments and might need to check the Citrix VDA installation MSI log file located in C:\Windows\Temp\Citrix. Yes I can add it to my custom stuff, but wouldn't it be a nice feature?
---snap----

**Comment by matthias-schlimm** [comment]
if you trigger BIS-F from MDT or SCCM Tasksequence the BIS-F logfile will be automatically redirect to the TS logfolder

**Comment by matthias-schlimm** [comment]
This will not be included in BIS-F, we will use the own logs only
