### ISSUE TITLE
FSLogix rule files not being copied

### ISSUE THREAD

**Issue by Darth-Mittens** [EUCweb/BIS-F#358]
Im having an issue where the FSLogix rule files are not being copied to C:\Program Files\FSLogix\Apps\Rules when PersBISF_Start.ps1 is run on startup.

Windows 10 22H2 virtual desktop MCS master image 
BIS-F settings are being configured using group policy
I have two other master image VMs in the same OU that BISF is working OK on so I dont think there is an issue with the GPO settings

This registry key has been created and the path is set correctly to the FSLogix rules shared folder
KEY_LOCAL_MACHINE\SOFTWARE\Policies\Login Consultants\BISF
LIC_BISF_CLI_RS 
`\\file-share\deploy\FSLogix\AppMasking`

I've tried running gpupdate /force and restarting the VM
Ive installed BIS-F-7.1912.6.11041 and updated the Group policy templates

The LIC_BISF_Device_Personalize scheduled task runs on startup but the FSLogix rule files are not copied

When I manually run PersBISF_Start.ps1 I get this error
Image in Mode VDAPrivate, skip device personalization (configured: Private Mode)

C:\Windows\Logs\BISFLogs\PERS_BISF_computer.log shows the same error

11/19/2022 10:38:06 AM | dbadmin | ERROR............... | Image in Mode VDAPrivate, skip device personalization (configured: Private Mode) 

Can you please help? Thank you

**Comment by matthias-schlimm** [comment]
Please set the device personalisation to “never” in the BIS-F GPO, check out

https://eucweb.com/docs/bisf-7-1912/gpo-configuration/global/configure-the-device-personalization

**Comment by EUCweb** [comment]
In addition, please upload the BIS-F personalisation log here, anonymous any sensitive data in the log before please

**Comment by Darth-Mittens** [comment]
@matthias-schlimm thank you! changing that setting fixed it :)

> Please set the device personalisation to “never” in the BIS-F GPO, 
check out https://eucweb.com/docs/bisf-7-1912/gpo-configuration/global/configure-the-device-personalization
