### ISSUE TITLE
Shared Configuration - JSON Export and Import

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#36]
additional option to export the Shared Configuration to xml and json file, default is xml file

**Comment by matthias-schlimm** [comment]
**Export to File like this:**
[Reg.json.txt](https://github.com/EUCweb/BIS-F/files/3637395/Reg.json.txt)

Default Export is set to JSON

Import using JSON with Fallback to XML if exist

**Comment by matthias-schlimm** [comment]
[BISFconfig_MicrosoftWindows10Pro_64-Bit.json.txt](https://github.com/EUCweb/BIS-F/files/3638344/BISFconfig_MicrosoftWindows10Pro_64-Bit.json.txt)
[BISFSharedConfig.json.txt](https://github.com/EUCweb/BIS-F/files/3638345/BISFSharedConfig.json.txt)
