### ISSUE TITLE
[Question]: No FSLogix Apps Central Rules Share defined

### ISSUE THREAD

**Issue by Darth-Mittens** [EUCweb/BIS-F#375]
### Describe your question

Hi,
Im having an issue where FS Logix rule files are not being copied to the VDA
The folder is empty C:\Program Files\FSLogix\Apps\Rules

I get this error in the BISF logs
No FSLogix Apps Central Rules Share defined, didn't copy files!

On the master image VM, the value for the rules share is set using gpo, the registry value exists and the rules are copied to C:\Program Files\FSLogix\Apps\Rules as expected

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Login Consultants\BISF
LIC_BISF_CLI_RS
`\\fileshare\deploy\FSLogix\AppMasking`

However, after running PrepareBaseImage.cmd on the master image vm and updating the machine catalog the VDA does not have this registry key, its completely missing

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Login Consultants\

Can you please help
Thank you

**Comment by matthias-schlimm** [comment]
You must apply this setting of the BIS-F policy to your targets.

Regards
Matthias
Am 10. März 2023, 13:56 +0100 schrieb Darth-Mittens ***@***.***>:

**Comment by Darth-Mittens** [comment]
OK, so the gpo to set the fileshare needs to be applied to **both** the master image vms and the VDAs?
Not sure when this changed as we've only had it applied to the master images before...
Thanks for your help

**Comment by EUCweb** [comment]
This is never changed, but depends on how policy cache on the Master and target will be processed.
Am 10. März 2023, 16:53 +0100 schrieb Darth-Mittens ***@***.***>:

**Comment by Darth-Mittens** [comment]
OK, thanks for your help!
