### ISSUE TITLE
Pending Reboot 

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#40]
After a System reboot, sometimes BIS-F detect also a pending system reboot
![image](https://user-images.githubusercontent.com/34108095/40440690-0ce0c39c-5ebf-11e8-87af-9758d1ccdbdc.png)

**Comment by matthias-schlimm** [comment]
BIS-F using this Script https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542 to detect the pending Reboot, the error comes from this script, that is a part of the BISF.psm1

**Comment by matthias-schlimm** [comment]
we must replace this in a better way with http://ilovepowershell.com/2015/09/10/how-to-check-if-a-server-needs-a-reboot/

`#Adapted from https://gist.github.com/altrive/5329377
#Based on <http://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542>
function Test-PendingReboot
{
 if (Get-ChildItem "HKLM:\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending" -EA Ignore) { return $true }
 if (Get-Item "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired" -EA Ignore) { return $true }
 if (Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" -Name PendingFileRenameOperations -EA Ignore) { return $true }
 try { 
   $util = [wmiclass]"\\.\root\ccm\clientsdk:CCM_ClientUtilities"
   $status = $util.DetermineIfRebootPending()
   if(($status -ne $null) -and $status.RebootPending){
     return $true
   }
 }catch{}
 
 return $false
}`

**Comment by EUCweb** [comment]
replace  Get-PendingReboot function in BISF.psm1 with above script, see https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Global/BISF.psm1

**Installation instructions:**
1. Open up the global Folder of your BIS-F Installation folder
2. Rename or take a copy of the exitisting BISF.psm1 
3. copy the complete BISF.psm1 from the above path to the global Folder 
4. Test the functionality and report your experience under https://github.com/EUCweb/BIS-F/issues/40

**Comment by EUCweb** [comment]
No return of the Pending reboot state in BETA 02.105

7/9/2018 12:19:43 PM | Administrator | INFORMATION... | Processing function Get-BISFPendingReboot
7/9/2018 12:19:43 PM | Administrator | INFORMATION... | Pending system reboot is

**Comment by matthias-schlimm** [comment]
fixed in https://github.com/EUCweb/BIS-F/blob/develop/Framework/PrepBISF_Start.ps1

line 216
$CheckPndReboot = Get-BISFPendingReboot

**Comment by Puntoboy** [comment]
I've started getting this issue with a new 2016 image I am building. The log file is pretty vague. 

`29/01/2021 16:24:08 | ctx_installer | INFORMATION... | Processing function Get-BISFPendingReboot
29/01/2021 16:24:08 | ctx_installer | INFORMATION... | Session Manager - PendingFileRenameOperations: True
29/01/2021 16:24:08 | ctx_installer | ERROR............... | A pending system reboot was detected, please reboot the system and run the script again!`

I've rebooted the machine several times.

**Comment by EUCweb** [comment]
@Puntoboy you can supress the pending reboot via BIS-F GPO https://eucweb.com/docs/bisf-7-1912/gpo-configuration/global/suppress-pending-reboot. 

From your log you can see "Session Manager - PendingFileRenameOperations: ", this is the component that is responsible for the pending reboot and in my link you can check where it come from.

**Comment by Puntoboy** [comment]
Thanks. I was aware of the GPO override but I'd rather find out what is causing the pending restart even though I've repeatedly done that. I'll check the link thank you :)

**Comment by EUCweb** [comment]
This is new with BIS-F 7.1912.6, we are logging the component, for better troubleshooting

**Comment by Puntoboy** [comment]
> This is new with BIS-F 7.1912.6, we are logging the component, for better troubleshooting

Thanks. I've taken a look at the registry key, seems some orphaned file rename so I removed it.
