### ISSUE TITLE
sihclient.exe consumes CPU load with disabled WSUS Service

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#43]
Anyone else seeing Trusted Installer kicking in, stealing CPU even when WSUS is set to Disabled on WS2016? And system is deploy from WIM already patched w latest CU. Very strange. Weak internet connection makes it even worse, so for now disabling WU/ TrustedInstaller (Class)

![image](https://user-images.githubusercontent.com/34108095/40701356-ec8b9580-63dd-11e8-971c-a5391d3ef87d.png)

For BIS-F possible to enable scheduled task, called **sih** on private image boot and disable it with BIS-F if image is in shared mode and WSUS service is disabled

**Comment by matthias-schlimm** [comment]
Actually I haven't disabled the sih task in my startup script (haven't seen that task running and consuming CPU yet), this is the task I regularly see consuming CPU on sealed images (if not disabled):
"\Microsoft\Windows\Servicing\StartComponentCleanup", also all .net tasks..

**Comment by matthias-schlimm** [comment]
Services and scheduled Tasks are out of scope from BIS-F, check out https://github.com/EUCweb/BIS-F/issues/133

**Comment by matthias-schlimm** [comment]
It can be done during startup with 99_PersBISF_StartUp.ps1

**Comment by matthias-schlimm** [comment]
05.10.2019 MS: ENH 43 - sihclient.exe consumes CPU load with disabled WSUS Service (function invoke-sihTask) in 99_PersBISF_StartUp.ps1
