### ISSUE TITLE
Citrix Optimizer Not operating via BIS-F

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#44]
Optimization Templates are not being picked up when NOT specified via ADMX. 

This is when looking for default templates.

Issue is looking like the "90_PrepBISF_CTX.ps1" file. The Template names are incorrect 

Example
(current = $template = 'Citrix_WindowsServer2016_x64' actual = Citrix_WindowsServer2016_1607.xml")

**Comment by matthias-schlimm** [comment]
I think it's possible to pre-defined all default templates in the ADMX, that's can also be easily changed for further usage

**Comment by JamesKindon** [comment]
Specifying the Template works, the problem occurs if we don't specify a template. If Martin and the optimizer team are going to release new templates regularly, it might be worth having an option in the ADMX that says Server 2008 R2 Template = "Defined by User", Server 2016 Template - "Defined by user".

The default could change depending on their release

**Comment by matthias-schlimm** [comment]
depending on the OS the template will be picked up if not specified in the ADMX. If Citrix changes this in the future we can handle it easier in the ADMX instead of the code

**Comment by matthias-schlimm** [comment]
@JamesKindon can you list all templates here, so we can change it in the code for the next minor update and for Major Release we add them to the ADMX

**Comment by JamesKindon** [comment]
Here are the latest ones

Citrix_Windows7_SP1.xml
Citrix_Windows10_1607.xml
Citrix_Windows10_1703.xml
Citrix_Windows10_1709.xml
Citrix_Windows81.xml
Citrix_WindowsServer2008R2.xml
Citrix_WindowsServer2012R2.xml
Citrix_WindowsServer2016_1607.xml

**Comment by matthias-schlimm** [comment]
get the Right ReleaseID with 
`(Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\" -Name ReleaseID).ReleaseId`

**Comment by matthias-schlimm** [comment]
try a test, grab a copy of the script and test it https://github.com/EUCweb/BIS-F/blob/bugfix/44_Pickup-CiitrixOptimizer-DefaultTemplates/Framework/SubCall/Preparation/90_PrepBISF_CTX.ps1

**Comment by musklor** [comment]
An issue for me too. Infinite boot loop during process.

Before : $template = 'Citrix_WindowsServer2016_$($ReleaseID)'
After : $template = "Citrix_WindowsServer2016_$($ReleaseID)"

Same issue with the others OS

Yes ! It works !

**Comment by matthias-schlimm** [comment]
fix it here https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/90_PrepBISF_CTX.ps1
