### ISSUE TITLE
PVS Optimizer Tool Disables Windows Search

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#45]
Annoyingly, the PVS Optimization tool disables the windows search service. This is a bit silly in this day and age, particularly when dealing with FSLogix and Outlook Indexing

Would be good to have a setting that is applied at the end the sealing routine that reverses this, and sets the search back to automatic. This would be ideal via an ADMX setting as not all environments will want search

**Comment by matthias-schlimm** [comment]
good point, will add create a new entry under ADMX BIS-F > Citrix > PVS / VDA Optimizer and start with Service

**Comment by matthias-schlimm** [comment]
@JamesKindon Services optimization is not a part of BIS-F anymore, use CTX optimizer or GPP
