### ISSUE TITLE
Make any PVS conversion work Optional

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#46]
It would be great to be able to continue with the BIS-F Routines even IF the PVS Target is installed, but we DON'T want BIS-F to do any conversion....A setting to say do nothing would be great

**Comment by matthias-schlimm** [comment]
good idea, we can add a option here

![image](https://user-images.githubusercontent.com/34108484/40715572-4a0387e0-6406-11e8-9d9a-92e9d5ed3e59.png)

**Comment by madrianr** [comment]
I Need this too - I thought that this tool is also usefull if I update the master image in private mode so I don't have to run Imaging Wizard...

**Comment by matthias-schlimm** [comment]
BIS-F automatically detect the bootmode and run the imagingwizard if you boot up from Harddisk only, this can be fullfill from bis-f with the current release.

**Comment by madrianr** [comment]
Thanks

 

Von: Matthias Schlimm [mailto:notifications@github.com] 
Gesendet: Donnerstag, 27. September 2018 16:45
An: EUCweb/BIS-F
Cc: Robert Madrian (madrian e-dbsolutions); Comment
Betreff: Re: [EUCweb/BIS-F] Make any PVS conversion work Optional (#46)

 

BIS-F automatically detect the bootmode and run the imagingwizard if you boot up from Harddisk only, this can be fullfill from bis-f with the current release.

**Comment by ryancbutler** [comment]
Is it possible to create a workaround by modifying personality.ini?  Set the INI to think its in private mode?  Would this still allow bis-f to run but not the disk convert?

**Comment by matthias-schlimm** [comment]
I think not good idea to modify a file, personality.ini also used for BIS-F diskmode and other optimizations are might to fail. 

I think about to add an option to the ADMX

**Comment by EUCweb** [comment]
manually merged from above PR, wrong branch for PR selected

**Comment by ozzy01** [comment]
Sweet. Yea, this will be beneficial for sure. To have it really just 'do nothing' if disabled or whatever. Glad it is in Bugs

**Comment by matthias-schlimm** [comment]
looks like this 

![BISF-PVSconfig1](https://user-images.githubusercontent.com/34108484/63970810-553d3500-caa5-11e9-8c57-34d7e2459668.png)
