### ISSUE TITLE
2008 R2 check disk issues

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#47]
Interestingly, after running BIS-F Against 2008 R2, when the machine is rebooted, it goes into a chk disk cycle. This happens every time BIS-F was run

I have resolved it for now with the following
https://blogs.technet.microsoft.com/ganand/2009/03/17/how-to-stop-chkdsk-from-running/ 
https://discussions.citrix.com/topic/374202-pvs-77-disk-check-runs-on-boot/

I know Server 2008 R2 is old (I haven't touched it in years but the current project requires it), but it might be worth having an option to disable Check Disk via BIS-F?

**Comment by matthias-schlimm** [comment]
is this really possible or can we skip it ?

**Comment by JamesKindon** [comment]
Lets kill it

**Comment by matthias-schlimm** [comment]
no further investigation on this issue
