### ISSUE TITLE
Citrix AppLayering does not detect the right layer 

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#48]
It‘s possible to use the runMode to detect the right layer. Got this informations behind 

1: Published image, all normal filtering takes place

2: Not used

3: Editing the OS Layer, no filtering takes place

4: Editing any app or platform layer

 

KEY_NAME="HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\unifltr"

VALUE_NAME=RunMode

**Comment by matthias-schlimm** [comment]
There are currently 4 valid numbers, 5 if you include the implicit "0, or not present, == not running at all":
 
1: Published image, all normal filtering takes place
2: Not used
3: Editing the OS Layer, no filtering takes place
4: Editing any app or platform layer
 
KEY_NAME="HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\unifltr"
VALUE_NAME=RunMode

**Comment by EUCweb** [comment]
In the layered Image the "Start"=dword:00000004 is set , in all other layers it's set to "Start"=dword:00000001. at the moment this is the only value to detect the layered image.

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\unifltr]
"Type"=dword:00000002
"Start"=dword:00000004
"ErrorControl"=dword:00000001
"Tag"=dword:00000002
"ImagePath"=hex(2):73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,44,00,\
  52,00,49,00,56,00,45,00,52,00,53,00,5c,00,75,00,6e,00,69,00,66,00,6c,00,74,\
  00,72,00,2e,00,73,00,79,00,73,00,00,00
"DisplayName"="unifltr"
"Group"="FSFilter Virtualization"
"DependOnService"=hex(7):46,00,6c,00,74,00,4d,00,67,00,72,00,00,00,00,00
"Description"="Unifltr mini-filter driver"
"SystemVolume"="C"
"RunMode"=dword:00000003
"SupportedFeatures"=dword:00000003
"UseWin10OpenRules"=dword:00000000

**Comment by EUCweb** [comment]
with DiskMode from BIS-F, we are able now to detect the No-ELM and n private boot based on CTX226062 

OS-layer: UnmanagedAppLayering
Platform layer: VDAPrivateAppLayering
App layer: UnmanagedAppLayering
Outside ELM: ReadWriteAppLayering
