### ISSUE TITLE
Citrix AppLayering - different shared configuration based on Layer

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#52]
ADMX Extension: Configure different configurations based on AppLayer

![BISF_AppLayering](https://user-images.githubusercontent.com/34108484/66257753-49781900-e79d-11e9-8cdc-963d68ea871c.JPG)

LIC_BISF_CLI_AppLayOSCfg | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_AppLayAppPltCfg | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_AppLayPltCfg | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_AppLayNoELM | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist

LIC_BISF_POL_AppLayCfg | DWORD | 1 | If Policy is enabled Registry   Data is set to 1, otherwise it not exist
LIC_BISF_CLI_AppLayCfg | REG_SZ | YES, NO | IF Policy is enabled Registry   Data is set to YES, if disabled set to NO; otherwise not exist.

**Comment by matthias-schlimm** [comment]
Export is finished, check Export-Registry function and BISF.ps1 too

Coding for import not yet

**Comment by matthias-schlimm** [comment]
![BISF-AppLayering-Export](https://user-images.githubusercontent.com/34108484/66265895-fdb98400-e81d-11e9-99a4-a47a8586e331.JPG)

Depending on the ADMX configuration the above menu is dynamically created and shows you the Layer to be exported from the current configuration

![BISF-AppLayering_ADMX](https://user-images.githubusercontent.com/34108484/66265907-19bd2580-e81e-11e9-9220-59d7602e2040.JPG)

**Comment by matthias-schlimm** [comment]
During Import BIS-F gets the AppLayer with automatic Fallback to the OS configuration

![BISF-AppLayering-Import](https://user-images.githubusercontent.com/34108484/66265929-73bdeb00-e81e-11e9-8bcb-758b334fde20.JPG)
