### ISSUE TITLE
ADMX: Configure BIS-F Desktop Shortcut

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#54]
you can configure, if a BIS-F Desktop shortcut is created during preparation on the Desktop of the admin, who starts BIS-F

**Comment by matthias-schlimm** [comment]
created in BB_develop branch

![2019-08-17_21-50-21](https://user-images.githubusercontent.com/34108484/63216678-11f3d580-c139-11e9-97b2-6d44211dcd94.jpg)
