### ISSUE TITLE
Windows Defender -ArgumentList failing

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#55]
Firstly, thank you for creating BIS-F. I'm an SCCM engineering who is moving into the Citrix PVS space, BIS-F integrated with our OSD task sequences really simplifies the whole processes. 

I noticed that during the task sequence the step for updating virus definitions for Windows Defender sits idle and then fails after 60 maximum run time. Looking into the script further, the command line is **Start-Process -FilePath "$ProductPath\MpCMDrun.exe" -ArgumentList "SignatureUpdate" -WindowStyle Hidden**

The signatureupdate argument should be -SignatureUpdate (proceeding dash is missing). This causes Windows Defender to error 'Update failed with hr: 0x80070490". 

Updating the PowerShell script to Start-Process -FilePath "**$ProductPath\MpCMDrun.exe" -ArgumentList "-SignatureUpdate" -WindowStyle Hidden**
resolves the issues.

**Comment by matthias-schlimm** [comment]
fixed in 20.10.2018 MS: Bugfix 55: Windows Defender -ArgumentList failing

https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_AV-WinDefend.ps1
