### ISSUE TITLE
Mc Afee - remove hardcoded maconfig.exe path

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#58]
In script 10_PrepBISF_AV-McAfee.ps1 the executable is hardcoded 

$PrepApp_x64 = "${env:ProgramFiles}\McAfee\Common Framework\maconfig.exe"
$PrepApp_x86 = "${env:ProgramFiles(x86)}\McAfee\Common Framework\maconfig.exe"

possible search in ${env:ProgramFiles(x86)}\McAfee or ${env:ProgramFiles}\McAfee

**Comment by EUCweb** [comment]
fixed in https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_AV-McAfee.ps1
