### ISSUE TITLE
Function DelSepData inside the personalization SEP script

### ISSUE THREAD

**Issue by musklor** [EUCweb/BIS-F#59]
Hi, I've made some test and I think it could be a great idea if you put the DelSepData function inside the sep personalization script.
Why? If someone forget the most important task : sealing. It's a security and best practices from Symantec.

**Comment by musklor** [comment]
If the PVS updater is inside a sep group with a tamper protection, the target devices will be in the same sep group. It's the easiest way to manage.

**Comment by matthias-schlimm** [comment]
Without sealing, personalization won't work, because the scheduled task isn't created. this is required to run the BIS-F personalization on startup

**Comment by musklor** [comment]
Obviously, the first time we need to seal with the script, but my idea is for the others times when we need to update the vdisk.

**Comment by matthias-schlimm** [comment]
Everytime after an update run the BIS-F Preperation to seal the image

**Comment by musklor** [comment]
Yes I agree. We can close.
Thanks for your script.
Viva Kaspersky, the perfect av for PVS :)
