### ISSUE TITLE
Endless Reboot with VMware Paravirtual SCSI disk

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#6]
we discovered a bug when using VMware Paravirtual SCSI disk controller (get disk ID 1) compared to default OOTB LSI Logic SAS (disk 0). Goes into a endless reboot

More info : https://www.vladan.fr/performance-optimized-vm-of-windows-server-2016-on-esxi-6-5-creation-steps-guide/

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#22
