### ISSUE TITLE
Add Parallels RAS support

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#6]
_From @matthias-schimm on March 12, 2018 20:48_

Service Name = RAS RD Session Host Agent
Display Name = RAS RD Session Host Agent 
EXE = C:\Program Files (x86)\Parallels\ApplicationServer\2XAgent.exe

Parallels Remote Appilcation Server // https://www.parallels.com/products/ras/remote-application-server/
 
RAS is a add on product to regular RDSH so treat it as that

basically one or two controllers and then x number of session hosts with or without their agent, because it can be push directly from their admin console.

these days it's all agents for VMW, CTX and Parallels // The rest is the same

_Copied from original issue: EUCweb/BIS-F#25_

**Comment by matthias-schlimm** [comment]
included in BB_develop
