### ISSUE TITLE
Script 10_PrepBISF_AV-SEP and 10_PersBISF_AV-SEP

### ISSUE THREAD

**Issue by musklor** [EUCweb/BIS-F#61]
We could put the Server in the right SEP GROUP (tamper protection disabled) before processing.

Before: 
C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc -start
C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc -importsylink
C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc -updateconfig
C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc -stop
 
After:
C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc -stop
C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc -importsylink
C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc -updateconfig
C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc -start

**Comment by matthias-schlimm** [comment]
what you mean with Before and After ? in which of the both SEP scripts possible to run, please explain it in more detail, thx.

**Comment by musklor** [comment]
Beginning and end of script

**Comment by matthias-schlimm** [comment]
if you start the smc.exe at the end of the preparation, it's not possible. this will create a new GUID on the Master itself, which was deleted before in the registry and the filesystem

**Comment by musklor** [comment]
Of course. My idea isn't good. I don't want to put the sep password inside the script. I think I'll deactivate the tamper protection for the updater AND the target devices. And all your scripts will be fully functional.

**Comment by matthias-schlimm** [comment]
sounds good
