### ISSUE TITLE
BIS-F AppLayering - Layer Finalzed is blocked with MCS - Booting Layered Image

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#62]
From @MathiasSVA
I let Applayering create a machine that is meant for an MCS distribution, but in the environment the VM needs to be rebooted once and an adaptation made, due to a special software. If I then want to run BIS-F, then it bangs accordingly, because BIS-F makes the assumption it is an OS layer. As mentioned above, the AppLayering service has been set to disabled by itself

The RunMode Registry Key is set to 3 in the finalized image

please find attached the BIS-F logfile
[Prep_BIS_REZ01SRLAYERING_20180906-113056.log](https://github.com/EUCweb/BIS-F/files/2358251/Prep_BIS_REZ01SRLAYERING_20180906-113056.log)

**Comment by matthias-schlimm** [comment]
@MathiasSVA please upload the logs from OS, Platform and App-Layer. I will check it and compare before proceed, thx.

**Comment by matthias-schlimm** [comment]
Please fix it temp. with the following manual code change 

In **BISF.psm1** - Function **Test-AppLayeringSoftware** - change Line 2090

**from:**
`IF ($DiskMode -eq "ReadWriteAppLayering") {`

**to:**
`IF (($DiskMode -eq "ReadWriteAppLayering") -or ($svc.Status -ne 'Running')) {`

**Comment by matthias-schlimm** [comment]
@MathiasSVA

fixed in https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Global/BISF.psm1

**Comment by matthias-schlimm** [comment]
@fangludi reported the Layer is not Right detected with this Change above

**Comment by matthias-schlimm** [comment]
I have removed the fix above from the developer branch

**Comment by fangludi** [comment]
Thanks, if $svc = Test-BISFService -ServiceName "UniService" -ProductName "Citrix AppLayering", it will only return true or false.. Maybe you need Test-BISFServiceState instead of Test-BISFService to let it show the status which is running or not.

**Comment by matthias-schlimm** [comment]
Thanks Fangludi, you are Right.. my fault 

Please grab a copy of the developer branch and test ot again, possible in all Layers
https://github.com/EUCweb/BIS-F/tree/develop

**Comment by fangludi** [comment]
Now it works in all layers, I just test, thanks!

**Comment by matthias-schlimm** [comment]
Please send me the BIS-F logs from all layers, I will have a look under the hood. Prep and Pers log please

**Comment by fangludi** [comment]
[log.zip](https://github.com/EUCweb/BIS-F/files/2500293/log.zip)
