### ISSUE TITLE
personal vdisk inventory on vdi clients only

### ISSUE THREAD

**Issue by musklor** [EUCweb/BIS-F#64]
Hi, could you explain me this feature, please?

**Comment by matthias-schlimm** [comment]
Sorry, this is not the right Place to discuss, please join the BIS-F Slack channel to discuss your questions 

Join it here https://join.slack.com/t/bis-f/shared_invite/enQtNDMyNDU4NzU2Mzg3LWI3OGJjNDgwNTU2OTgxZTQyYmFiNTBlNjlhY2EzNzIzZWVjNzM1MWE0YTg4ZjY5YTc3NTQwNTA3OGJhZmFhNTg

**Comment by musklor** [comment]
Sorry
