### ISSUE TITLE
Add an option to delete the log files for Citrix Optimizer

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#65]
Created from @fangludi

If users enable Citrix Optimizer in BIS-F, three files (execute_History.html, execute_History.xml, and Log_Debug_CTXOE.log) will be generated in Logs folder by date/time inside the installation location of Citrix Optimizer every time they run the BIS-F preparation script, so it's better to add an option to delete those log files after executing the Citrix Optimizer.

**Comment by matthias-schlimm** [comment]
the log can be deleted, but not the XML file

**Comment by matthias-schlimm** [comment]
![BISF-CTXOE](https://user-images.githubusercontent.com/34108484/66145485-39c8cb00-e60b-11e9-874d-6c66eace5541.JPG)


LIC_BISF_CLI_CTXOE_LogDelete | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
