### ISSUE TITLE
[02.105] vietool.exe - custom searchpath not working correctly

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#66]
Just noticed that in build 02.105, The custom search path for the vietool.exe is not picking up the executable while it does exist in the provided folder. It does pick up correctly from \System32 when you do not configure a custom search path though

**Comment by matthias-schlimm** [comment]
Change line 142:

**old:**
$VIEExists = Get-ChildItem -Path "$VIESearchFolder" -filter "$VIEApp" -ErrorAction SilentlyContinue | Where {$_.FullName -notlike "*Tools\*"} | % {$_.FullName}


**new:**

$VIEExists = Get-ChildItem -Path "$VIESearchFolder" -filter "$VIEApp" -ErrorAction SilentlyContinue | % {$_.FullName}
		    }    
		    }

**Comment by matthias-schlimm** [comment]
vietool. in a Path like Tools will not work, fix it in 
https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_AV-SEP.ps1
