### ISSUE TITLE
00_PersBISF_WriteCacheDisk.ps1 function CheckWriteCacheDrive fails if partition type is UEFI

### ISSUE THREAD

**Issue by vMathias79** [EUCweb/BIS-F#67]
Due to different Volume count on an UEFI parition type system this check inside of the function CheckWriteCacheDrive

If ((Get-WmiObject -Class Win32_volume).count -lt 3) 

does not apply due to different volume count on UEFI (already 3 partitions present).

Maybe an alternate check method should be implemented to make this failsafe?

**Comment by musklor** [comment]
UEFI : If ((Get-WmiObject -Class Win32_volume).count -lt 4)

or for English OS : If ((Get-WmiObject -Class Win32_volume | where {$_.Label -notlike "system reserved"}).count -lt 3)

**Comment by musklor** [comment]
If ((Get-WmiObject -Class Win32_volume | where {$_.Label -notmatch "syst.m|r.serv."}).count -lt 3)
(ok for English And French OS)

**Comment by matthias-schlimm** [comment]
I will add a option to BIS-F admx to select the count of partitions

**Comment by matthias-schlimm** [comment]
will discuss this further here https://github.com/EUCweb/BIS-F/issues/21
