### ISSUE TITLE
If WriteCache disk on master is GPT-partiton then uniqueid doesn't match

### ISSUE THREAD

**Issue by vMathias79** [EUCweb/BIS-F#69]
If the WriteCache disk on the master is formatted in GPT-style the uniqueid that is saved to the registry will not be applied correctly because BIS-F always creates a MBR-partition for the writecache. 

Suggestion: If the uniqueid saved in the registry has a length of a GUID, then create a GPT partition, else if length = 8 create MBR

furthermore when getting the uniqueid via diskpart the curly brackets have to be removed. diskpart will return the guid in curly brackets:

DISKPART> uniqueid disk
Disk ID: {C1C66B06-6C5D-4AD8-BE48-0405694202A7}

But when setting the uniqueid it expects the brackets to be removed:
DISKPART> uniqueid disk ID={C1C66B06-6C5D-4AD8-BE48-0405694202A7}

The specified identifier is not in the correct format.
Type the identifier in the correct format:
in hexadecimal form for an MBR disk or as a GUID for a GPT disk.

So best when tested if it is a GPT uniqueid do a $str = $str -replace '[{}]' to remove the brackets before saving to registry.

**Comment by matthias-schlimm** [comment]
thx, good point

**Comment by matthias-schlimm** [comment]
@MathiasK-SVA possible to send a PR in the next upcoming weeks ?

**Comment by matthias-schlimm** [comment]
fixed in https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Preparation/80_PrepBISF_WriteCacheDisk.ps1
