### ISSUE TITLE
PVS WriteCacheDisk - endless Reboot if System Reserved Parttion exists

### ISSUE THREAD

**Issue by matthias-schimm** [EUCweb/BIS-F#7]
If the System Reserved Partition exists, the formating of the WriteCacheDisk run in a endless reboot, beacuse in the script 00_PersBISF_WriteCacheDisk.ps1, line 102 -> If ((Get-WmiObject -Class Win32_volume).count -lt 3)  it checks the count of the drives <3, means SystemDrive and WriteCache only. 
 
**Workaround:**
IF you have System Reserverd Partation increase the above value from 3 to 5 manualy, we are working on a fix for this

**Comment by EUCweb** [comment]
This issue was moved to EUCweb/BISF#21
