### ISSUE TITLE
VDA Configuration results in Citrix Desktopservice as Disabled

### ISSUE THREAD

**Issue by madrianr** [EUCweb/BIS-F#70]
**Describe the bug**
If I activate the Delay Citrix Desktop Service then after runnig BIS-F the  Citrix Desktopservice as Disabled...

**Screenshots**
![unbenannt1](https://user-images.githubusercontent.com/10518186/46192812-d61b0c00-c2eb-11e8-96a7-e1b673473422.JPG)
![unbenannt2](https://user-images.githubusercontent.com/10518186/46192820-dadfc000-c2eb-11e8-8da6-d1d2e9248c2d.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 1803 x64

**Comment by matthias-schlimm** [comment]
RTFM :-)

https://edocs.eucweb.com/docs/bis-f-6-1-0/configure/citrix/ 

> Delay Citrix Desktop Service:
> The Citrix Desktop Service controls the registration state through the Citrix Controller. In some circumstances, this service has successfull registered the VM and the user can logged on to this, through Receiver/StoreFront. In the Backend some depend actions like Workspace Environment Agent, Group Policies, App-V Client and someone else are not completed with their own task. If you enable this policy the Citrix Destop Service would be started first, if the BIS-F personalization is finished.
> 
> Note: If you has the Device personalization configured to skip it on all DiskModes or on private Mode only, the Citrix Desktop Service would also be started.

**Comment by matthias-schlimm** [comment]
any questions ? otherwise I will close it

**Comment by madrianr** [comment]
First it is not fine to see RTFM :-(

I'm new to BIS-F and it seems that I do something wrong - so it would be nice to Point me in the Right direction - what I'm missing?

robert

**Comment by matthias-schlimm** [comment]
no worries ...

If you enable this policy, BIS-F disable the service during sealing and on startup, the BIS-F scheduled task starts the Desktop  Service at the end of the BIS-F personalization.

**Comment by madrianr** [comment]
what is the BIS-F scheduled task - do you mean the Service should be startet after sealing?

**Comment by matthias-schlimm** [comment]
The BIS-F scheduled task is creating during sealing. It's needed on startup and processes all scripts in the personalization folder

https://edocs.eucweb.com/docs/bis-f-6-1-0/flow-diagramm/personalization-system/
