### ISSUE TITLE
MCS Deployment: SCOM Agent - creates OpsStateDir in C: drive

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#72]
with Citrix MCS Deployment, during personalization the script creates the C:\OpsStateDir instead leave them in the origin path

**Screenshots**
![image](https://user-images.githubusercontent.com/34108095/47195696-481bc980-d35d-11e8-86ee-e443a8bfcaad.png)

**Comment by matthias-schlimm** [comment]
under review on customer level

**Comment by matthias-schlimm** [comment]
fixed
