### ISSUE TITLE
Adding more detected hypervisors/agents

### ISSUE THREAD

**Issue by FlorianHeigl** [EUCweb/BIS-F#76]
**Is your feature request related to a problem? Please describe.**
Adding support of KVM, Xen

**Describe the solution you'd like**
I'd like to provide a patch extending the list of VM tools to also find the free hypervisors that could be relatively easily used with VDI. (I mean, I would skip VirtualBox :)

I saw the issue that added i.e. Nutanix support:
https://github.com/EUCweb/BIS-F/issues/13

But I don't see any patch that would have come with it, and also can't find anything in the repository. If you can tell me where to look I'll add support. 

**Describe alternatives you've considered**
Not much I can do instead of fully diving into the whole project before being able to really try it :)

**Additional context**
I wanna test & document BIS-F. It is my understanding that it is a bit less deeply tied into a specific platform, and that is nice.

**Comment by FlorianHeigl** [comment]
If you just want the info

## KVM (need to look for QEMU since KVM is just QEMU with hardware virt)

* QEMU Guest Agent
* QEMU Guest Agent VSS Provider

(There's a third service, for the hypervisor hardware watchdog, but to my knowledge there is no person on earth who got that service to run, it seemed largely unmaintained)

I do not have the Service names for Red Hat "RHEV", the commercial offspring.

## Xen


I do not have the Service names for the Xen Project itself, and am uncertain if there ever *was* a VSS provider or anything else.
I'll double check.

I hope there is something for Oracle VM though, which is a pretty pure Xen setup.

**Comment by matthias-schlimm** [comment]
It's a part of the Bugs Bunny Release, here https://github.com/EUCweb/BIS-F/blob/6.2.0_Bugs_Bunny/Framework/SubCall/Global/BISF.psm1

You need to edit the function _Get-Hypervisor_

**Please note**: Bugs Bunny release is not finalized yet, this is the next release of BIS-F, will be available next year

**Comment by EUCweb** [comment]
with POSH command, can get Manufacturer and Model
 
`Get-WmiObject -query 'select * from Win32_ComputerSystem' | select-object Manufacturer,Model`

**Oracle VirualBox**
Manufacturer:  innotek GmbH
Model: virtualBox


**Nutanix AHV**
Manufacturer:  Nutanix   
Model: AHV


**Citrix Hypervisor**
Manufacturer: Xen                  
Model: HVM domU


**Vmware:**
Manufacturer: VMware, Inc.                            
Model: VMware Virtual Platform 

 **Hyper-V:**
Manufacturer: Microsoft Corporation                   
Model: Virtual Machine

**Comment by EUCweb** [comment]
@FlorianHeigl can you run the above Powershell-Command on a Windows VM hosted on KVM and share the output here

**Comment by matthias-schlimm** [comment]
@FlorianHeigl can you run the following Powershell Command on Windows VM hosted on KVM and share the output ?

`Get-WmiObject -query 'select * from Win32_ComputerSystem' | select-object Manufacturer,Model`

**Comment by FlorianHeigl** [comment]
Sorry that this fell down on my end.
