### ISSUE TITLE
Reset wsus

### ISSUE THREAD

**Issue by musklor** [EUCweb/BIS-F#77]
Hello, here an interesting page for resetting WSUS.
https://support.microsoft.com/en-au/help/971058/how-do-i-reset-windows-update-components

You could add some of this commands.
Yesterday, I had two servers (pvs updater, one vdisk 2016base and one copy 2016admin) but with one id in the wsus panel. (Bis-f script used)

**Comment by musklor** [comment]
I saw a piece of code to reset the susclientid inside bis-f script, but only with targeting enabled. So I've disabled this test (I don't use targeting for the moment) and the keys are killed now.

**Comment by matthias-schlimm** [comment]
Fixed in https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Preparation/97_PrepBISF_PRE_BaseImage.ps1
