### ISSUE TITLE
Provide Prepare4Image for the Ivanti Automation agent as choice

### ISSUE THREAD

**Issue by Siebrandf** [EUCweb/BIS-F#78]
I want BIS-F not to touch the RESWAS service and agent settings. Despite that it removes settings like the CachedDispatcher and CommunicationID settings which breaks the agent. I have the Ivanti Agent in a Platform Updating Layer, which provides me the opportunity to automate and secure layer creation and maintenance. I want the agent to survive BIS-F preparation activities (I run BIS-F for layer sealing) and left untouched. Here is an snippet from the BIS-F log; 

11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | RES ONE Automation Service would not stopped (ADMX configuration)
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Prepare for Imaging...
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | RES ROA Registry Path: HKLM:\SOFTWARE\RES\AutomationManager
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | RES ROA Install Path: C:\Program Files\RES\Automation\Agent
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Processing function Test-BISFRegistryValue
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Registrypath HKLM:\SOFTWARE\RES\AutomationManager\Agent, Value CachedDispatchers exists
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Processing function Test-BISFRegistryValue
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Registrypath HKLM:\SOFTWARE\RES\AutomationManager\Agent, Value CommunicationID exists
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Processing function Test-BISFRegistryValue
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Registrypath HKLM:\SOFTWARE\RES\AutomationManager\Agent, Value DispatcherListKGC NOT exists !!
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Processing function Test-BISFRegistryValue
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Registrypath HKLM:\SOFTWARE\RES\AutomationManager\Preferences, Value WUID exists
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Processing function Test-BISFRegistryValue
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Registrypath HKLM:\SOFTWARE\RES\AutomationManager\Agent, Value LastKnownResourceCacheFolder NOT exists !!
11/2/2018 8:26:15 AM | nacxddev | WARNING......... | Standardpath is set to C:\Program Files\RES\Automation\Agent\Workspace and could NOT deleted
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Check Silentswitch...
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | Silentswitch would be set to NO
11/2/2018 8:26:15 AM | nacxddev | INFORMATION... | RES ONE Automation Agent Service (RESWAS) - configuration not changed

**Comment by matthias-schlimm** [comment]
@Siebrandf I'm not using Ivanti RES, so you mean didn't stop the RESWAS Agent during Image sealing. ? Is that enough or some more else ?

**Comment by Siebrandf** [comment]
Matthias,

The issue is that currently when an RES One Automation agent is found, it removes all these entries like CachedDispatchers and CommunicationID etc, and it sets the Prepered4Image. I now commented out lines 130-174 from the 10_PrepBISF_RES.ps1. Basically what I want is an extra option that make me choose if I want the Image preperation section to run or not. If not, it should just skip these lines and keep the the settings in place. It's not so much disabling the service but more the removal of the settings mentioned which makes the Agent isolated and no longer to use when approached as we do.

**Comment by EUCweb** [comment]
Ok, thanks for the update. I will added an option to the ADMX as you describe.

**Comment by Siebrandf** [comment]
Awesome!

**Comment by EUCweb** [comment]
New Release is planned end of year 7 1912

**Comment by EUCweb** [comment]
Can you upload here your modified script as a txt file please

**Comment by Siebrandf** [comment]
[10_PrepBISF_RES.txt](https://github.com/EUCweb/BIS-F/files/3509403/10_PrepBISF_RES.txt)

**Comment by matthias-schlimm** [comment]
@Siebrandf it looks like this 

![2019-08-17_20-35-14](https://user-images.githubusercontent.com/34108484/63215987-a73d9c80-c12e-11e9-9187-6fa02d676f31.jpg)

**Comment by matthias-schlimm** [comment]
it's now included in BB_develop branch, coding also done in https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Preparation/10_PrepBISF_RES.ps1 starting in Line 133
