### ISSUE TITLE
VMWare RSS and TCPIP Optimizations

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#8]
_From @matthias-schimm on March 12, 2018 20:38_

Script to enable or disable RSS via Policy.  If enabled via Policy then configuration should take place to try and set performance-based results.  2017 "best practices" are to configure RSS as follows:

- Use "N-1" CPU's and assign to RSS.
    EG, if a system has 4 CPU's, assign 3 to RSS for a single NIC
- Use NUMA for RSS and divide CPU time along NUMA configurations.  eg, in a 2 x 6 vCPU system (12 total) with a single NIC assign 5 CPU's on NUMA node 0 to the NIC.  If two NIC's are present, then assign 5 vCPU's on NUMA 0 to NIC1 and 5 vCPU's on NUMA1 to NIC2

_Copied from original issue: EUCweb/BIS-F#20_

**Comment by Trentent** [comment]
First draft of this is complete.  Requires creating policy configuration to enable/disable feature.

I imagine if we "disable" this feature then no NUMA math or anything assigned...

2nd question is should we detect if NUMA is available on the VM/machine?  There are configurations in both BIOS and on the VM level that can disable NUMA so any configuration is useless anyways.  I do have a working PowerShell script with PInvoke to check for the presence of NUMA.
[Find_NumaNodePresent.zip](https://github.com/EUCweb/BIS-F/files/1868396/Find_NumaNodePresent.zip)

**Comment by matthias-schlimm** [comment]
[05_AHSCustom_VMWareTCPIPOptimizations.ps1.zip](https://github.com/EUCweb/BIS-F/files/3517313/05_AHSCustom_VMWareTCPIPOptimizations.ps1.zip)

**Comment by matthias-schlimm** [comment]
integrated into BB_develop, script is processing during preparation 05_PrepBISF_VMWareTCPIPOptimizations.ps1
