### ISSUE TITLE
CitrixOptimizer: Wrong template Names

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#80]
regarding Citrix Optimizer v2 and BIS-F 6.1.0 build 01.102, it gave me an error since BIS-F Search for Templates like
Citrix_WindowsServer2016_$($ReleaseID).xml Citrix_WindowsServer2019_$($ReleaseID).xml
And Citrix Optimizer v2 named them
Citrix_Windows_Server_2016_1607.xml
Citrix_Windows_Server_2019_1809
I just changed it in 90_PrepBISF_CTX.ps1, but think one of you should change it

<img width="527" alt="bildschirmfoto 2018-12-17 um 12 22 44" src="https://user-images.githubusercontent.com/34108484/50084237-8a934280-01f6-11e9-9f61-d7aa6887f3c1.png">

**Comment by matthias-schlimm** [comment]
Feedback from Martin Zugec: Yes, these names are final... We have decided to rename templates in order to support auto-selection

**Comment by EUCweb** [comment]
fixed in Release 6.1.0. build 01.103
