### ISSUE TITLE
Signed Installer

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#81]
During packaging the installer, sign the POSH scripts with CodeSigning Certificate.
**dependency:** remove executionpolicy bypass from PrepareBaseImage.cmd

**Comment by matthias-schlimm** [comment]
Signed Installer available now

**Comment by joshtbernstein** [comment]
@matthias-schlimm Did the change in PrepareBaseImage.cmd happen? I've just downloaded 7.1219.2.11029 and I'm still seeing "set-executionpolicy bypass".

**Comment by matthias-schlimm** [comment]
The installer is signed only, not the scripts itswlf.

 

Von: Josh <notifications@github.com> 
Gesendet: Donnerstag, 2. April 2020 19:29
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Matthias Schlimm <matthias.schlimm@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Signed Installer (#81)

 

@matthias-schlimm <https://github.com/matthias-schlimm>  Did the change in PrepareBaseImage.cmd happen? I've just downloaded 7.1219.2.11029 and I'm still seeing "set-executionpolicy bypass".
