### ISSUE TITLE
RES ONE Automation Agent - Action is missing 

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#82]
During sealing the preparation of the RES ONE Automation Agent stucks

![image](https://user-images.githubusercontent.com/34108484/51301085-416d2300-1a2e-11e9-8d78-646b53cba98f.png)

Script **10_PrepBISF_RES.ps1** - Change Line 204 to the following:
_Invoke -BISFService -ServiceName "$Svc3" -StartType Disabled -Action Stop_

**Comment by EUCweb** [comment]
fixed in https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_RES.ps1
