### ISSUE TITLE
Office 2019 detection

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#86]
latest BIS-F release 6.1.0 build 01.103 does not detect Office 2019. Possible to integrate it in 6.1.0 too and do not wait for Bugs Bunny release later this year

**Comment by EUCweb** [comment]
FRQ is here: grab this files and copy it to your installation directories and replace the old one
checkout https://github.com/EUCweb/BIS-F/blob/master/ReleaseNotes.txt

https://github.com/EUCweb/BIS-F/blob/master/Framework/SubCall/Preparation/96_PrepBISF_Rearm.ps1

https://github.com/EUCweb/BIS-F/blob/master/Framework/SubCall/Personalization/10_PersBISF_OfficeKMS.ps1

**Comment by EUCweb** [comment]
**must added for Bugs Bunny Release too, but keep O365 in BB release. Files above are different in BB Release**

**Comment by matthias-schlimm** [comment]
added Office 2019 support for BB Release too:

https://github.com/EUCweb/BIS-F/blob/6.2.0_Bugs_Bunny/ReleaseNotes.txt

https://github.com/EUCweb/BIS-F/blob/6.2.0_Bugs_Bunny/Framework/SubCall/Preparation/96_PrepBISF_Rearm.ps1

https://github.com/EUCweb/BIS-F/blob/6.2.0_Bugs_Bunny/Framework/SubCall/Personalization/10_PersBISF_OfficeKMS.ps1

**Comment by matthias-schlimm** [comment]
build release 6.1.0 build 01.104
