### ISSUE TITLE
Symantec Endpoint Protection 14.0 MP2 prevents graceful Citrix session logoff

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#87]
**Situation**
After installing or upgrading to Symantec Endpoint Protection (SEP) 14.0 MP2 in a Citrix environment, you find that it prevents graceful session logoff.

 

**Cause**
Our SymQual error reporting service prevents graceful session logoff due to locked WER folders:

Users\%username%\AppData\Local\Microsoft\Windows\WER\ReportArchive
Users\%username%\AppData\Local\Microsoft\Windows\WER\ReportQueue

**Solution**
Symantec is aware of this issue and will update this document when a solution becomes available. It is not necessary to log a support case on this issue. Please subscribe to this article to be notified of any updates.

The following workaround will effectively resolve the issue:

Double-click the Symantec Endpoint Protection notification area icon. In the left-hand column, click Change Settings.
Scroll down to Client Management and click the Configure Settings button.
Navigate to the Tamper Protection tab.
Uncheck the Protect Symantec security software from being tampered with or shut down checkbox and click the OK button.
Browse to the SEP installation path .._.\Symantec Endpoint Protection\14.x\bin\_ folder.
Rename **sqsvc.dll, sqscr.dll** and **symerr.exe** files to: **sqsvc.dll.old, sqscr.dll.old** and **symerr.exe.old**
Click Windows Start > Run and type and run the following: smc -stop, and then followed by smc -start. Return to the Tamper Protection tab and click the Protect Symantec security software from being tampered with or shut down checkbox and click the OK button.

https://support.symantec.com/en_US/article.TECH247167.html

**Comment by matthias-schlimm** [comment]
waiting for customer feedback. As described above, the files are renamed

![image](https://user-images.githubusercontent.com/34108484/55987573-1d725400-5ca2-11e9-991b-41bfac72116b.png)

**get the Hotfix here and replace the file in the BIS-F preparation folder:** https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_AV-SEP.ps1

**Comment by matthias-schlimm** [comment]
test at customer level, running without issues:

Hotfix available for CR and future BB release

**Comment by jeremyts** [comment]
Note that Symantec has confirmed that this issue is also present in 14.2 MP1, so it's not just a 14.0 MP2 issue.

**Comment by ScarUY** [comment]
> Note that Symantec has confirmed that this issue is also present in 14.2 MP1, so it's not just a 14.0 MP2 issue.

Currently using 14.3 RU5 and the problem is still there.
