### ISSUE TITLE
Request: Mcafee Endpoint security Detection

### ISSUE THREAD

**Issue by wing2005** [EUCweb/BIS-F#88]
Hi, 
We have Mcafee ENS, its using the same Agent and reg keys that needs to be deleted, but the script is not running because its looking for the old Engine VSE.

**Comment by EUCweb** [comment]
Can you send us the new one, means the servicename,  displayname and other relevant informations

**Comment by wing2005** [comment]
display name: mcafee endpoint security

service file: (x64)
c:\program files\mcafee\mcafee endpoint security\endpoint security platform\mfeesp.exe


i have added elseif clause in the script to check the file and run the cleanup, i'll test run it...

**Comment by wing2005** [comment]
how do i test only the av script without running the whole sealing process?

**Comment by EUCweb** [comment]
checkout Run single Script for Testing https://eucweb.com/kba/27190824

**Comment by wing2005** [comment]
i have tested it and its working. how do i submit for your review?

**Comment by EUCweb** [comment]
you can upload it here in the issue itself, thanks for help to make this tool even better

**Comment by EUCweb** [comment]
what's the Name of the service itself, same as Display Name ?

**Comment by wing2005** [comment]
attached image  -the file properties
i have commented all my add ins and changes. if variables are not in convention, edit them 
[bisf-mcafee.zip](https://github.com/EUCweb/BIS-F/files/3124934/bisf-mcafee.zip)

**Comment by EUCweb** [comment]
thx, I must convert your changes to my new script, this is for the new BIS-F version with MC Afee Move 
https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_AV-McAfee.ps1

**Comment by wing2005** [comment]
glad to help, its a great tool! until the updated version comes, i'm using my file.

**Comment by matthias-schlimm** [comment]
@wing2005 merged your script into the existing one, can you grab this single script only and try a test please https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Preparation/10_PrepBISF_AV-McAfee.ps1

**Comment by wing2005** [comment]
hello,
found on typo:
line 291 - should be Start-DefUpdates

working like a charm!!
thenks!
[image: image.png]
Sincerely,
Itamar Glick
MCSE 2003, MCSE+MESSAGING, MCP
itamargl@gmail.com

**Comment by matthias-schlimm** [comment]
fixed, thanks

will close this issue now
