### ISSUE TITLE
Cylance generalization / Citrix 'compatibility mode' enablement 

### ISSUE THREAD

**Issue by ozzy01** [EUCweb/BIS-F#89]
Per https://support.citrix.com/article/CTX232722, for Cylance, I always have make sure and enable the registry key for 'compatibility mode' as described therein.  Has hampered me on non-Citrix stuff as well.  I think there is some generalization as well from a Cylance perspective to clear a reg key that Matthias K was describing. Anyway, thought it would be good to add in under the AV options or whatever... thanks fellas

**Comment by EUCweb** [comment]
Thx Ozzy, BIS-F detects the  Software if a service is available or not, please send me the servicename and displayname

**Comment by ozzy01** [comment]
Yea, so its a service called " Cylance Protect" 
![image](https://user-images.githubusercontent.com/24480911/57104873-106be200-6cef-11e9-8980-4595c9a26b73.png)

**Comment by EUCweb** [comment]
Display and Servicename are still the same ? Please open up the service and take a screenshot of the properties first tab.

**Comment by ozzy01** [comment]
![image](https://user-images.githubusercontent.com/24480911/57145831-a48a8780-6d89-11e9-8f93-b3362125d6a8.png)

**Comment by matthias-schlimm** [comment]
merged pull request https://github.com/EUCweb/BIS-F/pull/100 into develop branch
@ozzy01 please grab a copy of https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Preparation/10_PrepBISF_AV-CylanceProtect.ps1 and copy it to your installation to test the Cyclance script

**Comment by ozzy01** [comment]
FYI, we have/are testing this. It failed on something so we are reviewing log tomorrow and will comment back in here

**Comment by matthias-schlimm** [comment]
@ozzy01 can you grab a copy of https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Preparation/10_PrepBISF_AV-CylanceProtect.ps1 this is now with CompatibilityMode enabled, currently not controlled via ADMX..

**Comment by ozzy01** [comment]
Perfect Thanks!

**Comment by matthias-schlimm** [comment]
Possible to send feedback, no chance to test it. It‘s a blind audition for me
