### ISSUE TITLE
Microsoft LAPS support

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#9]
_From @matthias-schimm on March 12, 2018 20:37_

See https://blog.thesysadmins.co.uk/deploying-microsoft-laps-non-persistent-vdi.html

Or make use of the PowerShell Module...
![laps](https://user-images.githubusercontent.com/34108484/37308176-1db34338-2635-11e8-8604-d5d6fba8ac55.png)

_Copied from original issue: EUCweb/BIS-F#19_

**Comment by matthias-schlimm** [comment]
BIS-F can use the script from this BLOG during startup https://www.citrix.com/blogs/2017/12/12/password-wars-randomizing-local-admin-passwords-in-non-persistent-environments/

**Comment by matthias-schlimm** [comment]
BIS-F can use the script from this BLOG during startup https://www.citrix.com/blogs/2017/12/12/password-wars-randomizing-local-admin-passwords-in-non-persistent-environments/

**Comment by matthias-schlimm** [comment]
![LAPS](https://user-images.githubusercontent.com/34108484/65369066-e89efb80-dc48-11e9-97ae-f7a18f9b6a47.JPG)

**Comment by matthias-schlimm** [comment]
added ADMX with LAPS support and trigger script https://github.com/EUCweb/BIS-F/blob/BB_develop/Framework/SubCall/Personalization/01_PersBISF_MS.ps1
