### ISSUE TITLE
New BIS-F version numbers like yymm.v

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#90]
For new BIS-F Release it's possible to create new Version numbers like 1905.1 (looks like MS and CTX)

Currently the build number increases automatically during creating the installer:

01 = PROD
02 = ACCEPTANCE
03 = TEST
04 = DEV

internal build numbers also required, for the frontend:
yymm.v = 1905.0  
Version = 6.5.0 build 01.nnn

**Comment by EUCweb** [comment]
created in the Installer script on BitBucket repro, will test it shortly 

New Version are create like This
7 1912.0.nnnn

Major = 7
Minor = 1912
Patch = 0
nnnn = incremental buildnumber through all DTAP Stages

The DTAP stage must be written to a different Registry Value to pickup from BISF.psm1 and analyze the DTAP Stage.

In the current registry value the Version as shown above will be written (7.1912.0.1000)

**Comment by matthias-schlimm** [comment]
Create new Packaging POSH Script to build the installer:
