### ISSUE TITLE
ADMX: Move FSlogix to Microsoft

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#91]
FSLogix is now a part of Microsoft, possible to move to ADMX as well

**Comment by JonathanPitre** [comment]
@matthias-schlimm It was done already in the develop branch.

**Comment by JonathanPitre** [comment]
@matthias-schlimm Oh I see, it was overwritten by the bugs bunny branch, I'll redo the change then, np

**Comment by EUCweb** [comment]
Please add your changes from the admx again, but do not replace it with your local copy, the admx between 6.1.0 and bugs bunny release is different, wem changes and some others.

**Comment by JonathanPitre** [comment]
Done in latest develop commit
