### ISSUE TITLE
Detect Citrix Cloud Connector installation

### ISSUE THREAD

**Issue by JonathanPitre** [EUCweb/BIS-F#93]
Each machine hosting the Cloud Connector must have **a unique SID and connector ID** so that Citrix Cloud can communicate reliably with the machines in your resource location. 

Installing the Cloud Connector on a machine template (before cloning) is not supported. If you clone a machine with the Cloud Connector installed, the Cloud Connector services will not run and the machine cannot connect to Citrix Cloud.

[Considerations for cloned machines](https://docs.citrix.com/en-us/citrix-cloud/citrix-cloud-resource-locations/citrix-cloud-connector/installation.html)

BISF-F should detect if the Citrix Cloud Connector is installed and give a warning or even stop the sealing process.

**Comment by matthias-schlimm** [comment]
need the servicenames first, to detect the installation of cloudconnector

**Comment by matthias-schlimm** [comment]
PS C:\windows\system32> Get-Service Citrix* | ft -AutoSize

Status  Name                                   DisplayName

Running Citrix NetScaler Cloud Gateway         Citrix NetScaler Cloud Gateway
Running CitrixConfigSyncService                Citrix Config Synchronizer Service
Running CitrixHighAvailabilityService          Citrix High Availability Service
Running CitrixITSMAdapterProvider              Citrix ITSM Adapter Provider
Stopped CitrixWemAuthSvc                       Citrix WEM Cloud Authentication Service
Stopped CitrixWemMsgSvc                        Citrix WEM Cloud Messaging Service
Stopped CitrixWorkspaceCloudADProvider         Citrix Cloud Services AD Provider
Stopped CitrixWorkspaceCloudAgentDiscovery     Citrix Cloud Services Agent Discovery
Running CitrixWorkspaceCloudAgentLogger        Citrix Cloud Services Agent Logger
Running CitrixWorkspaceCloudAgentSystem        Citrix Cloud Services Agent System
Running CitrixWorkspaceCloudAgentWatchDog      Citrix Cloud Services Agent WatchDog
Stopped CitrixWorkspaceCloudCredentialProvider Citrix Cloud Services Credential Provider
Stopped CitrixWorkspaceCloudWebRelayProvider   Citrix Cloud Services WebRelay Provider

**Comment by matthias-schlimm** [comment]
BISF.psm1 new function Test-CitrixCloudConnector and call it in preparation at BISF.ps1
