### ISSUE TITLE
Nutanix Xi Frame Support 

### ISSUE THREAD

**Issue by matthias-schlimm** [EUCweb/BIS-F#97]
I would like to integrate Frame in the next major release, need a screenshot of the Frame Agent service , the displayname and the servicename that is installed inside the Windows VM, to detect Xi Frame with BIS-F.

**Comment by vMathias79** [comment]
**As per current analysis of a running Frame Sandbox:**

Service name: MF2Service
Display name: MF2Service
Description: Mainframe2 service for starting MF2Server
Path to executable: "c:\Program Files\Frame\service\Service.Windows.exe"

![image](https://user-images.githubusercontent.com/475729/57489756-5577b180-72b7-11e9-8e92-0f0d75d38b27.png)

**Comment by EUCweb** [comment]
integrated in https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Global/BISF.psm1

**Comment by EUCweb** [comment]
@MathiasK-SVA can you grab a copy of this 2 files:
https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Global/BISF.ps1
https://github.com/EUCweb/BIS-F/blob/develop/Framework/SubCall/Global/BISF.psm1

and make a review if the XI Frame is detected from BIS-F ?

**Comment by vMathias79** [comment]
Yes will do over the upcoming weekend!

**Comment by EUCweb** [comment]
it's now in BB_develop branch @MathiasK-SVA
