### ISSUE TITLE
Detect and fix trust relationship issue automatically

### ISSUE THREAD

**Issue by JonathanPitre** [EUCweb/BIS-F#99]
It,s quite common with master images to get trust relationship issues when they get disconnected from the domain for too long for instance. We could detect the event log that indicate that there is a trust relationship issue and run the appropriate powershell commands to fix it automatically.

https://theitbros.com/fix-trust-relationship-failed-without-domain-rejoining/

Reset-ComputerMachinePassword -Server $env:logonserver -Credential $env:USERDOMAIN\$env:USERNAME
Test-ComputerSecureChannel -Repair -Credential $env:USERDOMAIN\$env:USERNAME
nltest /sc_verify:corp.contoso.com

How to detect the event log id:

(Get-EvenLog -LogName System -after ((Get-Date).AddDays(-1))).Where{$_.InstanceID -eq "5723 -Or $_.InstanceID -eq "5721"

https://devblogs.microsoft.com/scripting/event-log-queries-using-powershell/
https://www.itprotoday.com/windows-8/powershell-event-id-searching

**Comment by matthias-schlimm** [comment]
@JonathanPitre Good idea, but how can we automate this ? this can be done during BIS-F personalization but we need account with the privileged rights. I' don't want to store the password in the BIS-F policy
